from typing import List
from typing import overload
import ghidra.features.bsim.gui.filters
import java.lang
import javax.swing


class MultiChoiceBSimValueEditor(object, ghidra.features.bsim.gui.filters.BSimValueEditor):
    FILTER_DELIMETER: unicode = u','
    INVALID_COLOR: java.awt.Color
    VALID_COLOR: java.awt.Color



    def __init__(self, __a0: ghidra.features.bsim.gui.filters.BSimFilterType, __a1: List[object], __a2: List[object], __a3: unicode, __a4: utility.function.Callback): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getComponent(self) -> javax.swing.JComponent: ...

    def getValues(self) -> List[object]: ...

    def hasValidValues(self) -> bool: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def setValues(self, __a0: List[object]) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def component(self) -> javax.swing.JComponent: ...

    @property
    def values(self) -> List[object]: ...

    @values.setter
    def values(self, value: List[object]) -> None: ...