from typing import overload
import ghidra.features.bsim.query.client.tables
import java.lang
import java.sql


class CachedStatement(object):




    def __init__(self): ...



    def close(self) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getStatement(self) -> java.sql.Statement: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def prepareIfNeeded(self, __a0: ghidra.features.bsim.query.client.tables.StatementSupplier) -> java.sql.Statement: ...

    def setStatement(self, __a0: java.sql.Statement) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def statement(self) -> java.sql.Statement: ...

    @statement.setter
    def statement(self, value: java.sql.Statement) -> None: ...