from typing import List
from typing import overload
import ghidra.file.formats.squashfs
import ghidra.util.task
import java.lang


class SquashInodeTable(object):




    def __init__(self, __a0: ghidra.app.util.bin.BinaryReader, __a1: ghidra.file.formats.squashfs.SquashSuperBlock, __a2: ghidra.util.task.TaskMonitor): ...



    def buildRelationships(self, __a0: ghidra.util.task.TaskMonitor) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getInodeByNumber(self, __a0: int) -> ghidra.file.formats.squashfs.SquashInode: ...

    def getInodes(self) -> List[ghidra.file.formats.squashfs.SquashInode]: ...

    def getRootInode(self) -> ghidra.file.formats.squashfs.SquashInode: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def inodes(self) -> List[ghidra.file.formats.squashfs.SquashInode]: ...

    @property
    def rootInode(self) -> ghidra.file.formats.squashfs.SquashInode: ...