from typing import List
from typing import overload
import ghidra.file.formats.squashfs
import java.lang


class SquashFragmentTable(object):




    def __init__(self, __a0: ghidra.app.util.bin.BinaryReader, __a1: ghidra.file.formats.squashfs.SquashSuperBlock, __a2: ghidra.util.task.TaskMonitor): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getFragment(self, __a0: int) -> ghidra.file.formats.squashfs.SquashFragment: ...

    def getFragments(self) -> List[object]: ...

    def getMinFragPointer(self) -> long: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def fragments(self) -> List[object]: ...

    @property
    def minFragPointer(self) -> long: ...