from typing import overload
import ghidra.file.formats.squashfs
import java.lang


class SquashOtherInode(ghidra.file.formats.squashfs.SquashInode):




    def __init__(self, __a0: ghidra.app.util.bin.BinaryReader, __a1: ghidra.file.formats.squashfs.SquashSuperBlock, __a2: int): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getDeviceNumber(self) -> long: ...

    def getDirectoryTableEntry(self) -> ghidra.file.formats.squashfs.SquashDirectoryTableEntry: ...

    def getGroupID(self) -> int: ...

    def getLinkCount(self) -> long: ...

    def getModTime(self) -> long: ...

    def getNumber(self) -> int: ...

    def getParent(self) -> ghidra.file.formats.squashfs.SquashBasicDirectoryInode: ...

    def getPermissions(self) -> int: ...

    def getTargetSize(self) -> int: ...

    def getType(self) -> int: ...

    def getUserID(self) -> int: ...

    def getXattrIndex(self) -> long: ...

    def hashCode(self) -> int: ...

    def isDir(self) -> bool: ...

    def isFile(self) -> bool: ...

    def isSymLink(self) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def deviceNumber(self) -> long: ...

    @property
    def linkCount(self) -> long: ...

    @property
    def targetSize(self) -> int: ...

    @property
    def xattrIndex(self) -> long: ...