
# This file was generated by 'versioneer.py' (0.29+8.gf9bbd1b) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-07-12T19:35:44+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "547d7b8bcc8fde161710b06268c1039a7c3ea143",
 "version": "0.62.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
