
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-07-12T18:23:13+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "dd773863858ff51d88811084a111006f72d56df8",
 "version": "0.13.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
