"""
    HW Mux Reservation System

    No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)  # noqa: E501

    The version of the OpenAPI document: 2.31.0
    Generated by: https://openapi-generator.tech
"""


import sys
import unittest

import hwmux_client
from hwmux_client.model.status_f39_enum import StatusF39Enum


class TestStatusF39Enum(unittest.TestCase):
    """StatusF39Enum unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testStatusF39Enum(self):
        """Test StatusF39Enum"""
        # FIXME: construct object with mandatory attributes with example values
        # model = StatusF39Enum()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
