from typing import overload
import ghidra.app.util.demangler.swift.nodes
import java.lang


class SwiftDemangledTree(object):




    def __init__(self, __a0: ghidra.app.util.demangler.swift.SwiftNativeDemangler, __a1: unicode): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getDemangledString(self) -> unicode: ...

    def getRoot(self) -> ghidra.app.util.demangler.swift.nodes.SwiftNode: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def demangledString(self) -> unicode: ...

    @property
    def root(self) -> ghidra.app.util.demangler.swift.nodes.SwiftNode: ...