from typing import overload
import java.lang
import java.net
import java.util.concurrent


class AbstractAsyncServer(object):




    def __init__(self, __a0: java.net.SocketAddress): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getLocalAddress(self) -> java.net.SocketAddress: ...

    def hashCode(self) -> int: ...

    def launchAsyncService(self) -> java.util.concurrent.CompletableFuture: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def terminate(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def localAddress(self) -> java.net.SocketAddress: ...