from .FridaArmDebuggerMappingOpinion import FridaArmDebuggerMappingOpinion as FridaArmDebuggerMappingOpinion
from .FridaDebuggerPlatformOpinion import FridaDebuggerPlatformOpinion as FridaDebuggerPlatformOpinion
from .FridaDebuggerProgramLaunchOpinion import FridaDebuggerProgramLaunchOpinion as FridaDebuggerProgramLaunchOpinion
from .FridaX86DebuggerMappingOpinion import FridaX86DebuggerMappingOpinion as FridaX86DebuggerMappingOpinion