from typing import List
from typing import overload
import ghidra.file.formats.cramfs
import java.lang


class CramFsBlockFactory(object):




    def __init__(self, __a0: ghidra.file.formats.cramfs.CramFsInode, __a1: ghidra.app.util.bin.ByteProvider, __a2: List[object], __a3: bool): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getCramfsInode(self) -> ghidra.file.formats.cramfs.CramFsInode: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def produceBlocks(self) -> List[object]: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def cramfsInode(self) -> ghidra.file.formats.cramfs.CramFsInode: ...