
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-07-14T16:46:38+1000",
 "dirty": false,
 "error": null,
 "full-revisionid": "139d8db2f66e4fa4afcd2b6ca22f53feadc030c8",
 "version": "3.0.0a3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
