from typing import List
from typing import overload
import java.awt
import java.lang
import javax.swing


class InteractivePanelManager(object):




    def __init__(self): ...



    def addComponent(self, __a0: unicode, __a1: javax.swing.JComponent) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getColumnHeader(self) -> javax.swing.JComponent: ...

    def getColumnWidth(self, __a0: unicode) -> int: ...

    def getComponents(self) -> List[object]: ...

    def getMainPanel(self) -> javax.swing.JComponent: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def removeComponent(self, __a0: javax.swing.JComponent) -> None: ...

    def resetColumnWidthToPreferredWidth(self, __a0: unicode) -> None: ...

    def setColumnWidth(self, __a0: unicode, __a1: int) -> None: ...

    def setHeaderFont(self, __a0: java.awt.Font) -> None: ...

    def setName(self, __a0: javax.swing.JComponent, __a1: unicode) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def columnHeader(self) -> javax.swing.JComponent: ...

    @property
    def components(self) -> List[object]: ...

    @property
    def headerFont(self) -> None: ...  # No getter available.

    @headerFont.setter
    def headerFont(self, value: java.awt.Font) -> None: ...

    @property
    def mainPanel(self) -> javax.swing.JComponent: ...