from typing import overload
import ghidra.app.plugin.core.debug.gui.stack.vars
import java.lang


class VariableValueTable(object):




    def __init__(self): ...



    def add(self, __a0: ghidra.app.plugin.core.debug.gui.stack.vars.VariableValueRow) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def get(self, __a0: ghidra.app.plugin.core.debug.gui.stack.vars.VariableValueRow.RowKey) -> ghidra.app.plugin.core.debug.gui.stack.vars.VariableValueRow: ...

    def getClass(self) -> java.lang.Class: ...

    def getNumRows(self) -> int: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def remove(self, __a0: ghidra.app.plugin.core.debug.gui.stack.vars.VariableValueRow.RowKey) -> None: ...

    def reportDetails(self) -> None: ...

    def toHtml(self) -> unicode: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def numRows(self) -> int: ...