from bpkio_cli.commands.addons import addons
from bpkio_cli.commands.configure import configure
from bpkio_cli.commands.consumption import consumption
from bpkio_cli.commands.hello import hello
from bpkio_cli.commands.memory import memory
from bpkio_cli.commands.package import package
from bpkio_cli.commands.profiles import profile
from bpkio_cli.commands.recorder import record
from bpkio_cli.commands.services import add_services_section
from bpkio_cli.commands.sources import add_sources_section
from bpkio_cli.commands.tenants import add_tenants_commands
from bpkio_cli.commands.url import url
from bpkio_cli.commands.users import add_users_commands
from bpkio_cli.commands.categories import add_categories_commands
from bpkio_cli.commands.archive import archive
