from typing import List
from typing import overload
import ghidra.program.model.address
import ghidra.trace.database.space
import ghidra.trace.model.listing
import ghidra.trace.model.thread
import java.lang
import java.util


class DBTraceCodeSpace(object, ghidra.trace.model.listing.TraceCodeSpace, ghidra.trace.database.space.DBTraceSpaceBased):




    def __init__(self, __a0: ghidra.trace.database.listing.DBTraceCodeManager, __a1: db.DBHandle, __a2: ghidra.program.model.address.AddressSpace, __a3: ghidra.trace.database.space.AbstractDBTraceSpaceBasedManager.DBTraceSpaceEntry, __a4: ghidra.trace.model.thread.TraceThread): ...



    @overload
    def assertInSpace(self, __a0: ghidra.program.model.address.Address) -> long: ...

    @overload
    def assertInSpace(self, __a0: ghidra.program.model.address.AddressRange) -> None: ...

    def bytesChanged(self, __a0: java.util.Set, __a1: long, __a2: ghidra.program.model.address.Address, __a3: List[int], __a4: List[int]) -> None: ...

    def codeUnits(self) -> ghidra.trace.model.listing.TraceCodeUnitsView: ...

    @staticmethod
    def create(__a0: ghidra.program.model.address.AddressSpace, __a1: ghidra.trace.model.thread.TraceThread, __a2: int) -> ghidra.trace.database.space.DBTraceSpaceKey: ...

    def data(self) -> ghidra.trace.model.listing.TraceDataView: ...

    def definedData(self) -> ghidra.trace.model.listing.TraceDefinedDataView: ...

    def definedUnits(self) -> ghidra.trace.model.listing.TraceDefinedUnitsView: ...

    def equals(self, __a0: object) -> bool: ...

    def explainLanguages(self, __a0: ghidra.program.model.address.AddressSpace) -> unicode: ...

    def getAddressSpace(self) -> ghidra.program.model.address.AddressSpace: ...

    def getClass(self) -> java.lang.Class: ...

    def getFrameLevel(self) -> int: ...

    def getThread(self) -> ghidra.trace.model.thread.TraceThread: ...

    def hashCode(self) -> int: ...

    def instructions(self) -> ghidra.trace.model.listing.TraceInstructionsView: ...

    def invalidateCache(self) -> None: ...

    def isMySpace(self, __a0: ghidra.program.model.address.AddressSpace) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toAddress(self, __a0: long) -> ghidra.program.model.address.Address: ...

    def toOverlay(self, __a0: ghidra.program.model.address.Address) -> ghidra.program.model.address.Address: ...

    def toString(self) -> unicode: ...

    def undefinedData(self) -> ghidra.trace.model.listing.TraceUndefinedDataView: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def addressSpace(self) -> ghidra.program.model.address.AddressSpace: ...

    @property
    def frameLevel(self) -> int: ...

    @property
    def thread(self) -> ghidra.trace.model.thread.TraceThread: ...