from paqueteoptimizacionelizabethrm import funciones
from paqueteoptimizacionelizabethrm import multivariable
from paqueteoptimizacionelizabethrm import univariable
from paqueteoptimizacionelizabethrm import utils