from typing import overload
import ghidra.util.task
import java.lang


class CloseableTaskMonitor(ghidra.util.task.TaskMonitor, java.lang.AutoCloseable, object):
    DUMMY: ghidra.util.task.TaskMonitor
    NO_PROGRESS_VALUE: int = -1







    def addCancelledListener(self, __a0: ghidra.util.task.CancelledListener) -> None: ...

    def cancel(self) -> None: ...

    def checkCanceled(self) -> None: ...

    def checkCancelled(self) -> None: ...

    def clearCanceled(self) -> None: ...

    def clearCancelled(self) -> None: ...

    def close(self) -> None: ...

    @staticmethod
    def dummyIfNull(__a0: ghidra.util.task.TaskMonitor) -> ghidra.util.task.TaskMonitor: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getMaximum(self) -> long: ...

    def getMessage(self) -> unicode: ...

    def getProgress(self) -> long: ...

    def hashCode(self) -> int: ...

    @overload
    def increment(self) -> None: ...

    @overload
    def increment(self, __a0: long) -> None: ...

    @overload
    def incrementProgress(self) -> None: ...

    @overload
    def incrementProgress(self, __a0: long) -> None: ...

    @overload
    def initialize(self, __a0: long) -> None: ...

    @overload
    def initialize(self, __a0: long, __a1: unicode) -> None: ...

    def isCancelEnabled(self) -> bool: ...

    def isCancelled(self) -> bool: ...

    def isIndeterminate(self) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def removeCancelledListener(self, __a0: ghidra.util.task.CancelledListener) -> None: ...

    def reportError(self, __a0: java.lang.Throwable) -> None: ...

    def setCancelEnabled(self, __a0: bool) -> None: ...

    def setIndeterminate(self, __a0: bool) -> None: ...

    def setMaximum(self, __a0: long) -> None: ...

    def setMessage(self, __a0: unicode) -> None: ...

    def setProgress(self, __a0: long) -> None: ...

    def setShowProgressValue(self, __a0: bool) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def cancelEnabled(self) -> bool: ...

    @cancelEnabled.setter
    def cancelEnabled(self, value: bool) -> None: ...

    @property
    def cancelled(self) -> bool: ...

    @property
    def indeterminate(self) -> bool: ...

    @indeterminate.setter
    def indeterminate(self, value: bool) -> None: ...

    @property
    def maximum(self) -> long: ...

    @maximum.setter
    def maximum(self, value: long) -> None: ...

    @property
    def message(self) -> unicode: ...

    @message.setter
    def message(self, value: unicode) -> None: ...

    @property
    def progress(self) -> long: ...

    @progress.setter
    def progress(self, value: long) -> None: ...

    @property
    def showProgressValue(self) -> None: ...  # No getter available.

    @showProgressValue.setter
    def showProgressValue(self, value: bool) -> None: ...