from typing import List
from typing import overload
import ghidra.dbg.memory
import java.lang
import java.util.concurrent


class CachedMemory(object, ghidra.dbg.memory.MemoryReader, ghidra.dbg.memory.MemoryWriter):




    def __init__(self, __a0: ghidra.dbg.memory.MemoryReader, __a1: ghidra.dbg.memory.MemoryWriter): ...



    def clear(self) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def readMemory(self, __a0: long, __a1: int) -> java.util.concurrent.CompletableFuture: ...

    def toString(self) -> unicode: ...

    def updateMemory(self, __a0: long, __a1: List[int]) -> None: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    def writeMemory(self, __a0: long, __a1: List[int]) -> java.util.concurrent.CompletableFuture: ...

