from typing import List
from typing import overload
import ghidra.features.bsim.query.client.tables
import ghidra.features.bsim.query.description
import java.lang
import java.sql


class CallgraphTable(ghidra.features.bsim.query.client.tables.SQLComplexTable):





    class CallgraphRow(object):
        dest: long
        src: long



        def __init__(self): ...



        def equals(self, __a0: object) -> bool: ...

        def getClass(self) -> java.lang.Class: ...

        def hashCode(self) -> int: ...

        def notify(self) -> None: ...

        def notifyAll(self) -> None: ...

        def toString(self) -> unicode: ...

        @overload
        def wait(self) -> None: ...

        @overload
        def wait(self, __a0: long) -> None: ...

        @overload
        def wait(self, __a0: long, __a1: int) -> None: ...



    def __init__(self): ...



    def close(self) -> None: ...

    def create(self, __a0: java.sql.Statement) -> None: ...

    def delete(self, __a0: long) -> int: ...

    def drop(self, __a0: java.sql.Statement) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    @staticmethod
    def extractCallgraphRow(__a0: java.sql.ResultSet) -> ghidra.features.bsim.query.client.tables.CallgraphTable.CallgraphRow: ...

    def getClass(self) -> java.lang.Class: ...

    def hashCode(self) -> int: ...

    def insert(self, __a0: List[object]) -> long: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def queryCallgraphRows(self, __a0: ghidra.features.bsim.query.description.FunctionDescription, __a1: bool) -> List[object]: ...

    def setConnection(self, __a0: java.sql.Connection) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

