from typing import overload
import ghidra.program.model.address
import ghidra.trace.model
import ghidra.trace.model.symbol
import ghidra.trace.model.thread
import java.lang
import java.util


class TraceSymbolWithLocationView(ghidra.trace.model.symbol.TraceSymbolView, object):








    def equals(self, __a0: object) -> bool: ...

    def getAll(self, __a0: bool) -> java.util.Collection: ...

    def getAt(self, __a0: long, __a1: ghidra.trace.model.thread.TraceThread, __a2: ghidra.program.model.address.Address, __a3: bool) -> java.util.Collection: ...

    def getChildWithNameAt(self, __a0: unicode, __a1: long, __a2: ghidra.trace.model.thread.TraceThread, __a3: ghidra.program.model.address.Address, __a4: ghidra.trace.model.symbol.TraceNamespaceSymbol) -> ghidra.trace.model.symbol.TraceSymbol: ...

    def getChildren(self, __a0: ghidra.trace.model.symbol.TraceNamespaceSymbol) -> java.util.Collection: ...

    def getChildrenNamed(self, __a0: unicode, __a1: ghidra.trace.model.symbol.TraceNamespaceSymbol) -> java.util.Collection: ...

    def getClass(self) -> java.lang.Class: ...

    def getGlobalWithNameAt(self, __a0: unicode, __a1: long, __a2: ghidra.trace.model.thread.TraceThread, __a3: ghidra.program.model.address.Address) -> ghidra.trace.model.symbol.TraceSymbol: ...

    def getGlobals(self) -> java.util.Collection: ...

    def getGlobalsNamed(self, __a0: unicode) -> java.util.Collection: ...

    def getIntersecting(self, __a0: ghidra.trace.model.Lifespan, __a1: ghidra.trace.model.thread.TraceThread, __a2: ghidra.program.model.address.AddressRange, __a3: bool, __a4: bool) -> java.util.Collection: ...

    def getManager(self) -> ghidra.trace.model.symbol.TraceSymbolManager: ...

    def getNamed(self, __a0: unicode) -> java.util.Collection: ...

    def getWithMatchingName(self, __a0: unicode, __a1: bool) -> java.util.Collection: ...

    def hasAt(self, __a0: long, __a1: ghidra.trace.model.thread.TraceThread, __a2: ghidra.program.model.address.Address, __a3: bool) -> bool: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def scanByName(self, __a0: unicode) -> java.util.Iterator: ...

    def size(self, __a0: bool) -> int: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def globals(self) -> java.util.Collection: ...

    @property
    def manager(self) -> ghidra.trace.model.symbol.TraceSymbolManager: ...