from typing import overload
import ghidra.program.model.address
import ghidra.trace.model
import ghidra.trace.model.stack
import ghidra.trace.model.symbol
import ghidra.trace.model.thread
import ghidra.util.task
import java.lang
import java.util


class TraceEquateManager(ghidra.trace.model.symbol.TraceEquateOperations, object):








    @overload
    def clearReferences(self, __a0: ghidra.trace.model.Lifespan, __a1: ghidra.program.model.address.AddressRange, __a2: ghidra.util.task.TaskMonitor) -> None: ...

    @overload
    def clearReferences(self, __a0: ghidra.trace.model.Lifespan, __a1: ghidra.program.model.address.AddressSetView, __a2: ghidra.util.task.TaskMonitor) -> None: ...

    def create(self, __a0: unicode, __a1: long) -> ghidra.trace.model.symbol.TraceEquate: ...

    def equals(self, __a0: object) -> bool: ...

    def getAll(self) -> java.util.Collection: ...

    def getByKey(self, __a0: long) -> ghidra.trace.model.symbol.TraceEquate: ...

    def getByName(self, __a0: unicode) -> ghidra.trace.model.symbol.TraceEquate: ...

    def getByValue(self, __a0: long) -> java.util.Collection: ...

    def getClass(self) -> java.lang.Class: ...

    @overload
    def getEquateRegisterSpace(self, __a0: ghidra.trace.model.stack.TraceStackFrame, __a1: bool) -> ghidra.trace.model.symbol.TraceEquateSpace: ...

    @overload
    def getEquateRegisterSpace(self, __a0: ghidra.trace.model.thread.TraceThread, __a1: bool) -> ghidra.trace.model.symbol.TraceEquateSpace: ...

    def getEquateSpace(self, __a0: ghidra.program.model.address.AddressSpace, __a1: bool) -> ghidra.trace.model.symbol.TraceEquateSpace: ...

    @overload
    def getReferenced(self, __a0: long, __a1: ghidra.program.model.address.Address) -> java.util.Collection: ...

    @overload
    def getReferenced(self, __a0: long, __a1: ghidra.program.model.address.Address, __a2: int) -> java.util.Collection: ...

    def getReferencedByValue(self, __a0: long, __a1: ghidra.program.model.address.Address, __a2: int, __a3: long) -> ghidra.trace.model.symbol.TraceEquate: ...

    def getReferringAddresses(self, __a0: ghidra.trace.model.Lifespan) -> ghidra.program.model.address.AddressSetView: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @staticmethod
    def validateName(__a0: unicode) -> None: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def all(self) -> java.util.Collection: ...