from typing import overload
import ghidra.features.bsim.query
import ghidra.features.bsim.query.file
import java.lang
import java.net
import java.sql
import java.util


class BSimH2FileDBConnectionManager(object):





    class BSimH2FileDataSource(object, ghidra.features.bsim.query.BSimJDBCDataSource):








        def delete(self) -> None: ...

        def dispose(self) -> None: ...

        def equals(self, __a0: object) -> bool: ...

        def exists(self) -> bool: ...

        def getActiveConnections(self) -> int: ...

        def getClass(self) -> java.lang.Class: ...

        def getConnection(self) -> java.sql.Connection: ...

        def getConnectionType(self) -> ghidra.features.bsim.query.FunctionDatabase.ConnectionType: ...

        def getServerInfo(self) -> ghidra.features.bsim.query.BSimServerInfo: ...

        def getStatus(self) -> ghidra.features.bsim.query.FunctionDatabase.Status: ...

        def hashCode(self) -> int: ...

        def notify(self) -> None: ...

        def notifyAll(self) -> None: ...

        def toString(self) -> unicode: ...

        @overload
        def wait(self) -> None: ...

        @overload
        def wait(self, __a0: long) -> None: ...

        @overload
        def wait(self, __a0: long, __a1: int) -> None: ...

        @property
        def activeConnections(self) -> int: ...

        @property
        def connection(self) -> java.sql.Connection: ...

        @property
        def connectionType(self) -> ghidra.features.bsim.query.FunctionDatabase.ConnectionType: ...

        @property
        def serverInfo(self) -> ghidra.features.bsim.query.BSimServerInfo: ...

        @property
        def status(self) -> ghidra.features.bsim.query.FunctionDatabase.Status: ...

    def __init__(self): ...



    def equals(self, __a0: object) -> bool: ...

    @staticmethod
    def getAllDataSources() -> java.util.Collection: ...

    def getClass(self) -> java.lang.Class: ...

    @overload
    @staticmethod
    def getDataSource(__a0: ghidra.features.bsim.query.BSimServerInfo) -> ghidra.features.bsim.query.file.BSimH2FileDBConnectionManager.BSimH2FileDataSource: ...

    @overload
    @staticmethod
    def getDataSource(__a0: java.net.URL) -> ghidra.features.bsim.query.file.BSimH2FileDBConnectionManager.BSimH2FileDataSource: ...

    @staticmethod
    def getDataSourceIfExists(__a0: ghidra.features.bsim.query.BSimServerInfo) -> ghidra.features.bsim.query.file.BSimH2FileDBConnectionManager.BSimH2FileDataSource: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

