from typing import overload
import ghidra.app.util.importer
import ghidra.file.formats.android.dex.format
import ghidra.file.formats.android.oat
import ghidra.file.formats.android.oat.oatdexfile
import ghidra.program.model.data
import ghidra.program.model.listing
import ghidra.util.task
import java.lang


class OatDexFile_R(ghidra.file.formats.android.oat.oatdexfile.OatDexFile_Pie):




    def __init__(self, __a0: ghidra.app.util.bin.BinaryReader, __a1: ghidra.file.formats.android.oat.bundle.OatBundle): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getDexFileChecksum(self) -> int: ...

    def getDexFileLocation(self) -> unicode: ...

    def getDexFileOffset(self) -> int: ...

    def getDexHeader(self) -> ghidra.file.formats.android.dex.format.DexHeader: ...

    def getDexLayoutSections(self) -> int: ...

    def getLookupTable(self) -> int: ...

    def getLookupTableData(self) -> int: ...

    def getMethodBssMapping(self) -> int: ...

    def getOatClassOffsetsPointer(self) -> int: ...

    def getStringBssMapping(self) -> int: ...

    def getTypeBssMapping(self) -> int: ...

    def hashCode(self) -> int: ...

    def isDexHeaderExternal(self) -> bool: ...

    def markup(self, __a0: ghidra.file.formats.android.oat.OatHeader, __a1: ghidra.program.model.listing.Program, __a2: ghidra.util.task.TaskMonitor, __a3: ghidra.app.util.importer.MessageLog) -> None: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toDataType(self) -> ghidra.program.model.data.DataType: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def dexFileChecksum(self) -> int: ...

    @property
    def dexFileLocation(self) -> unicode: ...

    @property
    def dexFileOffset(self) -> int: ...

    @property
    def dexHeader(self) -> ghidra.file.formats.android.dex.format.DexHeader: ...

    @property
    def dexHeaderExternal(self) -> bool: ...

    @property
    def dexLayoutSections(self) -> int: ...

    @property
    def lookupTable(self) -> int: ...

    @property
    def lookupTableData(self) -> int: ...

    @property
    def methodBssMapping(self) -> int: ...

    @property
    def oatClassOffsetsPointer(self) -> int: ...

    @property
    def stringBssMapping(self) -> int: ...

    @property
    def typeBssMapping(self) -> int: ...