from typing import List
from typing import overload
import ghidra.pty
import ghidra.pty.windows
import java.lang
import java.util


class ConPtyFactory(java.lang.Enum, ghidra.pty.PtyFactory):
    INSTANCE: ghidra.pty.windows.ConPtyFactory







    @overload
    def compareTo(self, __a0: java.lang.Enum) -> int: ...

    @overload
    def compareTo(self, __a0: object) -> int: ...

    def describeConstable(self) -> java.util.Optional: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getDeclaringClass(self) -> java.lang.Class: ...

    def getDescription(self) -> unicode: ...

    def hashCode(self) -> int: ...

    @staticmethod
    def local() -> ghidra.pty.PtyFactory: ...

    def name(self) -> unicode: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    @overload
    def openpty(self) -> ghidra.pty.Pty: ...

    @overload
    def openpty(self, __a0: int, __a1: int) -> ghidra.pty.Pty: ...

    @overload
    def openpty(self, __a0: int, __a1: int) -> ghidra.pty.Pty: ...

    def ordinal(self) -> int: ...

    def toString(self) -> unicode: ...

    @overload
    @staticmethod
    def valueOf(__a0: unicode) -> ghidra.pty.windows.ConPtyFactory: ...

    @overload
    @staticmethod
    def valueOf(__a0: java.lang.Class, __a1: unicode) -> java.lang.Enum: ...

    @staticmethod
    def values() -> List[ghidra.pty.windows.ConPtyFactory]: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def description(self) -> unicode: ...