
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-07-12T17:56:13+0800",
 "dirty": false,
 "error": null,
 "full-revisionid": "5e3f254d48383f37d849dd16db564ad9449e5163",
 "version": "0.13.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
