from typing import List
from typing import overload
import ghidra.file.formats.android.oat.oatclass
import ghidra.program.model.data
import java.lang


class OatClass_Q(ghidra.file.formats.android.oat.oatclass.OatClass_Pie):








    def equals(self, __a0: object) -> bool: ...

    def getBitmap(self) -> List[int]: ...

    def getBitmapSize(self) -> int: ...

    def getClass(self) -> java.lang.Class: ...

    def getMethodOffsets(self) -> List[object]: ...

    def getStatus(self) -> int: ...

    def getType(self) -> ghidra.file.formats.android.oat.oatclass.OatClassType: ...

    def hashCode(self) -> int: ...

    def isMethodNative(self, __a0: int) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toDataType(self) -> ghidra.program.model.data.DataType: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

