
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-07-10T14:17:36+0100",
 "dirty": false,
 "error": null,
 "full-revisionid": "21fdfbeddef04f4fe7aa7700ecaf5f5fd610a5cc",
 "version": "3.0.7"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
