from typing import overload
import docking.action
import docking.widgets
import ghidra.debug.api.tracemgr
import ghidra.framework.options
import ghidra.program.model.listing
import ghidra.program.util
import java.lang


class DebuggerStaticSyncTrait(object):




    def __init__(self, __a0: ghidra.framework.plugintool.PluginTool, __a1: ghidra.framework.plugintool.Plugin, __a2: docking.ComponentProvider, __a3: bool): ...



    def doAutoSyncCursorFromStatic(self) -> None: ...

    def doAutoSyncCursorIntoStatic(self, __a0: ghidra.program.util.ProgramLocation) -> None: ...

    def dynamicProgramLocationChanged(self, __a0: ghidra.program.util.ProgramLocation, __a1: docking.widgets.EventTrigger) -> None: ...

    def dynamicSelectionChanged(self, __a0: ghidra.program.model.listing.Program, __a1: ghidra.program.util.ProgramSelection, __a2: docking.widgets.EventTrigger) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def goToCoordinates(self, __a0: ghidra.debug.api.tracemgr.DebuggerCoordinates) -> None: ...

    def hashCode(self) -> int: ...

    def installAutoSyncCursorWithStaticListingAction(self) -> docking.action.ToggleDockingAction: ...

    def installAutoSyncSelectionWithStaticListingAction(self) -> docking.action.ToggleDockingAction: ...

    def installSyncSelectionFromStaticListingAction(self) -> docking.action.DockingAction: ...

    def installSyncSelectionIntoStaticListingAction(self) -> docking.action.DockingAction: ...

    def isAutoSyncCursorWithStaticListing(self) -> bool: ...

    def isAutoSyncSelectionWithStaticListing(self) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def readConfigState(self, __a0: ghidra.framework.options.SaveState) -> None: ...

    def setAutoSyncCursorWithStaticListing(self, __a0: bool) -> None: ...

    def setAutoSyncSelectionWithStaticListing(self, __a0: bool) -> None: ...

    def staticProgramActivated(self, __a0: ghidra.program.model.listing.Program) -> None: ...

    def staticProgramLocationChanged(self, __a0: ghidra.program.util.ProgramLocation) -> None: ...

    def staticProgramSelectionChanged(self, __a0: ghidra.program.model.listing.Program, __a1: ghidra.program.util.ProgramSelection) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def autoSyncCursorWithStaticListing(self) -> bool: ...

    @autoSyncCursorWithStaticListing.setter
    def autoSyncCursorWithStaticListing(self, value: bool) -> None: ...

    @property
    def autoSyncSelectionWithStaticListing(self) -> bool: ...

    @autoSyncSelectionWithStaticListing.setter
    def autoSyncSelectionWithStaticListing(self, value: bool) -> None: ...