from typing import List
from typing import overload
import ghidra.features.bsim.gui.filters
import ghidra.features.bsim.gui.search.dialog
import ghidra.features.bsim.query.protocol
import java.lang


class BSimFilterSet(object):





    class FilterEntry(java.lang.Record):




        def __init__(self, __a0: ghidra.features.bsim.gui.filters.BSimFilterType, __a1: List[object]): ...



        def equals(self, __a0: object) -> bool: ...

        def filterType(self) -> ghidra.features.bsim.gui.filters.BSimFilterType: ...

        def getClass(self) -> java.lang.Class: ...

        def hashCode(self) -> int: ...

        def notify(self) -> None: ...

        def notifyAll(self) -> None: ...

        def toString(self) -> unicode: ...

        def values(self) -> List[object]: ...

        @overload
        def wait(self) -> None: ...

        @overload
        def wait(self, __a0: long) -> None: ...

        @overload
        def wait(self, __a0: long, __a1: int) -> None: ...



    def __init__(self): ...



    def addEntry(self, __a0: ghidra.features.bsim.gui.filters.BSimFilterType, __a1: List[object]) -> None: ...

    def copy(self) -> ghidra.features.bsim.gui.search.dialog.BSimFilterSet: ...

    def equals(self, __a0: object) -> bool: ...

    def getBSimFilter(self) -> ghidra.features.bsim.query.protocol.BSimFilter: ...

    def getClass(self) -> java.lang.Class: ...

    def getFilterEntries(self) -> List[object]: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def removeAll(self, __a0: ghidra.features.bsim.gui.filters.BSimFilterType) -> None: ...

    def size(self) -> int: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def BSimFilter(self) -> ghidra.features.bsim.query.protocol.BSimFilter: ...

    @property
    def filterEntries(self) -> List[object]: ...