from typing import overload
import java.awt
import java.lang


class ProportionalHorizontalLayout(object, java.awt.LayoutManager2):





    class Proportion(object):




        def __init__(self, __a0: float): ...



        def equals(self, __a0: object) -> bool: ...

        def getClass(self) -> java.lang.Class: ...

        def hashCode(self) -> int: ...

        def notify(self) -> None: ...

        def notifyAll(self) -> None: ...

        def toString(self) -> unicode: ...

        @overload
        def wait(self) -> None: ...

        @overload
        def wait(self, __a0: long) -> None: ...

        @overload
        def wait(self, __a0: long, __a1: int) -> None: ...



    def __init__(self): ...



    @overload
    def addLayoutComponent(self, __a0: unicode, __a1: java.awt.Component) -> None: ...

    @overload
    def addLayoutComponent(self, __a0: java.awt.Component, __a1: object) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getLayoutAlignmentX(self, __a0: java.awt.Container) -> float: ...

    def getLayoutAlignmentY(self, __a0: java.awt.Container) -> float: ...

    def hashCode(self) -> int: ...

    def invalidateLayout(self, __a0: java.awt.Container) -> None: ...

    def layoutContainer(self, __a0: java.awt.Container) -> None: ...

    def maximumLayoutSize(self, __a0: java.awt.Container) -> java.awt.Dimension: ...

    def minimumLayoutSize(self, __a0: java.awt.Container) -> java.awt.Dimension: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def preferredLayoutSize(self, __a0: java.awt.Container) -> java.awt.Dimension: ...

    def removeLayoutComponent(self, __a0: java.awt.Component) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

