from typing import List
from typing import overload
import ghidra.file.formats.android.bootimg
import ghidra.program.model.data
import java.lang


class BootImageHeaderV1(ghidra.file.formats.android.bootimg.BootImageHeaderV0):




    def __init__(self, __a0: ghidra.app.util.bin.BinaryReader): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getCommandLine(self) -> unicode: ...

    def getExtraCommandLine(self) -> unicode: ...

    def getHeaderSize(self) -> int: ...

    def getHeaderVersion(self) -> int: ...

    def getId(self) -> List[int]: ...

    def getKernelAddress(self) -> int: ...

    def getKernelOffset(self) -> long: ...

    def getKernelPageCount(self) -> int: ...

    def getKernelSize(self) -> int: ...

    def getMagic(self) -> unicode: ...

    def getName(self) -> unicode: ...

    def getOSVersion(self) -> int: ...

    def getPageSize(self) -> int: ...

    def getRamdiskAddress(self) -> int: ...

    def getRamdiskOffset(self) -> int: ...

    def getRamdiskPageCount(self) -> int: ...

    def getRamdiskSize(self) -> int: ...

    def getRecoveryDtboOffset(self) -> long: ...

    def getRecoveryDtboSize(self) -> int: ...

    def getRecoveryDtboSizeAdjusted(self) -> int: ...

    def getSecondAddress(self) -> int: ...

    def getSecondOffset(self) -> long: ...

    def getSecondPageCount(self) -> int: ...

    def getSecondSize(self) -> int: ...

    def getTagsAddress(self) -> int: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def pageAlign(self, __a0: long) -> long: ...

    def toDataType(self) -> ghidra.program.model.data.DataType: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def headerSize(self) -> int: ...

    @property
    def recoveryDtboOffset(self) -> long: ...

    @property
    def recoveryDtboSize(self) -> int: ...

    @property
    def recoveryDtboSizeAdjusted(self) -> int: ...