from typing import List
from typing import overload
import ghidra.file.formats.android.bootimg
import ghidra.program.model.data
import java.lang


class VendorBootImageHeaderV4(ghidra.file.formats.android.bootimg.VendorBootImageHeaderV3):




    def __init__(self, __a0: ghidra.app.util.bin.BinaryReader): ...



    def equals(self, __a0: object) -> bool: ...

    def getBootConfigOffset(self) -> long: ...

    def getBootConfigSize(self) -> int: ...

    def getClass(self) -> java.lang.Class: ...

    def getCmdline(self) -> unicode: ...

    def getDtbAddress(self) -> long: ...

    def getDtbOffset(self) -> long: ...

    def getDtbSize(self) -> int: ...

    def getHeaderSize(self) -> int: ...

    def getHeaderVersion(self) -> int: ...

    def getKernelAddress(self) -> int: ...

    def getMagic(self) -> unicode: ...

    def getName(self) -> unicode: ...

    def getNestedVendorRamdiskCount(self) -> long: ...

    def getNestedVendorRamdiskOffset(self, __a0: int) -> long: ...

    def getNestedVendorRamdiskSize(self, __a0: int) -> int: ...

    def getPageSize(self) -> int: ...

    def getRamdiskAddress(self) -> int: ...

    def getTagsAddress(self) -> int: ...

    def getVendorRamdiskOffset(self) -> long: ...

    def getVendorRamdiskSize(self) -> int: ...

    def getVendorRamdiskTableEntryList(self) -> List[object]: ...

    def getVendorRamdiskTableEntryNum(self) -> int: ...

    def getVendorRamdiskTableEntrySize(self) -> int: ...

    def getVendorRamdiskTableOffset(self) -> long: ...

    def getVendorRamdiskTableSize(self) -> int: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toDataType(self) -> ghidra.program.model.data.DataType: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def bootConfigOffset(self) -> long: ...

    @property
    def bootConfigSize(self) -> int: ...

    @property
    def nestedVendorRamdiskCount(self) -> long: ...

    @property
    def vendorRamdiskTableEntryList(self) -> List[object]: ...

    @property
    def vendorRamdiskTableEntryNum(self) -> int: ...

    @property
    def vendorRamdiskTableEntrySize(self) -> int: ...

    @property
    def vendorRamdiskTableOffset(self) -> long: ...

    @property
    def vendorRamdiskTableSize(self) -> int: ...