from typing import overload
import ghidra.features.bsim.query.protocol
import ghidra.program.model.listing
import java.lang
import java.util


class SFQueryInfo(object):
    DEFAULT_QUERIES_PER_STAGE: int = 10



    def __init__(self, __a0: java.util.Set): ...



    def buildQueryNearest(self) -> ghidra.features.bsim.query.protocol.QueryNearest: ...

    def equals(self, __a0: object) -> bool: ...

    def getBsimFilter(self) -> ghidra.features.bsim.query.protocol.BSimFilter: ...

    def getClass(self) -> java.lang.Class: ...

    def getFilterInfoStrings(self) -> java.util.Collection: ...

    def getFunctions(self) -> java.util.Set: ...

    def getMaximumResults(self) -> int: ...

    def getNumberOfStages(self, __a0: int) -> int: ...

    def getPreFilter(self) -> ghidra.features.bsim.query.protocol.PreFilter: ...

    def getProgram(self) -> ghidra.program.model.listing.Program: ...

    def getSignificanceThreshold(self) -> float: ...

    def getSimilarityThreshold(self) -> float: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def setFunctions(self, __a0: java.util.Set) -> None: ...

    def setMaximumResults(self, __a0: int) -> None: ...

    def setSignificanceThreshold(self, __a0: float) -> None: ...

    def setSimilarityThreshold(self, __a0: float) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def bsimFilter(self) -> ghidra.features.bsim.query.protocol.BSimFilter: ...

    @property
    def filterInfoStrings(self) -> java.util.Collection: ...

    @property
    def functions(self) -> java.util.Set: ...

    @functions.setter
    def functions(self, value: java.util.Set) -> None: ...

    @property
    def maximumResults(self) -> int: ...

    @maximumResults.setter
    def maximumResults(self, value: int) -> None: ...

    @property
    def preFilter(self) -> ghidra.features.bsim.query.protocol.PreFilter: ...

    @property
    def program(self) -> ghidra.program.model.listing.Program: ...

    @property
    def significanceThreshold(self) -> float: ...

    @significanceThreshold.setter
    def significanceThreshold(self, value: float) -> None: ...

    @property
    def similarityThreshold(self) -> float: ...

    @similarityThreshold.setter
    def similarityThreshold(self, value: float) -> None: ...