from wiederverwendbar.starlette_admin.mongoengine.generic_embedded_document_field.converter import Converter
from wiederverwendbar.starlette_admin.mongoengine.generic_embedded_document_field.field import GenericEmbeddedDocumentField
