from typing import overload
import ghidra.file.formats.android.oat.oatmethod
import ghidra.program.model.data
import java.lang


class OatMethodOffsets_Lollipop(ghidra.file.formats.android.oat.oatmethod.OatMethodOffsets):




    def __init__(self, __a0: ghidra.app.util.bin.BinaryReader): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getCodeOffset(self) -> int: ...

    def getGcMapOffset(self) -> int: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toDataType(self) -> ghidra.program.model.data.DataType: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def gcMapOffset(self) -> int: ...