from typing import overload
import java.lang


class CartCancelDialogs(object):
    WRAP_WIDTH_CHARACTERS: int = 80



    def __init__(self): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    @staticmethod
    def promptContinue(__a0: unicode, __a1: unicode, __a2: int) -> bool: ...

    @staticmethod
    def promptErrorContinue(__a0: unicode, __a1: unicode) -> bool: ...

    @staticmethod
    def promptWarningContinue(__a0: unicode, __a1: unicode) -> bool: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

