from typing import overload
import ghidra.file.formats.squashfs
import java.lang


class SquashedFile(object):




    def __init__(self, __a0: ghidra.file.formats.squashfs.SquashInode, __a1: ghidra.file.formats.squashfs.SquashFragment): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getFragment(self) -> ghidra.file.formats.squashfs.SquashFragment: ...

    def getInode(self) -> ghidra.file.formats.squashfs.SquashInode: ...

    def getName(self) -> unicode: ...

    def getPath(self) -> unicode: ...

    def getUncompressedSize(self) -> long: ...

    def hasFragment(self) -> bool: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def fragment(self) -> ghidra.file.formats.squashfs.SquashFragment: ...

    @property
    def inode(self) -> ghidra.file.formats.squashfs.SquashInode: ...

    @property
    def name(self) -> unicode: ...

    @property
    def path(self) -> unicode: ...

    @property
    def uncompressedSize(self) -> long: ...