from typing import overload
import ghidra.file.formats.squashfs
import java.lang


class SquashInode(object):




    def __init__(self, __a0: ghidra.app.util.bin.BinaryReader, __a1: ghidra.file.formats.squashfs.SquashSuperBlock): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getDirectoryTableEntry(self) -> ghidra.file.formats.squashfs.SquashDirectoryTableEntry: ...

    def getGroupID(self) -> int: ...

    def getModTime(self) -> long: ...

    def getNumber(self) -> int: ...

    def getParent(self) -> ghidra.file.formats.squashfs.SquashBasicDirectoryInode: ...

    def getPermissions(self) -> int: ...

    def getType(self) -> int: ...

    def getUserID(self) -> int: ...

    def hashCode(self) -> int: ...

    def isDir(self) -> bool: ...

    def isFile(self) -> bool: ...

    def isSymLink(self) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def dir(self) -> bool: ...

    @property
    def directoryTableEntry(self) -> ghidra.file.formats.squashfs.SquashDirectoryTableEntry: ...

    @property
    def file(self) -> bool: ...

    @property
    def groupID(self) -> int: ...

    @property
    def modTime(self) -> long: ...

    @property
    def number(self) -> int: ...

    @property
    def parent(self) -> ghidra.file.formats.squashfs.SquashBasicDirectoryInode: ...

    @property
    def permissions(self) -> int: ...

    @property
    def symLink(self) -> bool: ...

    @property
    def type(self) -> int: ...

    @property
    def userID(self) -> int: ...