from typing import overload
import java.lang
import java.util.concurrent
import java.util.function


class RemoteAsyncResult(java.util.concurrent.CompletionStage, java.util.concurrent.Future, object):








    def acceptEither(self, __a0: java.util.concurrent.CompletionStage, __a1: java.util.function.Consumer) -> java.util.concurrent.CompletionStage: ...

    @overload
    def acceptEitherAsync(self, __a0: java.util.concurrent.CompletionStage, __a1: java.util.function.Consumer) -> java.util.concurrent.CompletionStage: ...

    @overload
    def acceptEitherAsync(self, __a0: java.util.concurrent.CompletionStage, __a1: java.util.function.Consumer, __a2: java.util.concurrent.Executor) -> java.util.concurrent.CompletionStage: ...

    def applyToEither(self, __a0: java.util.concurrent.CompletionStage, __a1: java.util.function.Function) -> java.util.concurrent.CompletionStage: ...

    @overload
    def applyToEitherAsync(self, __a0: java.util.concurrent.CompletionStage, __a1: java.util.function.Function) -> java.util.concurrent.CompletionStage: ...

    @overload
    def applyToEitherAsync(self, __a0: java.util.concurrent.CompletionStage, __a1: java.util.function.Function, __a2: java.util.concurrent.Executor) -> java.util.concurrent.CompletionStage: ...

    def cancel(self, __a0: bool) -> bool: ...

    def equals(self, __a0: object) -> bool: ...

    def exceptionNow(self) -> java.lang.Throwable: ...

    def exceptionally(self, __a0: java.util.function.Function) -> java.util.concurrent.CompletionStage: ...

    @overload
    def exceptionallyAsync(self, __a0: java.util.function.Function) -> java.util.concurrent.CompletionStage: ...

    @overload
    def exceptionallyAsync(self, __a0: java.util.function.Function, __a1: java.util.concurrent.Executor) -> java.util.concurrent.CompletionStage: ...

    def exceptionallyCompose(self, __a0: java.util.function.Function) -> java.util.concurrent.CompletionStage: ...

    @overload
    def exceptionallyComposeAsync(self, __a0: java.util.function.Function) -> java.util.concurrent.CompletionStage: ...

    @overload
    def exceptionallyComposeAsync(self, __a0: java.util.function.Function, __a1: java.util.concurrent.Executor) -> java.util.concurrent.CompletionStage: ...

    @overload
    def get(self) -> object: ...

    @overload
    def get(self, __a0: long, __a1: java.util.concurrent.TimeUnit) -> object: ...

    def getClass(self) -> java.lang.Class: ...

    def handle(self, __a0: java.util.function.BiFunction) -> java.util.concurrent.CompletionStage: ...

    @overload
    def handleAsync(self, __a0: java.util.function.BiFunction) -> java.util.concurrent.CompletionStage: ...

    @overload
    def handleAsync(self, __a0: java.util.function.BiFunction, __a1: java.util.concurrent.Executor) -> java.util.concurrent.CompletionStage: ...

    def hashCode(self) -> int: ...

    def isCancelled(self) -> bool: ...

    def isDone(self) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def resultNow(self) -> object: ...

    def runAfterBoth(self, __a0: java.util.concurrent.CompletionStage, __a1: java.lang.Runnable) -> java.util.concurrent.CompletionStage: ...

    @overload
    def runAfterBothAsync(self, __a0: java.util.concurrent.CompletionStage, __a1: java.lang.Runnable) -> java.util.concurrent.CompletionStage: ...

    @overload
    def runAfterBothAsync(self, __a0: java.util.concurrent.CompletionStage, __a1: java.lang.Runnable, __a2: java.util.concurrent.Executor) -> java.util.concurrent.CompletionStage: ...

    def runAfterEither(self, __a0: java.util.concurrent.CompletionStage, __a1: java.lang.Runnable) -> java.util.concurrent.CompletionStage: ...

    @overload
    def runAfterEitherAsync(self, __a0: java.util.concurrent.CompletionStage, __a1: java.lang.Runnable) -> java.util.concurrent.CompletionStage: ...

    @overload
    def runAfterEitherAsync(self, __a0: java.util.concurrent.CompletionStage, __a1: java.lang.Runnable, __a2: java.util.concurrent.Executor) -> java.util.concurrent.CompletionStage: ...

    def state(self) -> java.util.concurrent.Future.State: ...

    def thenAccept(self, __a0: java.util.function.Consumer) -> java.util.concurrent.CompletionStage: ...

    @overload
    def thenAcceptAsync(self, __a0: java.util.function.Consumer) -> java.util.concurrent.CompletionStage: ...

    @overload
    def thenAcceptAsync(self, __a0: java.util.function.Consumer, __a1: java.util.concurrent.Executor) -> java.util.concurrent.CompletionStage: ...

    def thenAcceptBoth(self, __a0: java.util.concurrent.CompletionStage, __a1: java.util.function.BiConsumer) -> java.util.concurrent.CompletionStage: ...

    @overload
    def thenAcceptBothAsync(self, __a0: java.util.concurrent.CompletionStage, __a1: java.util.function.BiConsumer) -> java.util.concurrent.CompletionStage: ...

    @overload
    def thenAcceptBothAsync(self, __a0: java.util.concurrent.CompletionStage, __a1: java.util.function.BiConsumer, __a2: java.util.concurrent.Executor) -> java.util.concurrent.CompletionStage: ...

    def thenApply(self, __a0: java.util.function.Function) -> java.util.concurrent.CompletionStage: ...

    @overload
    def thenApplyAsync(self, __a0: java.util.function.Function) -> java.util.concurrent.CompletionStage: ...

    @overload
    def thenApplyAsync(self, __a0: java.util.function.Function, __a1: java.util.concurrent.Executor) -> java.util.concurrent.CompletionStage: ...

    def thenCombine(self, __a0: java.util.concurrent.CompletionStage, __a1: java.util.function.BiFunction) -> java.util.concurrent.CompletionStage: ...

    @overload
    def thenCombineAsync(self, __a0: java.util.concurrent.CompletionStage, __a1: java.util.function.BiFunction) -> java.util.concurrent.CompletionStage: ...

    @overload
    def thenCombineAsync(self, __a0: java.util.concurrent.CompletionStage, __a1: java.util.function.BiFunction, __a2: java.util.concurrent.Executor) -> java.util.concurrent.CompletionStage: ...

    def thenCompose(self, __a0: java.util.function.Function) -> java.util.concurrent.CompletionStage: ...

    @overload
    def thenComposeAsync(self, __a0: java.util.function.Function) -> java.util.concurrent.CompletionStage: ...

    @overload
    def thenComposeAsync(self, __a0: java.util.function.Function, __a1: java.util.concurrent.Executor) -> java.util.concurrent.CompletionStage: ...

    def thenRun(self, __a0: java.lang.Runnable) -> java.util.concurrent.CompletionStage: ...

    @overload
    def thenRunAsync(self, __a0: java.lang.Runnable) -> java.util.concurrent.CompletionStage: ...

    @overload
    def thenRunAsync(self, __a0: java.lang.Runnable, __a1: java.util.concurrent.Executor) -> java.util.concurrent.CompletionStage: ...

    def toCompletableFuture(self) -> java.util.concurrent.CompletableFuture: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    def whenComplete(self, __a0: java.util.function.BiConsumer) -> java.util.concurrent.CompletionStage: ...

    @overload
    def whenCompleteAsync(self, __a0: java.util.function.BiConsumer) -> java.util.concurrent.CompletionStage: ...

    @overload
    def whenCompleteAsync(self, __a0: java.util.function.BiConsumer, __a1: java.util.concurrent.Executor) -> java.util.concurrent.CompletionStage: ...

    @property
    def cancelled(self) -> bool: ...

    @property
    def done(self) -> bool: ...