from typing import overload
import ghidra.dbg.target
import ghidra.trace.model.memory
import java.lang


class ManagedMemoryRecorder(object):








    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getTraceMemoryRegion(self, __a0: ghidra.dbg.target.TargetMemoryRegion) -> ghidra.trace.model.memory.TraceMemoryRegion: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def offerProcessMemory(self, __a0: ghidra.dbg.target.TargetMemory) -> None: ...

    def offerProcessRegion(self, __a0: ghidra.dbg.target.TargetMemoryRegion) -> None: ...

    def removeProcessMemory(self, __a0: ghidra.dbg.target.TargetMemory) -> None: ...

    def removeProcessRegion(self, __a0: ghidra.dbg.target.TargetMemoryRegion) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

