from typing import overload
import ghidra.dbg.target
import ghidra.trace.model.modules
import java.lang


class ManagedModuleRecorder(object):








    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getTraceModule(self, __a0: ghidra.dbg.target.TargetModule) -> ghidra.trace.model.modules.TraceModule: ...

    def getTraceSection(self, __a0: ghidra.dbg.target.TargetSection) -> ghidra.trace.model.modules.TraceSection: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def offerProcessModule(self, __a0: ghidra.dbg.target.TargetModule) -> None: ...

    def offerProcessModuleSection(self, __a0: ghidra.dbg.target.TargetSection) -> None: ...

    def removeProcessModule(self, __a0: ghidra.dbg.target.TargetModule) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

