from typing import List
from typing import overload
import ghidra.app.plugin.assembler.sleigh.sem
import java.lang


class WildAssemblyNopState(ghidra.app.plugin.assembler.sleigh.sem.AssemblyNopState):




    def __init__(self, __a0: ghidra.app.plugin.assembler.sleigh.sem.AbstractAssemblyTreeResolver, __a1: List[object], __a2: int, __a3: ghidra.app.plugin.processors.sleigh.symbol.OperandSymbol, __a4: unicode): ...



    def computeHash(self) -> int: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getLength(self) -> int: ...

    def getPath(self) -> List[object]: ...

    def getResolver(self) -> ghidra.app.plugin.assembler.sleigh.sem.AbstractAssemblyTreeResolver: ...

    def getShift(self) -> int: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

