from typing import overload
import ghidra.trace.model.property
import java.lang
import java.util


class TraceAddressPropertyManager(object):








    def createPropertyMap(self, __a0: unicode, __a1: java.lang.Class) -> ghidra.trace.model.property.TracePropertyMap: ...

    def equals(self, __a0: object) -> bool: ...

    def getAllProperties(self) -> java.util.Map: ...

    def getClass(self) -> java.lang.Class: ...

    def getOrCreatePropertyMap(self, __a0: unicode, __a1: java.lang.Class) -> ghidra.trace.model.property.TracePropertyMap: ...

    def getOrCreatePropertyMapSuper(self, __a0: unicode, __a1: java.lang.Class) -> ghidra.trace.model.property.TracePropertyMap: ...

    @overload
    def getPropertyMap(self, __a0: unicode) -> ghidra.trace.model.property.TracePropertyMap: ...

    @overload
    def getPropertyMap(self, __a0: unicode, __a1: java.lang.Class) -> ghidra.trace.model.property.TracePropertyMap: ...

    def getPropertyMapExtends(self, __a0: unicode, __a1: java.lang.Class) -> ghidra.trace.model.property.TracePropertyMap: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def allProperties(self) -> java.util.Map: ...