from typing import overload
import ghidra.app.plugin.assembler.sleigh.symbol
import java.lang


class WildAssemblyNonTerminal(ghidra.app.plugin.assembler.sleigh.symbol.AssemblyNonTerminal):




    def __init__(self, __a0: unicode, __a1: bool): ...



    @overload
    def compareTo(self, __a0: ghidra.app.plugin.assembler.sleigh.symbol.AssemblySymbol) -> int: ...

    @overload
    def compareTo(self, __a0: object) -> int: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getName(self) -> unicode: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def takesOperandIndex(self) -> bool: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

