from typing import overload
import db
import ghidra.util.database
import java.lang


class AbstractDirectedLongKeyIterator(object, ghidra.util.database.DirectedLongKeyIterator):




    def __init__(self, __a0: db.DBLongIterator): ...



    def delete(self) -> bool: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    @staticmethod
    def getIterator(__a0: db.Table, __a1: ghidra.util.database.KeySpan, __a2: ghidra.util.database.DirectedIterator.Direction) -> ghidra.util.database.AbstractDirectedLongKeyIterator: ...

    def hasNext(self) -> bool: ...

    def hashCode(self) -> int: ...

    def next(self) -> object: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

