from typing import overload
import ghidra.app.util.importer
import ghidra.file.formats.android.fbpk
import ghidra.program.model.address
import ghidra.program.model.data
import ghidra.program.model.listing
import ghidra.util.task
import java.lang


class FBPKv1_Partition(ghidra.file.formats.android.fbpk.FBPK_Partition):




    def __init__(self, __a0: ghidra.app.util.bin.BinaryReader): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getDataSize(self) -> int: ...

    def getDataStartOffset(self) -> long: ...

    def getFBPT(self) -> ghidra.file.formats.android.fbpk.FBPT: ...

    def getHeaderSize(self) -> int: ...

    def getName(self) -> unicode: ...

    def getOffsetToNextPartitionTable(self) -> int: ...

    def getPartitionIndex(self) -> int: ...

    def getType(self) -> int: ...

    def getUnknown1(self) -> int: ...

    def getUnknown2(self) -> int: ...

    def hashCode(self) -> int: ...

    def isDirectory(self) -> bool: ...

    def isFile(self) -> bool: ...

    def markup(self, __a0: ghidra.program.model.listing.Program, __a1: ghidra.program.model.address.Address, __a2: ghidra.util.task.TaskMonitor, __a3: ghidra.app.util.importer.MessageLog) -> None: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toDataType(self) -> ghidra.program.model.data.DataType: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def FBPT(self) -> ghidra.file.formats.android.fbpk.FBPT: ...

    @property
    def dataSize(self) -> int: ...

    @property
    def dataStartOffset(self) -> long: ...

    @property
    def directory(self) -> bool: ...

    @property
    def file(self) -> bool: ...

    @property
    def offsetToNextPartitionTable(self) -> int: ...

    @property
    def unknown1(self) -> int: ...

    @property
    def unknown2(self) -> int: ...