from typing import List
from typing import overload
import ghidra.app.util.bin
import ghidra.file.formats.android.oat
import ghidra.file.formats.android.oat.bundle
import ghidra.file.formats.android.oat.headers
import ghidra.program.model.data
import java.lang


class OatHeader_199(ghidra.file.formats.android.oat.headers.OatHeader_195):




    def __init__(self, __a0: ghidra.app.util.bin.BinaryReader): ...



    def equals(self, __a0: object) -> bool: ...

    def getChecksum(self) -> int: ...

    def getClass(self) -> java.lang.Class: ...

    def getDexFileCount(self) -> int: ...

    def getExecutableOffset(self) -> int: ...

    def getInstructionSet(self) -> ghidra.file.formats.android.oat.OatInstructionSet: ...

    def getKeyValueStoreSize(self) -> int: ...

    def getMagic(self) -> unicode: ...

    def getOatDexFileList(self) -> List[object]: ...

    def getOatDexFilesOffset(self, __a0: ghidra.app.util.bin.BinaryReader) -> int: ...

    def getVersion(self) -> unicode: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def parse(self, __a0: ghidra.app.util.bin.BinaryReader, __a1: ghidra.file.formats.android.oat.bundle.OatBundle) -> None: ...

    def toDataType(self) -> ghidra.program.model.data.DataType: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

