
# This file was generated by 'versioneer.py' (0.28) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-07-11T17:05:29+0300",
 "dirty": false,
 "error": null,
 "full-revisionid": "4130a41f438fe12ab8a5217dd1826510ee48e54b",
 "version": "1.9.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
