from typing import overload
import ghidra.app.plugin.core.analysis.rust.demangler
import ghidra.app.util.demangler
import java.lang


class RustDemanglerOptions(ghidra.app.util.demangler.DemanglerOptions):




    @overload
    def __init__(self): ...

    @overload
    def __init__(self, __a0: ghidra.app.plugin.core.analysis.rust.demangler.RustDemanglerFormat): ...

    @overload
    def __init__(self, __a0: ghidra.app.util.demangler.DemanglerOptions): ...

    @overload
    def __init__(self, __a0: ghidra.app.plugin.core.analysis.rust.demangler.RustDemanglerFormat, __a1: bool): ...



    def applyCallingConvention(self) -> bool: ...

    def applySignature(self) -> bool: ...

    def demangleOnlyKnownPatterns(self) -> bool: ...

    def doDisassembly(self) -> bool: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getDemanglerFormat(self) -> ghidra.app.plugin.core.analysis.rust.demangler.RustDemanglerFormat: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def setApplyCallingConvention(self, __a0: bool) -> None: ...

    def setApplySignature(self, __a0: bool) -> None: ...

    def setDemangleOnlyKnownPatterns(self, __a0: bool) -> None: ...

    def setDoDisassembly(self, __a0: bool) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def demanglerFormat(self) -> ghidra.app.plugin.core.analysis.rust.demangler.RustDemanglerFormat: ...