# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resemble/v1alpha1/admin/exim.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\"resemble/v1alpha1/admin/exim.proto\x12\x17resemble.v1alpha1.admin\"\x18\n\x16ListConsensusesRequest\"0\n\x17ListConsensusesResponse\x12\x15\n\rconsensus_ids\x18\x01 \x03(\t\"/\n\x07\x41\x63torId\x12\x12\n\nstate_type\x18\x01 \x01(\t\x12\x10\n\x08\x61\x63tor_id\x18\x02 \x01(\t\"%\n\rExportRequest\x12\x14\n\x0c\x63onsensus_id\x18\x01 \x01(\t\"X\n\x0e\x45xportResponse\x12\x32\n\x08\x61\x63tor_id\x18\x01 \x01(\x0b\x32 .resemble.v1alpha1.admin.ActorId\x12\x12\n\nstate_json\x18\x02 \x01(\x0c\"W\n\rImportRequest\x12\x32\n\x08\x61\x63tor_id\x18\x01 \x01(\x0b\x32 .resemble.v1alpha1.admin.ActorId\x12\x12\n\nstate_json\x18\x02 \x01(\x0c\"\x10\n\x0eImportResponse2\xb6\x02\n\x04\x45xim\x12t\n\x0fListConsensuses\x12/.resemble.v1alpha1.admin.ListConsensusesRequest\x1a\x30.resemble.v1alpha1.admin.ListConsensusesResponse\x12[\n\x06\x45xport\x12&.resemble.v1alpha1.admin.ExportRequest\x1a\'.resemble.v1alpha1.admin.ExportResponse0\x01\x12[\n\x06Import\x12&.resemble.v1alpha1.admin.ImportRequest\x1a\'.resemble.v1alpha1.admin.ImportResponse(\x01\x62\x06proto3')



_LISTCONSENSUSESREQUEST = DESCRIPTOR.message_types_by_name['ListConsensusesRequest']
_LISTCONSENSUSESRESPONSE = DESCRIPTOR.message_types_by_name['ListConsensusesResponse']
_ACTORID = DESCRIPTOR.message_types_by_name['ActorId']
_EXPORTREQUEST = DESCRIPTOR.message_types_by_name['ExportRequest']
_EXPORTRESPONSE = DESCRIPTOR.message_types_by_name['ExportResponse']
_IMPORTREQUEST = DESCRIPTOR.message_types_by_name['ImportRequest']
_IMPORTRESPONSE = DESCRIPTOR.message_types_by_name['ImportResponse']
ListConsensusesRequest = _reflection.GeneratedProtocolMessageType('ListConsensusesRequest', (_message.Message,), {
  'DESCRIPTOR' : _LISTCONSENSUSESREQUEST,
  '__module__' : 'resemble.v1alpha1.admin.exim_pb2'
  # @@protoc_insertion_point(class_scope:resemble.v1alpha1.admin.ListConsensusesRequest)
  })
_sym_db.RegisterMessage(ListConsensusesRequest)

ListConsensusesResponse = _reflection.GeneratedProtocolMessageType('ListConsensusesResponse', (_message.Message,), {
  'DESCRIPTOR' : _LISTCONSENSUSESRESPONSE,
  '__module__' : 'resemble.v1alpha1.admin.exim_pb2'
  # @@protoc_insertion_point(class_scope:resemble.v1alpha1.admin.ListConsensusesResponse)
  })
_sym_db.RegisterMessage(ListConsensusesResponse)

ActorId = _reflection.GeneratedProtocolMessageType('ActorId', (_message.Message,), {
  'DESCRIPTOR' : _ACTORID,
  '__module__' : 'resemble.v1alpha1.admin.exim_pb2'
  # @@protoc_insertion_point(class_scope:resemble.v1alpha1.admin.ActorId)
  })
_sym_db.RegisterMessage(ActorId)

ExportRequest = _reflection.GeneratedProtocolMessageType('ExportRequest', (_message.Message,), {
  'DESCRIPTOR' : _EXPORTREQUEST,
  '__module__' : 'resemble.v1alpha1.admin.exim_pb2'
  # @@protoc_insertion_point(class_scope:resemble.v1alpha1.admin.ExportRequest)
  })
_sym_db.RegisterMessage(ExportRequest)

ExportResponse = _reflection.GeneratedProtocolMessageType('ExportResponse', (_message.Message,), {
  'DESCRIPTOR' : _EXPORTRESPONSE,
  '__module__' : 'resemble.v1alpha1.admin.exim_pb2'
  # @@protoc_insertion_point(class_scope:resemble.v1alpha1.admin.ExportResponse)
  })
_sym_db.RegisterMessage(ExportResponse)

ImportRequest = _reflection.GeneratedProtocolMessageType('ImportRequest', (_message.Message,), {
  'DESCRIPTOR' : _IMPORTREQUEST,
  '__module__' : 'resemble.v1alpha1.admin.exim_pb2'
  # @@protoc_insertion_point(class_scope:resemble.v1alpha1.admin.ImportRequest)
  })
_sym_db.RegisterMessage(ImportRequest)

ImportResponse = _reflection.GeneratedProtocolMessageType('ImportResponse', (_message.Message,), {
  'DESCRIPTOR' : _IMPORTRESPONSE,
  '__module__' : 'resemble.v1alpha1.admin.exim_pb2'
  # @@protoc_insertion_point(class_scope:resemble.v1alpha1.admin.ImportResponse)
  })
_sym_db.RegisterMessage(ImportResponse)

_EXIM = DESCRIPTOR.services_by_name['Exim']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _LISTCONSENSUSESREQUEST._serialized_start=63
  _LISTCONSENSUSESREQUEST._serialized_end=87
  _LISTCONSENSUSESRESPONSE._serialized_start=89
  _LISTCONSENSUSESRESPONSE._serialized_end=137
  _ACTORID._serialized_start=139
  _ACTORID._serialized_end=186
  _EXPORTREQUEST._serialized_start=188
  _EXPORTREQUEST._serialized_end=225
  _EXPORTRESPONSE._serialized_start=227
  _EXPORTRESPONSE._serialized_end=315
  _IMPORTREQUEST._serialized_start=317
  _IMPORTREQUEST._serialized_end=404
  _IMPORTRESPONSE._serialized_start=406
  _IMPORTRESPONSE._serialized_end=422
  _EXIM._serialized_start=425
  _EXIM._serialized_end=735
# @@protoc_insertion_point(module_scope)
