from typing import List
from typing import overload
import ghidra.app.util
import ghidra.app.util.exporter
import ghidra.app.util.importer
import ghidra.framework.model
import ghidra.framework.plugintool
import ghidra.program.model.address
import ghidra.util
import ghidra.util.task
import java.io
import java.lang


class TraceViewXmlExporter(ghidra.app.util.exporter.XmlExporter):




    def __init__(self): ...



    def canExportDomainFile(self, __a0: ghidra.framework.model.DomainFile) -> bool: ...

    @overload
    def canExportDomainObject(self, __a0: ghidra.framework.model.DomainObject) -> bool: ...

    @overload
    def canExportDomainObject(self, __a0: java.lang.Class) -> bool: ...

    def equals(self, __a0: object) -> bool: ...

    @overload
    def export(self, __a0: java.io.File, __a1: ghidra.framework.model.DomainFile, __a2: ghidra.util.task.TaskMonitor) -> bool: ...

    @overload
    def export(self, __a0: java.io.File, __a1: ghidra.framework.model.DomainObject, __a2: ghidra.program.model.address.AddressSetView, __a3: ghidra.util.task.TaskMonitor) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getDefaultFileExtension(self) -> unicode: ...

    def getHelpLocation(self) -> ghidra.util.HelpLocation: ...

    def getMessageLog(self) -> ghidra.app.util.importer.MessageLog: ...

    def getName(self) -> unicode: ...

    def getOptions(self, __a0: ghidra.app.util.DomainObjectService) -> List[object]: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def setExporterServiceProvider(self, __a0: ghidra.framework.plugintool.ServiceProvider) -> None: ...

    def setOptions(self, __a0: List[object]) -> None: ...

    def supportsAddressRestrictedExport(self) -> bool: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def options(self) -> None: ...  # No getter available.

    @options.setter
    def options(self, value: List[object]) -> None: ...