from typing import List
from typing import overload
import ghidra.file.formats.android.oat.tlt
import ghidra.program.model.data
import java.lang


class TypeLookupTable_R(ghidra.file.formats.android.oat.tlt.TypeLookupTable_Q):




    def __init__(self, __a0: ghidra.app.util.bin.BinaryReader): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getDexFileBegin(self) -> int: ...

    def getEntries(self) -> int: ...

    def getEntryList(self) -> List[object]: ...

    def getMaskBits(self) -> int: ...

    def hashCode(self) -> int: ...

    def isOwnsEntries(self) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toDataType(self) -> ghidra.program.model.data.DataType: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

