# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: resemble/v1alpha1/inspect/inspect.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.api import annotations_pb2 as google_dot_api_dot_annotations__pb2
from google.api import httpbody_pb2 as google_dot_api_dot_httpbody__pb2
from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\'resemble/v1alpha1/inspect/inspect.proto\x12\x19resemble.v1alpha1.inspect\x1a\x1cgoogle/api/annotations.proto\x1a\x19google/api/httpbody.proto\x1a\x1cgoogle/protobuf/struct.proto\"0\n\x13GetAllActorsRequest\x12\x19\n\x11only_consensus_id\x18\x01 \x01(\t\"?\n\x14GetAllActorsResponse\x12\'\n\x06\x61\x63tors\x18\x01 \x01(\x0b\x32\x17.google.protobuf.Struct\"#\n\x13WebDashboardRequest\x12\x0c\n\x04\x66ile\x18\x01 \x01(\t2\x82\x02\n\x07Inspect\x12s\n\x0cGetAllActors\x12..resemble.v1alpha1.inspect.GetAllActorsRequest\x1a/.resemble.v1alpha1.inspect.GetAllActorsResponse\"\x00\x30\x01\x12\x81\x01\n\x0cWebDashboard\x12..resemble.v1alpha1.inspect.WebDashboardRequest\x1a\x14.google.api.HttpBody\"+\x82\xd3\xe4\x93\x02%\x12\x0b/__/inspectZ\x16\x12\x14/__/inspect/{file=*}b\x06proto3')



_GETALLACTORSREQUEST = DESCRIPTOR.message_types_by_name['GetAllActorsRequest']
_GETALLACTORSRESPONSE = DESCRIPTOR.message_types_by_name['GetAllActorsResponse']
_WEBDASHBOARDREQUEST = DESCRIPTOR.message_types_by_name['WebDashboardRequest']
GetAllActorsRequest = _reflection.GeneratedProtocolMessageType('GetAllActorsRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETALLACTORSREQUEST,
  '__module__' : 'resemble.v1alpha1.inspect.inspect_pb2'
  # @@protoc_insertion_point(class_scope:resemble.v1alpha1.inspect.GetAllActorsRequest)
  })
_sym_db.RegisterMessage(GetAllActorsRequest)

GetAllActorsResponse = _reflection.GeneratedProtocolMessageType('GetAllActorsResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETALLACTORSRESPONSE,
  '__module__' : 'resemble.v1alpha1.inspect.inspect_pb2'
  # @@protoc_insertion_point(class_scope:resemble.v1alpha1.inspect.GetAllActorsResponse)
  })
_sym_db.RegisterMessage(GetAllActorsResponse)

WebDashboardRequest = _reflection.GeneratedProtocolMessageType('WebDashboardRequest', (_message.Message,), {
  'DESCRIPTOR' : _WEBDASHBOARDREQUEST,
  '__module__' : 'resemble.v1alpha1.inspect.inspect_pb2'
  # @@protoc_insertion_point(class_scope:resemble.v1alpha1.inspect.WebDashboardRequest)
  })
_sym_db.RegisterMessage(WebDashboardRequest)

_INSPECT = DESCRIPTOR.services_by_name['Inspect']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _INSPECT.methods_by_name['WebDashboard']._options = None
  _INSPECT.methods_by_name['WebDashboard']._serialized_options = b'\202\323\344\223\002%\022\013/__/inspectZ\026\022\024/__/inspect/{file=*}'
  _GETALLACTORSREQUEST._serialized_start=157
  _GETALLACTORSREQUEST._serialized_end=205
  _GETALLACTORSRESPONSE._serialized_start=207
  _GETALLACTORSRESPONSE._serialized_end=270
  _WEBDASHBOARDREQUEST._serialized_start=272
  _WEBDASHBOARDREQUEST._serialized_end=307
  _INSPECT._serialized_start=310
  _INSPECT._serialized_end=568
# @@protoc_insertion_point(module_scope)
