
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-07-15T15:07:17+0000",
 "dirty": true,
 "error": null,
 "full-revisionid": "7a4fe2ad467dbe4059b774763e6263a59ad72324",
 "version": "0.1.3"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
