from typing import overload
import ghidra.features.bsim.gui.search.dialog
import ghidra.features.bsim.query
import java.lang
import java.util


class BSimServerManager(object):




    def __init__(self): ...



    def addListener(self, __a0: ghidra.features.bsim.gui.search.dialog.BSimServerManagerListener) -> None: ...

    def addServer(self, __a0: ghidra.features.bsim.query.BSimServerInfo) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    @staticmethod
    def getActiveConnections(__a0: ghidra.features.bsim.query.BSimServerInfo) -> int: ...

    def getClass(self) -> java.lang.Class: ...

    def getServerInfos(self) -> java.util.Set: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def removeListener(self, __a0: ghidra.features.bsim.gui.search.dialog.BSimServerManagerListener) -> None: ...

    def removeServer(self, __a0: ghidra.features.bsim.query.BSimServerInfo, __a1: bool) -> bool: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def serverInfos(self) -> java.util.Set: ...