from typing import overload
import ghidra.features.bsim.gui.search.dialog
import java.lang


class BSimSearchSettings(object):




    @overload
    def __init__(self): ...

    @overload
    def __init__(self, __a0: float, __a1: float, __a2: int, __a3: ghidra.features.bsim.gui.search.dialog.BSimFilterSet): ...



    def copy(self) -> ghidra.features.bsim.gui.search.dialog.BSimSearchSettings: ...

    def equals(self, __a0: object) -> bool: ...

    def getBSimFilterSet(self) -> ghidra.features.bsim.gui.search.dialog.BSimFilterSet: ...

    def getClass(self) -> java.lang.Class: ...

    def getConfidence(self) -> float: ...

    def getMaxResults(self) -> int: ...

    def getSimilarity(self) -> float: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def BSimFilterSet(self) -> ghidra.features.bsim.gui.search.dialog.BSimFilterSet: ...

    @property
    def confidence(self) -> float: ...

    @property
    def maxResults(self) -> int: ...

    @property
    def similarity(self) -> float: ...