from typing import overload
import ghidra.app.util.bin.format.pdb2.pdbreader
import ghidra.app.util.pdb.pdbapplicator
import ghidra.program.model.address
import java.lang


class FunctionSymbolApplier(ghidra.app.util.pdb.pdbapplicator.AbstractBlockContextApplier, ghidra.app.util.pdb.pdbapplicator.BlockNestingSymbolApplier, ghidra.app.util.pdb.pdbapplicator.DisassembleableAddressSymbolApplier):




    def __init__(self, __a0: ghidra.app.util.pdb.pdbapplicator.DefaultPdbApplicator, __a1: ghidra.app.util.bin.format.pdb2.pdbreader.symbol.AbstractProcedureMsSymbol): ...



    def apply(self, __a0: ghidra.app.util.bin.format.pdb2.pdbreader.MsSymbolIterator) -> None: ...

    def beginBlock(self, __a0: ghidra.program.model.address.Address, __a1: unicode, __a2: long) -> None: ...

    def deferredApply(self, __a0: ghidra.app.util.bin.format.pdb2.pdbreader.MsSymbolIterator) -> None: ...

    def endBlock(self) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getAddressForDisassembly(self) -> ghidra.program.model.address.Address: ...

    def getClass(self) -> java.lang.Class: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def addressForDisassembly(self) -> ghidra.program.model.address.Address: ...