from typing import overload
import ghidra.features.bsim.query.protocol
import java.lang


class NullStaging(ghidra.features.bsim.query.protocol.StagingManager):




    def __init__(self): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getQueriesMade(self) -> int: ...

    def getQuery(self) -> ghidra.features.bsim.query.protocol.BSimQuery: ...

    def getTotalSize(self) -> int: ...

    def hashCode(self) -> int: ...

    def initialize(self, __a0: ghidra.features.bsim.query.protocol.BSimQuery) -> bool: ...

    def nextStage(self) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def query(self) -> ghidra.features.bsim.query.protocol.BSimQuery: ...