from typing import overload
import java.lang
import java.util.function


class PreFilter(object):




    def __init__(self): ...



    def addPredicate(self, __a0: java.util.function.BiPredicate) -> None: ...

    def clearFilters(self) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getAndReducedPredicate(self) -> java.util.function.BiPredicate: ...

    def getClass(self) -> java.lang.Class: ...

    def getOrReducedPredicate(self) -> java.util.function.BiPredicate: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def andReducedPredicate(self) -> java.util.function.BiPredicate: ...

    @property
    def orReducedPredicate(self) -> java.util.function.BiPredicate: ...