from typing import overload
import java.lang


class DatabaseInfo(object):




    def __init__(self, __a0: unicode, __a1: ghidra.features.bsim.query.description.DatabaseInformation): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getDescription(self) -> unicode: ...

    def getName(self) -> unicode: ...

    def getOwner(self) -> unicode: ...

    def getServerURL(self) -> unicode: ...

    def getVersion(self) -> unicode: ...

    def hashCode(self) -> int: ...

    def isReadOnly(self) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def description(self) -> unicode: ...

    @property
    def name(self) -> unicode: ...

    @property
    def owner(self) -> unicode: ...

    @property
    def readOnly(self) -> bool: ...

    @property
    def serverURL(self) -> unicode: ...

    @property
    def version(self) -> unicode: ...