from typing import overload
import java.lang


class CtrlVertex(object):




    def __init__(self, __a0: ghidra.program.model.pcode.PcodeBlockBasic, __a1: int, __a2: ghidra.codecompare.graphanalysis.CtrlGraph): ...



    def clearNGrams(self) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def setZeroGram(self, __a0: int) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def zeroGram(self) -> None: ...  # No getter available.

    @zeroGram.setter
    def zeroGram(self, value: int) -> None: ...