from typing import overload
import java.lang


class CtrlGraph(object):




    def __init__(self, __a0: ghidra.codecompare.graphanalysis.Pinning.Side, __a1: ghidra.program.model.pcode.HighFunction): ...



    def addEdgeColor(self) -> None: ...

    def clearNGrams(self) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def hashCode(self) -> int: ...

    def makeNGrams(self, __a0: int) -> None: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

