from typing import List
from typing import overload
import ghidra.util.database.spatial
import java.lang
import java.util


class Query(object):





    class QueryInclusion(java.lang.Enum):
        ALL: ghidra.util.database.spatial.Query.QueryInclusion
        NONE: ghidra.util.database.spatial.Query.QueryInclusion
        SOME: ghidra.util.database.spatial.Query.QueryInclusion







        @overload
        def compareTo(self, __a0: java.lang.Enum) -> int: ...

        @overload
        def compareTo(self, __a0: object) -> int: ...

        def describeConstable(self) -> java.util.Optional: ...

        def equals(self, __a0: object) -> bool: ...

        def getClass(self) -> java.lang.Class: ...

        def getDeclaringClass(self) -> java.lang.Class: ...

        def hashCode(self) -> int: ...

        def name(self) -> unicode: ...

        def notify(self) -> None: ...

        def notifyAll(self) -> None: ...

        def ordinal(self) -> int: ...

        def toString(self) -> unicode: ...

        @overload
        @staticmethod
        def valueOf(__a0: unicode) -> ghidra.util.database.spatial.Query.QueryInclusion: ...

        @overload
        @staticmethod
        def valueOf(__a0: java.lang.Class, __a1: unicode) -> java.lang.Enum: ...

        @staticmethod
        def values() -> List[ghidra.util.database.spatial.Query.QueryInclusion]: ...

        @overload
        def wait(self) -> None: ...

        @overload
        def wait(self, __a0: long) -> None: ...

        @overload
        def wait(self, __a0: long, __a1: int) -> None: ...







    def equals(self, __a0: object) -> bool: ...

    def getBoundsComparator(self) -> java.util.Comparator: ...

    def getClass(self) -> java.lang.Class: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def terminateEarlyData(self, __a0: object) -> bool: ...

    def terminateEarlyNode(self, __a0: object) -> bool: ...

    def testData(self, __a0: object) -> bool: ...

    def testNode(self, __a0: object) -> ghidra.util.database.spatial.Query.QueryInclusion: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def boundsComparator(self) -> java.util.Comparator: ...