from typing import overload
import java.lang


class JdiVMThreadGroup(object):




    def __init__(self, __a0: int, __a1: unicode, __a2: long, __a3: long, __a4: unicode): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getExecutable(self) -> unicode: ...

    def getExitCode(self) -> long: ...

    def getInferiorId(self) -> int: ...

    def getPid(self) -> long: ...

    def getType(self) -> unicode: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def executable(self) -> unicode: ...

    @property
    def exitCode(self) -> long: ...

    @property
    def inferiorId(self) -> int: ...

    @property
    def pid(self) -> long: ...

    @property
    def type(self) -> unicode: ...