from typing import overload
import ghidra.program.database
import ghidra.util
import java.lang


class StringRecord(ghidra.program.database.DatabaseObject):




    def __init__(self, __a0: ghidra.program.database.DBObjectCache, __a1: long, __a2: unicode): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getKey(self) -> long: ...

    def getValue(self) -> unicode: ...

    def hashCode(self) -> int: ...

    def isDeleted(self, __a0: ghidra.util.Lock) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def setInvalid(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def value(self) -> unicode: ...