from typing import overload
import ghidra.debug.api.model
import ghidra.program.model.lang
import java.lang
import java.util


class DefaultDebuggerMappingOffer(object, ghidra.debug.api.model.DebuggerMappingOffer):




    def __init__(self, __a0: ghidra.dbg.target.TargetObject, __a1: int, __a2: unicode, __a3: ghidra.program.model.lang.LanguageID, __a4: ghidra.program.model.lang.CompilerSpecID, __a5: java.util.Collection): ...



    def equals(self, __a0: object) -> bool: ...

    @staticmethod
    def first(__a0: java.util.Collection) -> ghidra.debug.api.model.DebuggerTargetTraceMapper: ...

    def getClass(self) -> java.lang.Class: ...

    def getConfidence(self) -> int: ...

    def getDescription(self) -> unicode: ...

    def getTraceCompilerSpecID(self) -> ghidra.program.model.lang.CompilerSpecID: ...

    def getTraceLanguageID(self) -> ghidra.program.model.lang.LanguageID: ...

    def hashCode(self) -> int: ...

    def isOverride(self) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def take(self) -> ghidra.debug.api.model.DebuggerTargetTraceMapper: ...

    def toString(self) -> unicode: ...

    @staticmethod
    def unique(__a0: java.util.Collection) -> ghidra.debug.api.model.DebuggerMappingOffer: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def confidence(self) -> int: ...

    @property
    def description(self) -> unicode: ...

    @property
    def override(self) -> bool: ...

    @property
    def traceCompilerSpecID(self) -> ghidra.program.model.lang.CompilerSpecID: ...

    @property
    def traceLanguageID(self) -> ghidra.program.model.lang.LanguageID: ...