from typing import List
from typing import overload
import ghidra.app.plugin.core.debug.gui.tracermi.launcher
import ghidra.debug.api.tracermi
import ghidra.util
import ghidra.util.task
import java.lang
import java.util
import javax.swing


class AbstractScriptTraceRmiLaunchOffer(ghidra.app.plugin.core.debug.gui.tracermi.launcher.AbstractTraceRmiLaunchOffer):




    def __init__(self, __a0: ghidra.app.plugin.core.debug.gui.tracermi.launcher.TraceRmiLauncherServicePlugin, __a1: ghidra.program.model.listing.Program, __a2: java.io.File, __a3: unicode, __a4: ghidra.app.plugin.core.debug.gui.tracermi.launcher.ScriptAttributesParser.ScriptAttributes): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getConfigName(self) -> unicode: ...

    def getDescription(self) -> unicode: ...

    def getHelpLocation(self) -> ghidra.util.HelpLocation: ...

    def getIcon(self) -> javax.swing.Icon: ...

    @overload
    def getLauncherArgs(self, __a0: bool) -> java.util.Map: ...

    @overload
    def getLauncherArgs(self, __a0: bool, __a1: ghidra.debug.api.tracermi.TraceRmiLaunchOffer.LaunchConfigurator, __a2: java.lang.Throwable) -> java.util.Map: ...

    def getMenuGroup(self) -> unicode: ...

    def getMenuOrder(self) -> unicode: ...

    def getMenuPath(self) -> List[object]: ...

    def getParameters(self) -> java.util.Map: ...

    def getTitle(self) -> unicode: ...

    def hashCode(self) -> int: ...

    @overload
    def launchProgram(self, __a0: ghidra.util.task.TaskMonitor) -> ghidra.debug.api.tracermi.TraceRmiLaunchOffer.LaunchResult: ...

    @overload
    def launchProgram(self, __a0: ghidra.util.task.TaskMonitor, __a1: ghidra.debug.api.tracermi.TraceRmiLaunchOffer.LaunchConfigurator) -> ghidra.debug.api.tracermi.TraceRmiLaunchOffer.LaunchResult: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def requiresImage(self) -> bool: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def configName(self) -> unicode: ...

    @property
    def description(self) -> unicode: ...

    @property
    def helpLocation(self) -> ghidra.util.HelpLocation: ...

    @property
    def icon(self) -> javax.swing.Icon: ...

    @property
    def menuGroup(self) -> unicode: ...

    @property
    def menuOrder(self) -> unicode: ...

    @property
    def menuPath(self) -> List[object]: ...

    @property
    def parameters(self) -> java.util.Map: ...

    @property
    def title(self) -> unicode: ...