from typing import overload
import ghidra.app.plugin.core.debug.service.model
import ghidra.trace.model.thread
import ghidra.trace.model.time
import java.lang


class DefaultTimeRecorder(object):




    def __init__(self, __a0: ghidra.app.plugin.core.debug.service.model.DefaultTraceRecorder): ...



    def createSnapshot(self, __a0: unicode, __a1: ghidra.trace.model.thread.TraceThread, __a2: ghidra.app.plugin.core.debug.service.model.RecorderPermanentTransaction) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def forceSnapshot(self) -> ghidra.trace.model.time.TraceSnapshot: ...

    def getClass(self) -> java.lang.Class: ...

    def getSnap(self) -> long: ...

    def getSnapshot(self) -> ghidra.trace.model.time.TraceSnapshot: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def snap(self) -> long: ...

    @property
    def snapshot(self) -> ghidra.trace.model.time.TraceSnapshot: ...