from typing import List
from typing import overload
import ghidra.app.plugin.core.debug.service.model.interfaces
import ghidra.debug.api.model
import ghidra.program.model.address
import ghidra.trace.model
import java.lang
import java.util.concurrent


class DefaultProcessRecorder(object, ghidra.app.plugin.core.debug.service.model.interfaces.ManagedProcessRecorder):




    def __init__(self, __a0: ghidra.app.plugin.core.debug.service.model.DefaultTraceRecorder): ...



    def equals(self, __a0: object) -> bool: ...

    def getAccessibleProcessMemory(self) -> ghidra.program.model.address.AddressSetView: ...

    def getBreakpointRecorder(self) -> ghidra.app.plugin.core.debug.service.model.interfaces.ManagedBreakpointRecorder: ...

    def getClass(self) -> java.lang.Class: ...

    def getMemoryMapper(self) -> ghidra.debug.api.model.DebuggerMemoryMapper: ...

    def getProcessMemory(self) -> ghidra.app.plugin.core.debug.service.model.interfaces.AbstractRecorderMemory: ...

    def getSnap(self) -> long: ...

    def getTrace(self) -> ghidra.trace.model.Trace: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def readProcessMemory(self, __a0: ghidra.program.model.address.Address, __a1: int) -> java.util.concurrent.CompletableFuture: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    def writeProcessMemory(self, __a0: ghidra.program.model.address.Address, __a1: List[int]) -> java.util.concurrent.CompletableFuture: ...

    @property
    def accessibleProcessMemory(self) -> ghidra.program.model.address.AddressSetView: ...

    @property
    def breakpointRecorder(self) -> ghidra.app.plugin.core.debug.service.model.interfaces.ManagedBreakpointRecorder: ...

    @property
    def memoryMapper(self) -> ghidra.debug.api.model.DebuggerMemoryMapper: ...

    @property
    def processMemory(self) -> ghidra.app.plugin.core.debug.service.model.interfaces.AbstractRecorderMemory: ...

    @property
    def snap(self) -> long: ...

    @property
    def trace(self) -> ghidra.trace.model.Trace: ...