
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-07-12T22:15:54-0700",
 "dirty": false,
 "error": null,
 "full-revisionid": "22684048b4da324a6c5e82916a91072f15e71761",
 "version": "4.4.1"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
