from typing import overload
import ghidra.features.bsim.query.description
import ghidra.xml
import java.io
import java.lang
import java.util


class ClusterNote(object):




    @overload
    def __init__(self): ...

    @overload
    def __init__(self, __a0: ghidra.features.bsim.query.description.FunctionDescription, __a1: int, __a2: float, __a3: float): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getFunctionDescription(self) -> ghidra.features.bsim.query.description.FunctionDescription: ...

    def getMaxSimilarity(self) -> float: ...

    def getSignificance(self) -> float: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def restoreXml(self, __a0: ghidra.xml.XmlPullParser, __a1: ghidra.features.bsim.query.description.DescriptionManager, __a2: java.util.Map) -> None: ...

    def saveXml(self, __a0: java.io.Writer) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def functionDescription(self) -> ghidra.features.bsim.query.description.FunctionDescription: ...

    @property
    def maxSimilarity(self) -> float: ...

    @property
    def significance(self) -> float: ...