from typing import overload
import generic.lsh.vector
import ghidra.features.bsim.query.description
import ghidra.features.bsim.query.protocol
import ghidra.xml
import java.io
import java.lang


class ResponseVectorMatch(ghidra.features.bsim.query.protocol.QueryResponseRecord):
    manage: ghidra.features.bsim.query.description.DescriptionManager



    def __init__(self): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getDescriptionManager(self) -> ghidra.features.bsim.query.description.DescriptionManager: ...

    def getLocalStagingCopy(self) -> ghidra.features.bsim.query.protocol.QueryResponseRecord: ...

    def getName(self) -> unicode: ...

    def hashCode(self) -> int: ...

    def mergeResults(self, __a0: ghidra.features.bsim.query.protocol.QueryResponseRecord) -> None: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def restoreXml(self, __a0: ghidra.xml.XmlPullParser, __a1: generic.lsh.vector.LSHVectorFactory) -> None: ...

    def saveXml(self, __a0: java.io.Writer) -> None: ...

    def sort(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def descriptionManager(self) -> ghidra.features.bsim.query.description.DescriptionManager: ...