from typing import overload
import ghidra.features.bsim.query
import java.lang
import java.sql


class BSimJDBCDataSource(object):








    def equals(self, __a0: object) -> bool: ...

    def getActiveConnections(self) -> int: ...

    def getClass(self) -> java.lang.Class: ...

    def getConnection(self) -> java.sql.Connection: ...

    def getConnectionType(self) -> ghidra.features.bsim.query.FunctionDatabase.ConnectionType: ...

    def getServerInfo(self) -> ghidra.features.bsim.query.BSimServerInfo: ...

    def getStatus(self) -> ghidra.features.bsim.query.FunctionDatabase.Status: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def activeConnections(self) -> int: ...

    @property
    def connection(self) -> java.sql.Connection: ...

    @property
    def connectionType(self) -> ghidra.features.bsim.query.FunctionDatabase.ConnectionType: ...

    @property
    def serverInfo(self) -> ghidra.features.bsim.query.BSimServerInfo: ...

    @property
    def status(self) -> ghidra.features.bsim.query.FunctionDatabase.Status: ...