from typing import overload
import ghidra.framework.plugintool.util
import java.lang
import javax.swing


class BsimPluginPackage(ghidra.framework.plugintool.util.PluginPackage):
    NAME: unicode = u'BSim'



    def __init__(self): ...



    @overload
    def compareTo(self, __a0: ghidra.framework.plugintool.util.PluginPackage) -> int: ...

    @overload
    def compareTo(self, __a0: object) -> int: ...

    def equals(self, __a0: object) -> bool: ...

    @staticmethod
    def exists(__a0: unicode) -> bool: ...

    def getActivationLevel(self) -> ghidra.framework.plugintool.util.PluginStatus: ...

    def getClass(self) -> java.lang.Class: ...

    def getDescription(self) -> unicode: ...

    def getIcon(self) -> javax.swing.Icon: ...

    def getName(self) -> unicode: ...

    @staticmethod
    def getPluginPackage(__a0: unicode) -> ghidra.framework.plugintool.util.PluginPackage: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def activationLevel(self) -> ghidra.framework.plugintool.util.PluginStatus: ...