from typing import overload
import ghidra.util
import java.lang


class MinimalErrorLogger(ghidra.util.DefaultErrorLogger):




    def __init__(self): ...



    @overload
    def debug(self, __a0: object, __a1: object) -> None: ...

    @overload
    def debug(self, __a0: object, __a1: object, __a2: java.lang.Throwable) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    @overload
    def error(self, __a0: object, __a1: object) -> None: ...

    @overload
    def error(self, __a0: object, __a1: object, __a2: java.lang.Throwable) -> None: ...

    def getClass(self) -> java.lang.Class: ...

    def hashCode(self) -> int: ...

    @overload
    def info(self, __a0: object, __a1: object) -> None: ...

    @overload
    def info(self, __a0: object, __a1: object, __a2: java.lang.Throwable) -> None: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def trace(self, __a0: object, __a1: object) -> None: ...

    @overload
    def trace(self, __a0: object, __a1: object, __a2: java.lang.Throwable) -> None: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @overload
    def warn(self, __a0: object, __a1: object) -> None: ...

    @overload
    def warn(self, __a0: object, __a1: object, __a2: java.lang.Throwable) -> None: ...

