# coding: utf-8

"""
    Evolution API

    </br> <hr style=\"height: 5px;background: #007500;margin: 20px 0;box-shadow: 0px 3px 5px 0px rgb(204 204 204);\">  <div align=\"center\">  [![Whatsapp Group](https://img.shields.io/badge/Group-WhatsApp-%2322BC18)](https://evolution-api.com/whatsapp) [![Discord Community](https://img.shields.io/badge/Discord-Community-blue)](https://evolution-api.com/discord) [![Postman Collection](https://img.shields.io/badge/Postman-Collection-orange)](https://evolution-api.com/postman)  [![Documentation](https://img.shields.io/badge/Documentation-Official-green)](https://doc.evolution-api.com) [![License](https://img.shields.io/badge/license-GPL--3.0-orange)](./LICENSE) [![Support](https://img.shields.io/badge/Donation-picpay-green)](https://app.picpay.com/user/davidsongomes1998) [![Support](https://img.shields.io/badge/Buy%20me-coffe-orange)](https://bmc.link/evolutionapi)  </div>    <div align=\"center\"><img src=\"https://raw.githubusercontent.com/EvolutionAPI/evolution-api/main/public/images/cover.png\"></div>  <font size='3'>   This project is based on the [evolution](https://github.com/code-chat-br/whatsapp-api). The original project is an implementation of [Baileys](https://github.com/WhiskeySockets/Baileys), serving as a Restful API service that controls WhatsApp functions.</br>    The code allows the creation of multiservice chats, service bots, or any other system that utilizes WhatsApp. The documentation provides instructions on how to set up and use the project, as well as additional information about its features and configuration options. </font>  [![Run in Postman](https://run.pstmn.io/button.svg)](https://god.gw.postman.com/run-collection/26869335-5546d063-156b-4529-915f-909dd628c090?action=collection%2Ffork&source=rip_markdown&collection-url=entityId%3D26869335-5546d063-156b-4529-915f-909dd628c090%26entityType%3Dcollection%26workspaceId%3D339a4ee7-378b-45c9-b5b8-fd2c0a9c2442) 

    The version of the OpenAPI document: 1.8.2
    Contact: contato@agenciadgcode.com
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from evolution_api_client.api.chat_controller_api import ChatControllerApi


class TestChatControllerApi(unittest.TestCase):
    """ChatControllerApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ChatControllerApi()

    def tearDown(self) -> None:
        pass

    def test_chat_archive_chat_instance_name_put(self) -> None:
        """Test case for chat_archive_chat_instance_name_put

        Archive specific chats for a given instance.
        """
        pass

    def test_chat_delete_message_for_everyone_instance_name_delete(self) -> None:
        """Test case for chat_delete_message_for_everyone_instance_name_delete

        Delete a message for everyone in a given instance.
        """
        pass

    def test_chat_fetch_profile_picture_url_instance_name_post(self) -> None:
        """Test case for chat_fetch_profile_picture_url_instance_name_post

        Retrieve the profile picture URL of a specific number.
        """
        pass

    def test_chat_find_chats_instance_name_get(self) -> None:
        """Test case for chat_find_chats_instance_name_get

        List all chats associated with a specific instance.
        """
        pass

    def test_chat_find_contacts_instance_name_post(self) -> None:
        """Test case for chat_find_contacts_instance_name_post

        Retrieve contact details using an ID.
        """
        pass

    def test_chat_find_messages_instance_name_post(self) -> None:
        """Test case for chat_find_messages_instance_name_post

        Search for messages based on specific criteria.
        """
        pass

    def test_chat_find_status_message_instance_name_post(self) -> None:
        """Test case for chat_find_status_message_instance_name_post

        Search for status messages using an ID.
        """
        pass

    def test_chat_get_base64_from_media_message_instance_name_post(self) -> None:
        """Test case for chat_get_base64_from_media_message_instance_name_post

        Convert media message content to Base64.
        """
        pass

    def test_chat_mark_message_as_read_instance_name_put(self) -> None:
        """Test case for chat_mark_message_as_read_instance_name_put

        Mark specific messages as read for a given instance.
        """
        pass

    def test_chat_whatsapp_numbers_instance_name_post(self) -> None:
        """Test case for chat_whatsapp_numbers_instance_name_post

        Provide a list of WhatsApp numbers associated with a given instance.
        """
        pass


if __name__ == '__main__':
    unittest.main()
