from typing import overload
import docking
import ghidra.app.plugin.core.debug.gui.stack
import java.awt
import java.awt.event
import java.lang


class DebuggerStackActionContext(docking.DefaultActionContext):




    def __init__(self, __a0: ghidra.app.plugin.core.debug.gui.stack.DebuggerStackProvider, __a1: ghidra.app.plugin.core.debug.gui.stack.StackFrameRow, __a2: java.awt.Component): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getComponentProvider(self) -> docking.ComponentProvider: ...

    def getContextObject(self) -> object: ...

    def getEventClickModifiers(self) -> int: ...

    def getFrame(self) -> ghidra.app.plugin.core.debug.gui.stack.StackFrameRow: ...

    def getMouseEvent(self) -> java.awt.event.MouseEvent: ...

    def getSourceComponent(self) -> java.awt.Component: ...

    def getSourceObject(self) -> object: ...

    def hasAnyEventClickModifiers(self, __a0: int) -> bool: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def setContextObject(self, __a0: object) -> docking.DefaultActionContext: ...

    def setEventClickModifiers(self, __a0: int) -> None: ...

    def setMouseEvent(self, __a0: java.awt.event.MouseEvent) -> docking.ActionContext: ...

    def setSourceObject(self, __a0: object) -> docking.ActionContext: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def frame(self) -> ghidra.app.plugin.core.debug.gui.stack.StackFrameRow: ...