from typing import List
from typing import overload
import docking.widgets.fieldpanel.field
import docking.widgets.fieldpanel.support
import java.awt
import java.lang
import javax.swing


class TerminalTextFieldElement(object, docking.widgets.fieldpanel.field.FieldElement):
    UNDERLINE_HEIGHT: int = 1



    def __init__(self, __a0: ghidra.app.plugin.core.terminal.vt.VtLine, __a1: java.awt.FontMetrics, __a2: ghidra.app.plugin.core.terminal.vt.AnsiColorResolver): ...



    def charAt(self, __a0: int) -> int: ...

    def equals(self, __a0: object) -> bool: ...

    def getCharacterIndexForDataLocation(self, __a0: int, __a1: int) -> int: ...

    def getClass(self) -> java.lang.Class: ...

    def getColor(self, __a0: int) -> java.awt.Color: ...

    def getDataLocationForCharacterIndex(self, __a0: int) -> docking.widgets.fieldpanel.support.RowColLocation: ...

    def getFieldElement(self, __a0: int) -> docking.widgets.fieldpanel.field.FieldElement: ...

    def getHeightAbove(self) -> int: ...

    def getHeightBelow(self) -> int: ...

    def getMaxCharactersForWidth(self, __a0: int) -> int: ...

    def getNumCols(self) -> int: ...

    def getStringWidth(self) -> int: ...

    def getText(self) -> unicode: ...

    def hashCode(self) -> int: ...

    def length(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def paint(self, __a0: javax.swing.JComponent, __a1: java.awt.Graphics, __a2: int, __a3: int) -> None: ...

    def replaceAll(self, __a0: List[int], __a1: int) -> docking.widgets.fieldpanel.field.FieldElement: ...

    @overload
    def substring(self, __a0: int) -> docking.widgets.fieldpanel.field.FieldElement: ...

    @overload
    def substring(self, __a0: int, __a1: int) -> docking.widgets.fieldpanel.field.FieldElement: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def heightAbove(self) -> int: ...

    @property
    def heightBelow(self) -> int: ...

    @property
    def numCols(self) -> int: ...

    @property
    def stringWidth(self) -> int: ...

    @property
    def text(self) -> unicode: ...