from typing import overload
import docking.widgets.fieldpanel.field
import docking.widgets.fieldpanel.internal
import docking.widgets.fieldpanel.support
import java.awt
import java.lang
import javax.swing


class TerminalLayout(docking.widgets.fieldpanel.support.SingleRowLayout):




    def __init__(self, __a0: ghidra.app.plugin.core.terminal.vt.VtLine, __a1: java.awt.FontMetrics, __a2: ghidra.app.plugin.core.terminal.vt.AnsiColorResolver): ...



    def contains(self, __a0: int) -> bool: ...

    def cursorBeginning(self, __a0: docking.widgets.fieldpanel.support.FieldLocation) -> int: ...

    def cursorDown(self, __a0: docking.widgets.fieldpanel.support.FieldLocation, __a1: int) -> bool: ...

    def cursorEnd(self, __a0: docking.widgets.fieldpanel.support.FieldLocation) -> int: ...

    def cursorLeft(self, __a0: docking.widgets.fieldpanel.support.FieldLocation) -> int: ...

    def cursorRight(self, __a0: docking.widgets.fieldpanel.support.FieldLocation) -> int: ...

    def cursorUp(self, __a0: docking.widgets.fieldpanel.support.FieldLocation, __a1: int) -> bool: ...

    def enterLayout(self, __a0: docking.widgets.fieldpanel.support.FieldLocation, __a1: int, __a2: bool) -> bool: ...

    def equals(self, __a0: object) -> bool: ...

    def getBeginRowFieldNum(self, __a0: int) -> int: ...

    def getClass(self) -> java.lang.Class: ...

    def getCompressableWidth(self) -> int: ...

    def getCursorRect(self, __a0: int, __a1: int, __a2: int) -> java.awt.Rectangle: ...

    def getEndRowFieldNum(self, __a0: int) -> int: ...

    def getField(self, __a0: int) -> docking.widgets.fieldpanel.field.Field: ...

    def getFieldBounds(self, __a0: int) -> java.awt.Rectangle: ...

    def getFieldIndex(self, __a0: int, __a1: int) -> int: ...

    def getHeight(self) -> int: ...

    def getHeightAbove(self) -> int: ...

    def getHeightBelow(self) -> int: ...

    def getIndexSize(self) -> int: ...

    def getNumFields(self) -> int: ...

    def getPrimaryOffset(self) -> int: ...

    def getRowID(self) -> int: ...

    def getScrollableUnitIncrement(self, __a0: int, __a1: int) -> int: ...

    def hashCode(self) -> int: ...

    def insertSpaceAbove(self, __a0: int) -> None: ...

    def insertSpaceBelow(self, __a0: int) -> None: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def paint(self, __a0: javax.swing.JComponent, __a1: java.awt.Graphics, __a2: docking.widgets.fieldpanel.internal.PaintContext, __a3: java.awt.Rectangle, __a4: docking.widgets.fieldpanel.internal.LayoutBackgroundColorManager, __a5: docking.widgets.fieldpanel.support.FieldLocation) -> None: ...

    def setCursor(self, __a0: docking.widgets.fieldpanel.support.FieldLocation, __a1: int, __a2: int) -> int: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

