from typing import overload
import ghidra.program.model.address
import ghidra.trace.model
import ghidra.util.database.spatial.rect
import java.lang


class TraceAddressSnapSpace(object, ghidra.util.database.spatial.rect.EuclideanSpace2D):








    @overload
    def compareX(self, __a0: ghidra.program.model.address.Address, __a1: ghidra.program.model.address.Address) -> int: ...

    @overload
    def compareX(self, __a0: object, __a1: object) -> int: ...

    @overload
    def compareY(self, __a0: long, __a1: long) -> int: ...

    @overload
    def compareY(self, __a0: object, __a1: object) -> int: ...

    @overload
    def distX(self, __a0: ghidra.program.model.address.Address, __a1: ghidra.program.model.address.Address) -> float: ...

    @overload
    def distX(self, __a0: object, __a1: object) -> float: ...

    @overload
    def distY(self, __a0: long, __a1: long) -> float: ...

    @overload
    def distY(self, __a0: object, __a1: object) -> float: ...

    def equals(self, __a0: object) -> bool: ...

    @staticmethod
    def forAddressSpace(__a0: ghidra.program.model.address.AddressSpace) -> ghidra.trace.model.TraceAddressSnapSpace: ...

    def getClass(self) -> java.lang.Class: ...

    def getFull(self) -> ghidra.util.database.spatial.rect.Rectangle2D: ...

    def hashCode(self) -> int: ...

    def maxX(self, __a0: object, __a1: object) -> object: ...

    def maxY(self, __a0: object, __a1: object) -> object: ...

    @overload
    def midX(self, __a0: ghidra.program.model.address.Address, __a1: ghidra.program.model.address.Address) -> ghidra.program.model.address.Address: ...

    @overload
    def midX(self, __a0: object, __a1: object) -> object: ...

    @overload
    def midY(self, __a0: long, __a1: long) -> long: ...

    @overload
    def midY(self, __a0: object, __a1: object) -> object: ...

    def minX(self, __a0: object, __a1: object) -> object: ...

    def minY(self, __a0: object, __a1: object) -> object: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def full(self) -> ghidra.trace.model.TraceAddressSnapRange: ...