from typing import overload
import ghidra.program.model.address
import ghidra.trace.model
import ghidra.trace.model.bookmark
import ghidra.trace.model.stack
import ghidra.trace.model.thread
import java.awt
import java.lang
import java.util
import javax.swing


class TraceBookmarkManager(ghidra.trace.model.bookmark.TraceBookmarkOperations, object):








    def addBookmark(self, __a0: ghidra.trace.model.Lifespan, __a1: ghidra.program.model.address.Address, __a2: ghidra.trace.model.bookmark.TraceBookmarkType, __a3: unicode, __a4: unicode) -> ghidra.trace.model.bookmark.TraceBookmark: ...

    def defineBookmarkType(self, __a0: unicode, __a1: javax.swing.Icon, __a2: java.awt.Color, __a3: int) -> ghidra.trace.model.bookmark.TraceBookmarkType: ...

    def equals(self, __a0: object) -> bool: ...

    def getAllBookmarks(self) -> java.util.Collection: ...

    def getBookmark(self, __a0: long) -> ghidra.trace.model.bookmark.TraceBookmark: ...

    @overload
    def getBookmarkRegisterSpace(self, __a0: ghidra.trace.model.stack.TraceStackFrame, __a1: bool) -> ghidra.trace.model.bookmark.TraceBookmarkSpace: ...

    @overload
    def getBookmarkRegisterSpace(self, __a0: ghidra.trace.model.thread.TraceThread, __a1: bool) -> ghidra.trace.model.bookmark.TraceBookmarkSpace: ...

    def getBookmarkSpace(self, __a0: ghidra.program.model.address.AddressSpace, __a1: bool) -> ghidra.trace.model.bookmark.TraceBookmarkSpace: ...

    def getBookmarkType(self, __a0: unicode) -> ghidra.trace.model.bookmark.TraceBookmarkType: ...

    def getBookmarksAdded(self, __a0: long, __a1: long) -> java.util.Collection: ...

    def getBookmarksAt(self, __a0: long, __a1: ghidra.program.model.address.Address) -> java.lang.Iterable: ...

    def getBookmarksEnclosed(self, __a0: ghidra.trace.model.Lifespan, __a1: ghidra.program.model.address.AddressRange) -> java.lang.Iterable: ...

    def getBookmarksIntersecting(self, __a0: ghidra.trace.model.Lifespan, __a1: ghidra.program.model.address.AddressRange) -> java.lang.Iterable: ...

    def getBookmarksRemoved(self, __a0: long, __a1: long) -> java.util.Collection: ...

    def getCategoriesForType(self, __a0: ghidra.trace.model.bookmark.TraceBookmarkType) -> java.util.Set: ...

    def getClass(self) -> java.lang.Class: ...

    def getDefinedBookmarkTypes(self) -> java.util.Collection: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def allBookmarks(self) -> java.util.Collection: ...

    @property
    def definedBookmarkTypes(self) -> java.util.Collection: ...