from typing import overload
import ghidra.dbg.target
import java.lang


class ObjectAttributeRow(object):




    def __init__(self, __a0: ghidra.dbg.target.TargetObject, __a1: ghidra.app.plugin.core.debug.gui.objects.DebuggerObjectsProvider): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getDisplay(self) -> unicode: ...

    def getKind(self) -> unicode: ...

    def getName(self) -> unicode: ...

    def getTargetObject(self) -> ghidra.dbg.target.TargetObject: ...

    def getType(self) -> unicode: ...

    def getValue(self) -> unicode: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def display(self) -> unicode: ...

    @property
    def kind(self) -> unicode: ...

    @property
    def name(self) -> unicode: ...

    @property
    def targetObject(self) -> ghidra.dbg.target.TargetObject: ...

    @property
    def type(self) -> unicode: ...

    @property
    def value(self) -> unicode: ...