from typing import List
from typing import overload
import ghidra.app.plugin.core.debug.gui.objects
import ghidra.app.plugin.core.debug.gui.objects.components
import ghidra.dbg.target
import java.lang
import javax.swing


class ObjectTree(object, ghidra.app.plugin.core.debug.gui.objects.components.ObjectPane):
    ICON_TREE: javax.swing.Icon



    def __init__(self, __a0: ghidra.app.plugin.core.debug.gui.objects.ObjectContainer): ...



    def addToMap(self, __a0: ghidra.app.plugin.core.debug.gui.objects.ObjectContainer, __a1: ghidra.app.plugin.core.debug.gui.objects.ObjectContainer, __a2: ghidra.app.plugin.core.debug.gui.objects.components.ObjectNode) -> None: ...

    def cleanupOldNode(self, __a0: ghidra.app.plugin.core.debug.gui.objects.components.ObjectNode) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getComponent(self) -> javax.swing.JComponent: ...

    def getContainer(self) -> ghidra.app.plugin.core.debug.gui.objects.ObjectContainer: ...

    def getName(self) -> unicode: ...

    def getPrincipalComponent(self) -> javax.swing.JComponent: ...

    def getProvider(self) -> ghidra.app.plugin.core.debug.gui.objects.DebuggerObjectsProvider: ...

    def getSelectedObject(self) -> ghidra.dbg.target.TargetObject: ...

    def getTargetObject(self) -> ghidra.dbg.target.TargetObject: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def setFocus(self, __a0: ghidra.dbg.target.TargetObject, __a1: ghidra.dbg.target.TargetObject) -> None: ...

    def setRoot(self, __a0: ghidra.app.plugin.core.debug.gui.objects.ObjectContainer, __a1: ghidra.dbg.target.TargetObject) -> None: ...

    def setSelectedNode(self, __a0: ghidra.app.plugin.core.debug.gui.objects.components.ObjectNode) -> None: ...

    def setSelectedObject(self, __a0: ghidra.dbg.target.TargetObject) -> None: ...

    def signalContentsChanged(self, __a0: ghidra.app.plugin.core.debug.gui.objects.ObjectContainer) -> None: ...

    def signalDataChanged(self, __a0: ghidra.app.plugin.core.debug.gui.objects.ObjectContainer) -> None: ...

    def signalUpdate(self, __a0: ghidra.app.plugin.core.debug.gui.objects.ObjectContainer) -> None: ...

    def toString(self) -> unicode: ...

    def update(self, __a0: ghidra.app.plugin.core.debug.gui.objects.ObjectContainer) -> List[object]: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    def waitOnLoad(self) -> None: ...

    @property
    def component(self) -> javax.swing.JComponent: ...

    @property
    def container(self) -> ghidra.app.plugin.core.debug.gui.objects.ObjectContainer: ...

    @property
    def name(self) -> unicode: ...

    @property
    def principalComponent(self) -> javax.swing.JComponent: ...

    @property
    def provider(self) -> ghidra.app.plugin.core.debug.gui.objects.DebuggerObjectsProvider: ...

    @property
    def selectedNode(self) -> None: ...  # No getter available.

    @selectedNode.setter
    def selectedNode(self, value: ghidra.app.plugin.core.debug.gui.objects.components.ObjectNode) -> None: ...

    @property
    def selectedObject(self) -> ghidra.dbg.target.TargetObject: ...

    @selectedObject.setter
    def selectedObject(self, value: ghidra.dbg.target.TargetObject) -> None: ...

    @property
    def targetObject(self) -> ghidra.dbg.target.TargetObject: ...