from typing import List
from typing import overload
import ghidra.trace.model
import ghidra.trace.model.memory
import ghidra.trace.model.target
import ghidra.trace.model.thread
import java.lang


class TraceObjectRegister(ghidra.trace.model.target.TraceObjectInterface, object):
    KEY_STATE: unicode = u'_state'







    def computeMaxSnap(self) -> long: ...

    def computeMinSnap(self) -> long: ...

    def computeSpan(self) -> ghidra.trace.model.Lifespan: ...

    def equals(self, __a0: object) -> bool: ...

    def getBitLength(self) -> int: ...

    def getByteLength(self) -> int: ...

    def getClass(self) -> java.lang.Class: ...

    def getName(self) -> unicode: ...

    def getObject(self) -> ghidra.trace.model.target.TraceObject: ...

    def getState(self, __a0: long) -> ghidra.trace.model.memory.TraceMemoryState: ...

    def getThread(self) -> ghidra.trace.model.thread.TraceObjectThread: ...

    def getValue(self, __a0: long) -> List[int]: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def setState(self, __a0: ghidra.trace.model.Lifespan, __a1: ghidra.trace.model.memory.TraceMemoryState) -> None: ...

    def setValue(self, __a0: ghidra.trace.model.Lifespan, __a1: List[int]) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def bitLength(self) -> int: ...

    @property
    def byteLength(self) -> int: ...

    @property
    def name(self) -> unicode: ...

    @property
    def object(self) -> ghidra.trace.model.target.TraceObject: ...

    @property
    def thread(self) -> ghidra.trace.model.thread.TraceObjectThread: ...