from typing import List
from typing import overload
import db
import ghidra.framework.data
import ghidra.trace.model
import java.lang


class DBTraceChangeSet(object, ghidra.trace.model.TraceChangeSet, ghidra.framework.data.DomainObjectDBChangeSet):




    def __init__(self): ...



    def categoryAdded(self, __a0: long) -> None: ...

    def categoryChanged(self, __a0: long) -> None: ...

    @overload
    def clearUndo(self) -> None: ...

    @overload
    def clearUndo(self, __a0: bool) -> None: ...

    def dataTypeAdded(self, __a0: long) -> None: ...

    def dataTypeChanged(self, __a0: long) -> None: ...

    def endTransaction(self, __a0: bool) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getCategoryAdditions(self) -> List[long]: ...

    def getCategoryChanges(self) -> List[long]: ...

    def getClass(self) -> java.lang.Class: ...

    def getDataTypeAdditions(self) -> List[long]: ...

    def getDataTypeChanges(self) -> List[long]: ...

    def getSourceArchiveAdditions(self) -> List[long]: ...

    def getSourceArchiveChanges(self) -> List[long]: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def read(self, __a0: db.DBHandle) -> None: ...

    def redo(self) -> None: ...

    def setMaxUndos(self, __a0: int) -> None: ...

    def sourceArchiveAdded(self, __a0: long) -> None: ...

    def sourceArchiveChanged(self, __a0: long) -> None: ...

    def startTransaction(self) -> None: ...

    def toString(self) -> unicode: ...

    def undo(self) -> None: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    def write(self, __a0: db.DBHandle, __a1: bool) -> None: ...

    @property
    def categoryAdditions(self) -> List[long]: ...

    @property
    def categoryChanges(self) -> List[long]: ...

    @property
    def dataTypeAdditions(self) -> List[long]: ...

    @property
    def dataTypeChanges(self) -> List[long]: ...

    @property
    def maxUndos(self) -> None: ...  # No getter available.

    @maxUndos.setter
    def maxUndos(self, value: int) -> None: ...

    @property
    def sourceArchiveAdditions(self) -> List[long]: ...

    @property
    def sourceArchiveChanges(self) -> List[long]: ...