from typing import Iterator
from typing import List
from typing import overload
import ghidra.util.datastruct
import java.lang
import java.util
import java.util.function
import java.util.stream
import org.apache.commons.collections4.collection


class DefaultObservableCollection(org.apache.commons.collections4.collection.AbstractCollectionDecorator, ghidra.util.datastruct.ObservableCollection):






    def __iter__(self): ...

    def add(self, __a0: object) -> bool: ...

    def addAll(self, __a0: java.util.Collection) -> bool: ...

    def addChangeListener(self, __a0: ghidra.util.datastruct.CollectionChangeListener) -> None: ...

    def aggregateChanges(self) -> ghidra.util.datastruct.ObservableCollection.ChangeAggregator: ...

    def clear(self) -> None: ...

    def contains(self, __a0: object) -> bool: ...

    def containsAll(self, __a0: java.util.Collection) -> bool: ...

    def equals(self, __a0: object) -> bool: ...

    def forEach(self, __a0: java.util.function.Consumer) -> None: ...

    def getClass(self) -> java.lang.Class: ...

    def hashCode(self) -> int: ...

    def isEmpty(self) -> bool: ...

    def iterator(self) -> java.util.Iterator: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def notifyModified(self, __a0: object) -> None: ...

    def parallelStream(self) -> java.util.stream.Stream: ...

    def remove(self, __a0: object) -> bool: ...

    def removeAll(self, __a0: java.util.Collection) -> bool: ...

    def removeChangeListener(self, __a0: ghidra.util.datastruct.CollectionChangeListener) -> None: ...

    def removeIf(self, __a0: java.util.function.Predicate) -> bool: ...

    def retainAll(self, __a0: java.util.Collection) -> bool: ...

    def size(self) -> int: ...

    def spliterator(self) -> java.util.Spliterator: ...

    def stream(self) -> java.util.stream.Stream: ...

    @overload
    def toArray(self) -> List[object]: ...

    @overload
    def toArray(self, __a0: List[object]) -> List[object]: ...

    @overload
    def toArray(self, __a0: java.util.function.IntFunction) -> List[object]: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

