from typing import overload
import ghidra.pcodeCPort.slghpatexpress
import ghidra.pcodeCPort.slghsymbol
import ghidra.program.model.pcode
import ghidra.sleigh.grammar
import java.io
import java.lang
import java.util


class SubtableSymbol(ghidra.pcodeCPort.slghsymbol.TripleSymbol):
    location: ghidra.sleigh.grammar.Location



    @overload
    def __init__(self, __a0: ghidra.sleigh.grammar.Location): ...

    @overload
    def __init__(self, __a0: ghidra.sleigh.grammar.Location, __a1: unicode): ...



    def addConstructor(self, __a0: ghidra.pcodeCPort.slghsymbol.Constructor) -> None: ...

    def buildDecisionTree(self, __a0: ghidra.pcodeCPort.slghsymbol.DecisionProperties) -> None: ...

    def buildPattern(self, __a0: java.io.PrintStream) -> ghidra.pcodeCPort.slghpatexpress.TokenPattern: ...

    def collectLocalValues(self, __a0: java.util.ArrayList) -> None: ...

    @overload
    def compareTo(self, __a0: ghidra.pcodeCPort.slghsymbol.SleighSymbol) -> int: ...

    @overload
    def compareTo(self, __a0: object) -> int: ...

    def dispose(self) -> None: ...

    def encode(self, __a0: ghidra.program.model.pcode.Encoder) -> None: ...

    def encodeHeader(self, __a0: ghidra.program.model.pcode.Encoder) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getConstructor(self, __a0: int) -> ghidra.pcodeCPort.slghsymbol.Constructor: ...

    def getId(self) -> int: ...

    def getLocation(self) -> ghidra.sleigh.grammar.Location: ...

    def getName(self) -> unicode: ...

    def getNumConstructors(self) -> int: ...

    def getPattern(self) -> ghidra.pcodeCPort.slghpatexpress.TokenPattern: ...

    def getPatternExpression(self) -> ghidra.pcodeCPort.slghpatexpress.PatternExpression: ...

    def getSize(self) -> int: ...

    def getType(self) -> ghidra.pcodeCPort.slghsymbol.symbol_type: ...

    def hashCode(self) -> int: ...

    def isBeingBuilt(self) -> bool: ...

    def isError(self) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def setLocation(self, __a0: ghidra.sleigh.grammar.Location) -> None: ...

    def setWasSought(self, __a0: bool) -> None: ...

    def toDetailedString(self) -> unicode: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    def wasSought(self) -> bool: ...

    @property
    def beingBuilt(self) -> bool: ...

    @property
    def error(self) -> bool: ...

    @property
    def numConstructors(self) -> int: ...

    @property
    def pattern(self) -> ghidra.pcodeCPort.slghpatexpress.TokenPattern: ...

    @property
    def patternExpression(self) -> ghidra.pcodeCPort.slghpatexpress.PatternExpression: ...

    @property
    def size(self) -> int: ...

    @property
    def type(self) -> ghidra.pcodeCPort.slghsymbol.symbol_type: ...