from typing import overload
import generic.stl
import ghidra.pcodeCPort.slghsymbol
import ghidra.program.model.pcode
import java.lang


class SymbolTable(object):




    def __init__(self): ...



    def addGlobalSymbol(self, __a0: ghidra.pcodeCPort.slghsymbol.SleighSymbol) -> None: ...

    def addScope(self) -> None: ...

    def addSymbol(self, __a0: ghidra.pcodeCPort.slghsymbol.SleighSymbol) -> int: ...

    def dispose(self) -> None: ...

    def encode(self, __a0: ghidra.program.model.pcode.Encoder) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def findGlobalSymbol(self, __a0: unicode) -> ghidra.pcodeCPort.slghsymbol.SleighSymbol: ...

    @overload
    def findSymbol(self, __a0: int) -> ghidra.pcodeCPort.slghsymbol.SleighSymbol: ...

    @overload
    def findSymbol(self, __a0: unicode) -> ghidra.pcodeCPort.slghsymbol.SleighSymbol: ...

    @overload
    def findSymbol(self, __a0: unicode, __a1: int) -> ghidra.pcodeCPort.slghsymbol.SleighSymbol: ...

    def getClass(self) -> java.lang.Class: ...

    def getCurrentScope(self) -> ghidra.pcodeCPort.slghsymbol.SymbolScope: ...

    def getGlobalScope(self) -> ghidra.pcodeCPort.slghsymbol.SymbolScope: ...

    def getUnsoughtSymbols(self) -> generic.stl.VectorSTL: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def popScope(self) -> None: ...

    def purge(self) -> None: ...

    def replaceSymbol(self, __a0: ghidra.pcodeCPort.slghsymbol.SleighSymbol, __a1: ghidra.pcodeCPort.slghsymbol.SleighSymbol) -> None: ...

    def setCurrentScope(self, __a0: ghidra.pcodeCPort.slghsymbol.SymbolScope) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def currentScope(self) -> ghidra.pcodeCPort.slghsymbol.SymbolScope: ...

    @currentScope.setter
    def currentScope(self, value: ghidra.pcodeCPort.slghsymbol.SymbolScope) -> None: ...

    @property
    def globalScope(self) -> ghidra.pcodeCPort.slghsymbol.SymbolScope: ...

    @property
    def unsoughtSymbols(self) -> generic.stl.VectorSTL: ...