from typing import List
from typing import overload
import ghidra.app.plugin.core.debug.gui.pcode
import ghidra.program.model.pcode
import java.lang
import java.util


class EnumPcodeRow(java.lang.Enum, ghidra.app.plugin.core.debug.gui.pcode.PcodeRow):
    DECODE: ghidra.app.plugin.core.debug.gui.pcode.EnumPcodeRow
    NO_THREAD: ghidra.app.plugin.core.debug.gui.pcode.EnumPcodeRow







    @overload
    def compareTo(self, __a0: java.lang.Enum) -> int: ...

    @overload
    def compareTo(self, __a0: object) -> int: ...

    def describeConstable(self) -> java.util.Optional: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getCode(self) -> unicode: ...

    def getDeclaringClass(self) -> java.lang.Class: ...

    def getLabel(self) -> unicode: ...

    def getOp(self) -> ghidra.program.model.pcode.PcodeOp: ...

    def getSequence(self) -> int: ...

    def hashCode(self) -> int: ...

    def isNext(self) -> bool: ...

    def name(self) -> unicode: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def ordinal(self) -> int: ...

    def toString(self) -> unicode: ...

    @overload
    @staticmethod
    def valueOf(__a0: unicode) -> ghidra.app.plugin.core.debug.gui.pcode.EnumPcodeRow: ...

    @overload
    @staticmethod
    def valueOf(__a0: java.lang.Class, __a1: unicode) -> java.lang.Enum: ...

    @staticmethod
    def values() -> List[ghidra.app.plugin.core.debug.gui.pcode.EnumPcodeRow]: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def code(self) -> unicode: ...

    @property
    def label(self) -> unicode: ...

    @property
    def next(self) -> bool: ...

    @property
    def op(self) -> ghidra.program.model.pcode.PcodeOp: ...

    @property
    def sequence(self) -> int: ...