from .ImageMethod_Marshmallow import ImageMethod_Marshmallow as ImageMethod_Marshmallow
from .ImageMethod_Nougat import ImageMethod_Nougat as ImageMethod_Nougat
from .ImageMethod_Oreo import ImageMethod_Oreo as ImageMethod_Oreo
from .ImageMethod_Pie import ImageMethod_Pie as ImageMethod_Pie
from .ImageMethod_Q import ImageMethod_Q as ImageMethod_Q