# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pose_stamped.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from seerep.pb import header_pb2 as header__pb2
from seerep.pb import pose_pb2 as pose__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12pose_stamped.proto\x12\tseerep.pb\x1a\x0cheader.proto\x1a\npose.proto\"O\n\x0bPoseStamped\x12!\n\x06header\x18\x01 \x01(\x0b\x32\x11.seerep.pb.Header\x12\x1d\n\x04pose\x18\x02 \x01(\x0b\x32\x0f.seerep.pb.Poseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pose_stamped_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _POSESTAMPED._serialized_start=59
  _POSESTAMPED._serialized_end=138
# @@protoc_insertion_point(module_scope)
