# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: transfer_sensor_msgs.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from seerep.pb import header_pb2 as header__pb2
from seerep.pb import point_pb2 as point__pb2
from seerep.pb import pose_stamped_pb2 as pose__stamped__pb2
from seerep.pb import pose_pb2 as pose__pb2
from seerep.pb import quaternion_pb2 as quaternion__pb2
from seerep.pb import server_response_pb2 as server__response__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1atransfer_sensor_msgs.proto\x12\tseerep.pb\x1a\x0cheader.proto\x1a\x0bpoint.proto\x1a\x12pose_stamped.proto\x1a\npose.proto\x1a\x10quaternion.proto\x1a\x15server_response.proto2\xe0\x02\n\x12TransferSensorMsgs\x12>\n\x0eTransferHeader\x12\x11.seerep.pb.Header\x1a\x19.seerep.pb.ServerResponse\x12<\n\rTransferPoint\x12\x10.seerep.pb.Point\x1a\x19.seerep.pb.ServerResponse\x12\x46\n\x12TransferQuaternion\x12\x15.seerep.pb.Quaternion\x1a\x19.seerep.pb.ServerResponse\x12:\n\x0cTransferPose\x12\x0f.seerep.pb.Pose\x1a\x19.seerep.pb.ServerResponse\x12H\n\x13TransferPoseStamped\x12\x16.seerep.pb.PoseStamped\x1a\x19.seerep.pb.ServerResponseb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'transfer_sensor_msgs_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TRANSFERSENSORMSGS._serialized_start=142
  _TRANSFERSENSORMSGS._serialized_end=494
# @@protoc_insertion_point(module_scope)
