from typing import overload
import ghidra.program.model.address
import ghidra.trace.model.listing
import java.lang


class TraceCodeSpace(ghidra.trace.model.listing.TraceCodeOperations, object):








    def codeUnits(self) -> ghidra.trace.model.listing.TraceCodeUnitsView: ...

    def data(self) -> ghidra.trace.model.listing.TraceDataView: ...

    def definedData(self) -> ghidra.trace.model.listing.TraceDefinedDataView: ...

    def definedUnits(self) -> ghidra.trace.model.listing.TraceDefinedUnitsView: ...

    def equals(self, __a0: object) -> bool: ...

    def getAddressSpace(self) -> ghidra.program.model.address.AddressSpace: ...

    def getClass(self) -> java.lang.Class: ...

    def hashCode(self) -> int: ...

    def instructions(self) -> ghidra.trace.model.listing.TraceInstructionsView: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    def undefinedData(self) -> ghidra.trace.model.listing.TraceUndefinedDataView: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def addressSpace(self) -> ghidra.program.model.address.AddressSpace: ...