from typing import overload
import ghidra.program.model.address
import ghidra.program.model.symbol
import ghidra.trace.database.symbol
import ghidra.trace.model
import ghidra.trace.model.symbol
import ghidra.trace.model.thread
import java.lang


class DBTraceStackReference(ghidra.trace.database.symbol.DBTraceReference, ghidra.trace.model.symbol.TraceStackReference):




    def __init__(self, __a0: ghidra.trace.database.symbol.DBTraceReferenceSpace.DBTraceReferenceEntry): ...



    def clearAssociatedSymbol(self) -> None: ...

    @overload
    def compareTo(self, __a0: ghidra.program.model.symbol.Reference) -> int: ...

    @overload
    def compareTo(self, __a0: object) -> int: ...

    def delete(self) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getAssociatedSymbol(self) -> ghidra.program.model.symbol.Symbol: ...

    def getClass(self) -> java.lang.Class: ...

    def getFromAddress(self) -> ghidra.program.model.address.Address: ...

    def getLifespan(self) -> ghidra.trace.model.Lifespan: ...

    def getOperandIndex(self) -> int: ...

    def getReferenceType(self) -> ghidra.program.model.symbol.RefType: ...

    def getSource(self) -> ghidra.program.model.symbol.SourceType: ...

    def getStackOffset(self) -> int: ...

    def getStartSnap(self) -> long: ...

    def getSymbolID(self) -> long: ...

    def getThread(self) -> ghidra.trace.model.thread.TraceThread: ...

    def getToAddress(self) -> ghidra.program.model.address.Address: ...

    def getTrace(self) -> ghidra.trace.model.Trace: ...

    def hashCode(self) -> int: ...

    def isEntryPointReference(self) -> bool: ...

    def isExternalReference(self) -> bool: ...

    def isMemoryReference(self) -> bool: ...

    def isMnemonicReference(self) -> bool: ...

    def isOffsetReference(self) -> bool: ...

    def isOperandReference(self) -> bool: ...

    def isPrimary(self) -> bool: ...

    def isRegisterReference(self) -> bool: ...

    def isShiftedReference(self) -> bool: ...

    def isStackReference(self) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def setAssociatedSymbol(self, __a0: ghidra.program.model.symbol.Symbol) -> None: ...

    def setPrimary(self, __a0: bool) -> None: ...

    def setReferenceType(self, __a0: ghidra.program.model.symbol.RefType) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

