from typing import overload
import docking.action
import docking.widgets
import ghidra.service.graph
import ghidra.util.task
import java.lang
import java.util


class DefaultGraphDisplay(object, ghidra.service.graph.GraphDisplay):








    def addAction(self, __a0: docking.action.DockingActionIf) -> None: ...

    def centerAndScale(self) -> None: ...

    def clear(self) -> None: ...

    def close(self) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    @staticmethod
    def flatten(__a0: java.util.Collection) -> java.util.Set: ...

    def getActions(self) -> java.util.Collection: ...

    def getAllComponentVerticesFromSelected(self) -> java.util.Set: ...

    def getClass(self) -> java.lang.Class: ...

    def getFocusedVertex(self) -> ghidra.service.graph.AttributedVertex: ...

    def getGraph(self) -> ghidra.service.graph.AttributedGraph: ...

    def getGraphTitle(self) -> unicode: ...

    def getSelectedVertices(self) -> java.util.Set: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def selectVertices(self, __a0: java.util.Set, __a1: docking.widgets.EventTrigger) -> None: ...

    @overload
    def setFocusedVertex(self, __a0: ghidra.service.graph.AttributedVertex) -> None: ...

    @overload
    def setFocusedVertex(self, __a0: ghidra.service.graph.AttributedVertex, __a1: docking.widgets.EventTrigger) -> None: ...

    @overload
    def setGraph(self, __a0: ghidra.service.graph.AttributedGraph, __a1: unicode, __a2: bool, __a3: ghidra.util.task.TaskMonitor) -> None: ...

    @overload
    def setGraph(self, __a0: ghidra.service.graph.AttributedGraph, __a1: ghidra.service.graph.GraphDisplayOptions, __a2: unicode, __a3: bool, __a4: ghidra.util.task.TaskMonitor) -> None: ...

    def setGraphDisplayListener(self, __a0: ghidra.service.graph.GraphDisplayListener) -> None: ...

    def toString(self) -> unicode: ...

    def updateVertexName(self, __a0: ghidra.service.graph.AttributedVertex, __a1: unicode) -> None: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def actions(self) -> java.util.Collection: ...

    @property
    def allComponentVerticesFromSelected(self) -> java.util.Set: ...

    @property
    def focusedVertex(self) -> ghidra.service.graph.AttributedVertex: ...

    @focusedVertex.setter
    def focusedVertex(self, value: ghidra.service.graph.AttributedVertex) -> None: ...

    @property
    def graph(self) -> ghidra.service.graph.AttributedGraph: ...

    @property
    def graphDisplayListener(self) -> None: ...  # No getter available.

    @graphDisplayListener.setter
    def graphDisplayListener(self, value: ghidra.service.graph.GraphDisplayListener) -> None: ...

    @property
    def graphTitle(self) -> unicode: ...

    @property
    def selectedVertices(self) -> java.util.Set: ...