
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-07-15T17:57:53+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "a362033dd615cf75785bd78d3b8461dd0e5f5e14",
 "version": "0.4.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
