from typing import overload
import docking
import docking.action
import ghidra.app.plugin.core.strings
import ghidra.program.model.listing
import ghidra.util
import ghidra.util.task
import java.awt
import java.awt.event
import java.lang
import java.util
import javax.swing


class EncodedStringsDialog(docking.DialogComponentProvider):




    def __init__(self, __a0: ghidra.app.plugin.core.strings.EncodedStringsPlugin, __a1: ghidra.program.model.listing.Program, __a2: ghidra.program.model.address.AddressSetView): ...



    def addAction(self, __a0: docking.action.DockingActionIf) -> None: ...

    def clearStatusText(self) -> None: ...

    def close(self) -> None: ...

    def dispose(self) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getActionContext(self, __a0: java.awt.event.MouseEvent) -> docking.ActionContext: ...

    def getActions(self) -> java.util.Set: ...

    def getBackground(self) -> java.awt.Color: ...

    def getClass(self) -> java.lang.Class: ...

    def getComponent(self) -> javax.swing.JComponent: ...

    def getCreateButton(self) -> javax.swing.JButton: ...

    def getDefaultButton(self) -> javax.swing.JButton: ...

    def getDefaultSize(self) -> java.awt.Dimension: ...

    def getFocusComponent(self) -> java.awt.Component: ...

    def getHelpLocation(self) -> ghidra.util.HelpLocation: ...

    def getId(self) -> int: ...

    def getInitialLocation(self) -> java.awt.Point: ...

    def getPreferredSize(self) -> java.awt.Dimension: ...

    def getRememberLocation(self) -> bool: ...

    def getRememberSize(self) -> bool: ...

    def getStatusText(self) -> unicode: ...

    def getStringModel(self) -> ghidra.app.plugin.core.strings.EncodedStringsTableModel: ...

    def getTitle(self) -> unicode: ...

    def getUseSharedLocation(self) -> bool: ...

    def hashCode(self) -> int: ...

    def hideTaskMonitorComponent(self) -> None: ...

    def isModal(self) -> bool: ...

    def isResizeable(self) -> bool: ...

    def isRunningTask(self) -> bool: ...

    def isShowing(self) -> bool: ...

    def isTransient(self) -> bool: ...

    def isVisible(self) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def programClosed(self, __a0: ghidra.program.model.listing.Program) -> None: ...

    def removeAction(self, __a0: docking.action.DockingActionIf) -> None: ...

    def setAccessibleDescription(self, __a0: unicode) -> None: ...

    def setAllowAnyScriptOption(self, __a0: bool) -> None: ...

    def setAllowCommonScriptOption(self, __a0: bool) -> None: ...

    def setAllowLatinScriptOption(self, __a0: bool) -> None: ...

    def setBackground(self, __a0: java.awt.Color) -> None: ...

    def setCursor(self, __a0: java.awt.Cursor) -> None: ...

    def setDefaultButton(self, __a0: javax.swing.JButton) -> None: ...

    def setDefaultSize(self, __a0: int, __a1: int) -> None: ...

    def setExcludeCodecErrors(self, __a0: bool) -> None: ...

    def setExcludeNonStdCtrlChars(self, __a0: bool) -> None: ...

    def setFocusComponent(self, __a0: java.awt.Component) -> None: ...

    def setHelpLocation(self, __a0: ghidra.util.HelpLocation) -> None: ...

    def setInitialLocation(self, __a0: int, __a1: int) -> None: ...

    @overload
    def setMinimumSize(self, __a0: java.awt.Dimension) -> None: ...

    @overload
    def setMinimumSize(self, __a0: int, __a1: int) -> None: ...

    def setPreferredSize(self, __a0: int, __a1: int) -> None: ...

    def setRememberLocation(self, __a0: bool) -> None: ...

    def setRememberSize(self, __a0: bool) -> None: ...

    def setRequireValidStringOption(self, __a0: bool) -> None: ...

    def setRequiredScript(self, __a0: java.lang.Character.UnicodeScript) -> None: ...

    def setResizable(self, __a0: bool) -> None: ...

    def setSelectedCharset(self, __a0: unicode) -> None: ...

    def setShowAdvancedOptions(self, __a0: bool) -> None: ...

    def setShowScriptOptions(self, __a0: bool) -> None: ...

    def setStatusJustification(self, __a0: int) -> None: ...

    @overload
    def setStatusText(self, __a0: unicode) -> None: ...

    @overload
    def setStatusText(self, __a0: unicode, __a1: ghidra.util.MessageType) -> None: ...

    @overload
    def setStatusText(self, __a0: unicode, __a1: ghidra.util.MessageType, __a2: bool) -> None: ...

    def setTitle(self, __a0: unicode) -> None: ...

    def setTransient(self, __a0: bool) -> None: ...

    def setUseSharedLocation(self, __a0: bool) -> None: ...

    def showTaskMonitorComponent(self, __a0: unicode, __a1: bool, __a2: bool) -> ghidra.util.task.TaskMonitor: ...

    def taskCancelled(self, __a0: ghidra.util.task.Task) -> None: ...

    def taskCompleted(self, __a0: ghidra.util.task.Task) -> None: ...

    def toFront(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    def waitForCurrentTask(self) -> None: ...

    @property
    def allowAnyScriptOption(self) -> None: ...  # No getter available.

    @allowAnyScriptOption.setter
    def allowAnyScriptOption(self, value: bool) -> None: ...

    @property
    def allowCommonScriptOption(self) -> None: ...  # No getter available.

    @allowCommonScriptOption.setter
    def allowCommonScriptOption(self, value: bool) -> None: ...

    @property
    def allowLatinScriptOption(self) -> None: ...  # No getter available.

    @allowLatinScriptOption.setter
    def allowLatinScriptOption(self, value: bool) -> None: ...

    @property
    def createButton(self) -> javax.swing.JButton: ...

    @property
    def excludeCodecErrors(self) -> None: ...  # No getter available.

    @excludeCodecErrors.setter
    def excludeCodecErrors(self, value: bool) -> None: ...

    @property
    def excludeNonStdCtrlChars(self) -> None: ...  # No getter available.

    @excludeNonStdCtrlChars.setter
    def excludeNonStdCtrlChars(self, value: bool) -> None: ...

    @property
    def requireValidStringOption(self) -> None: ...  # No getter available.

    @requireValidStringOption.setter
    def requireValidStringOption(self, value: bool) -> None: ...

    @property
    def requiredScript(self) -> None: ...  # No getter available.

    @requiredScript.setter
    def requiredScript(self, value: java.lang.Character.UnicodeScript) -> None: ...

    @property
    def selectedCharset(self) -> None: ...  # No getter available.

    @selectedCharset.setter
    def selectedCharset(self, value: unicode) -> None: ...

    @property
    def showAdvancedOptions(self) -> None: ...  # No getter available.

    @showAdvancedOptions.setter
    def showAdvancedOptions(self, value: bool) -> None: ...

    @property
    def showScriptOptions(self) -> None: ...  # No getter available.

    @showScriptOptions.setter
    def showScriptOptions(self, value: bool) -> None: ...

    @property
    def stringModel(self) -> ghidra.app.plugin.core.strings.EncodedStringsTableModel: ...