from typing import overload
import ghidra.app.plugin.core.debug.mapping
import ghidra.debug.api.platform
import ghidra.framework.plugintool
import ghidra.program.model.lang
import ghidra.trace.model
import java.lang


class AbstractDebuggerPlatformOffer(object, ghidra.app.plugin.core.debug.mapping.DebuggerPlatformOffer):




    def __init__(self, __a0: unicode, __a1: ghidra.program.model.lang.CompilerSpec): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    @overload
    def getCompilerSpec(self) -> ghidra.program.model.lang.CompilerSpec: ...

    @overload
    def getCompilerSpec(self, __a0: ghidra.program.model.lang.LanguageID, __a1: ghidra.program.model.lang.CompilerSpecID) -> ghidra.program.model.lang.CompilerSpec: ...

    def getCompilerSpecID(self) -> ghidra.program.model.lang.CompilerSpecID: ...

    def getConfidence(self) -> int: ...

    def getDescription(self) -> unicode: ...

    def getLanguage(self) -> ghidra.program.model.lang.Language: ...

    def getLanguageID(self) -> ghidra.program.model.lang.LanguageID: ...

    def hashCode(self) -> int: ...

    def isCreatorOf(self, __a0: ghidra.debug.api.platform.DebuggerPlatformMapper) -> bool: ...

    def isOverride(self) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def take(self, __a0: ghidra.framework.plugintool.PluginTool, __a1: ghidra.trace.model.Trace) -> ghidra.debug.api.platform.DebuggerPlatformMapper: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def compilerSpec(self) -> ghidra.program.model.lang.CompilerSpec: ...

    @property
    def compilerSpecID(self) -> ghidra.program.model.lang.CompilerSpecID: ...

    @property
    def confidence(self) -> int: ...

    @property
    def description(self) -> unicode: ...

    @property
    def language(self) -> ghidra.program.model.lang.Language: ...

    @property
    def languageID(self) -> ghidra.program.model.lang.LanguageID: ...

    @property
    def override(self) -> bool: ...