import pytest
from .file import YamlFile as YamlFile
from _typeshed import Incomplete
from pathlib import Path

logger: Incomplete
enable_plugin: bool

def pytest_addhooks(pluginmanager) -> None: ...
def pytest_addoption(parser) -> None: ...
def pytest_configure(config: pytest.Config): ...
def pytest_collect_file(parent, file_path: Path): ...
