
# This file was generated by 'versioneer.py' (0.18) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-07-15T08:12:43+0000",
 "dirty": false,
 "error": null,
 "full-revisionid": "5b16d0143f9ff0aff1fb58b64ccfa447e6200122",
 "version": "0.9.0"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
