from typing import overload
import ghidra.codecompare.graphanalysis
import java.lang


class DataNGram(object, java.lang.Comparable):




    def __init__(self, __a0: ghidra.codecompare.graphanalysis.DataVertex, __a1: int, __a2: int, __a3: int): ...



    @overload
    def compareTo(self, __a0: ghidra.codecompare.graphanalysis.DataNGram) -> int: ...

    @overload
    def compareTo(self, __a0: object) -> int: ...

    def equalHash(self, __a0: ghidra.codecompare.graphanalysis.DataNGram) -> bool: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def graphsDiffer(self, __a0: ghidra.codecompare.graphanalysis.DataNGram) -> bool: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

