from typing import overload
import java.lang
import java.util.concurrent


class AsyncLazyValue(object):




    def __init__(self, __a0: java.util.function.Supplier): ...



    def equals(self, __a0: object) -> bool: ...

    def forget(self) -> None: ...

    def getClass(self) -> java.lang.Class: ...

    def hashCode(self) -> int: ...

    def isBusy(self) -> bool: ...

    def isDone(self) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def provide(self) -> java.util.concurrent.CompletableFuture: ...

    def request(self) -> java.util.concurrent.CompletableFuture: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def busy(self) -> bool: ...

    @property
    def done(self) -> bool: ...