from typing import overload
import ghidra.trace.database
import ghidra.trace.database.map
import ghidra.trace.model.property
import java.io
import java.lang
import java.util


class DBTraceAddressPropertyManager(object, ghidra.trace.model.property.TraceAddressPropertyManager, ghidra.trace.database.DBTraceManager):




    def __init__(self, __a0: db.DBHandle, __a1: ghidra.framework.data.OpenMode, __a2: java.util.concurrent.locks.ReadWriteLock, __a3: ghidra.util.task.TaskMonitor, __a4: ghidra.program.model.lang.Language, __a5: ghidra.trace.database.DBTrace, __a6: ghidra.trace.database.thread.DBTraceThreadManager): ...



    def createPropertyMap(self, __a0: unicode, __a1: java.lang.Class) -> ghidra.trace.database.map.AbstractDBTracePropertyMap: ...

    def dbError(self, __a0: java.io.IOException) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getAllProperties(self) -> java.util.Map: ...

    def getApiPropertyManager(self) -> ghidra.trace.model.property.TraceAddressPropertyManager: ...

    def getClass(self) -> java.lang.Class: ...

    def getOrCreatePropertyMap(self, __a0: unicode, __a1: java.lang.Class) -> ghidra.trace.database.map.AbstractDBTracePropertyMap: ...

    def getOrCreatePropertyMapSuper(self, __a0: unicode, __a1: java.lang.Class) -> ghidra.trace.model.property.TracePropertyMap: ...

    @overload
    def getPropertyMap(self, __a0: unicode) -> ghidra.trace.model.property.TracePropertyMap: ...

    @overload
    def getPropertyMap(self, __a0: unicode, __a1: java.lang.Class) -> ghidra.trace.model.property.TracePropertyMap: ...

    def getPropertyMapExtends(self, __a0: unicode, __a1: java.lang.Class) -> ghidra.trace.model.property.TracePropertyMap: ...

    def hashCode(self) -> int: ...

    def invalidateCache(self, __a0: bool) -> None: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def allProperties(self) -> java.util.Map: ...

    @property
    def apiPropertyManager(self) -> ghidra.trace.model.property.TraceAddressPropertyManager: ...