from typing import overload
import com.sun.jdi
import com.sun.jdi.event
import ghidra.dbg.jdi.manager
import ghidra.dbg.jdi.manager.breakpoint
import java.lang


class JdiEventsListener(object):








    def accessWatchpointHit(self, __a0: com.sun.jdi.event.AccessWatchpointEvent, __a1: ghidra.dbg.jdi.manager.JdiCause) -> None: ...

    def breakpointCreated(self, __a0: ghidra.dbg.jdi.manager.breakpoint.JdiBreakpointInfo, __a1: ghidra.dbg.jdi.manager.JdiCause) -> None: ...

    def breakpointDeleted(self, __a0: ghidra.dbg.jdi.manager.breakpoint.JdiBreakpointInfo, __a1: ghidra.dbg.jdi.manager.JdiCause) -> None: ...

    def breakpointHit(self, __a0: com.sun.jdi.event.BreakpointEvent, __a1: ghidra.dbg.jdi.manager.JdiCause) -> None: ...

    def breakpointModified(self, __a0: ghidra.dbg.jdi.manager.breakpoint.JdiBreakpointInfo, __a1: ghidra.dbg.jdi.manager.breakpoint.JdiBreakpointInfo, __a2: ghidra.dbg.jdi.manager.JdiCause) -> None: ...

    def classPrepare(self, __a0: com.sun.jdi.event.ClassPrepareEvent, __a1: ghidra.dbg.jdi.manager.JdiCause) -> None: ...

    def classUnload(self, __a0: com.sun.jdi.event.ClassUnloadEvent, __a1: ghidra.dbg.jdi.manager.JdiCause) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def exceptionHit(self, __a0: com.sun.jdi.event.ExceptionEvent, __a1: ghidra.dbg.jdi.manager.JdiCause) -> None: ...

    def getClass(self) -> java.lang.Class: ...

    def hashCode(self) -> int: ...

    def libraryLoaded(self, __a0: com.sun.jdi.VirtualMachine, __a1: unicode, __a2: ghidra.dbg.jdi.manager.JdiCause) -> None: ...

    def libraryUnloaded(self, __a0: com.sun.jdi.VirtualMachine, __a1: unicode, __a2: ghidra.dbg.jdi.manager.JdiCause) -> None: ...

    def memoryChanged(self, __a0: com.sun.jdi.VirtualMachine, __a1: long, __a2: int, __a3: ghidra.dbg.jdi.manager.JdiCause) -> None: ...

    def methodEntry(self, __a0: com.sun.jdi.event.MethodEntryEvent, __a1: ghidra.dbg.jdi.manager.JdiCause) -> None: ...

    def methodExit(self, __a0: com.sun.jdi.event.MethodExitEvent, __a1: ghidra.dbg.jdi.manager.JdiCause) -> None: ...

    def monitorContendedEnter(self, __a0: com.sun.jdi.event.MonitorContendedEnterEvent, __a1: ghidra.dbg.jdi.manager.JdiCause) -> None: ...

    def monitorContendedEntered(self, __a0: com.sun.jdi.event.MonitorContendedEnteredEvent, __a1: ghidra.dbg.jdi.manager.JdiCause) -> None: ...

    def monitorWait(self, __a0: com.sun.jdi.event.MonitorWaitEvent, __a1: ghidra.dbg.jdi.manager.JdiCause) -> None: ...

    def monitorWaited(self, __a0: com.sun.jdi.event.MonitorWaitedEvent, __a1: ghidra.dbg.jdi.manager.JdiCause) -> None: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def processShutdown(self, __a0: com.sun.jdi.event.Event, __a1: ghidra.dbg.jdi.manager.JdiCause) -> None: ...

    def processStop(self, __a0: com.sun.jdi.event.EventSet, __a1: ghidra.dbg.jdi.manager.JdiCause) -> None: ...

    def stepComplete(self, __a0: com.sun.jdi.event.StepEvent, __a1: ghidra.dbg.jdi.manager.JdiCause) -> None: ...

    def threadExited(self, __a0: com.sun.jdi.event.ThreadDeathEvent, __a1: ghidra.dbg.jdi.manager.JdiCause) -> None: ...

    def threadSelected(self, __a0: com.sun.jdi.ThreadReference, __a1: com.sun.jdi.StackFrame, __a2: ghidra.dbg.jdi.manager.JdiCause) -> None: ...

    def threadStarted(self, __a0: com.sun.jdi.event.ThreadStartEvent, __a1: ghidra.dbg.jdi.manager.JdiCause) -> None: ...

    def threadStateChanged(self, __a0: com.sun.jdi.ThreadReference, __a1: int, __a2: ghidra.dbg.jdi.manager.JdiCause, __a3: ghidra.dbg.jdi.manager.JdiReason) -> None: ...

    def toString(self) -> unicode: ...

    def vmDied(self, __a0: com.sun.jdi.event.VMDeathEvent, __a1: ghidra.dbg.jdi.manager.JdiCause) -> None: ...

    def vmDisconnected(self, __a0: com.sun.jdi.event.VMDisconnectEvent, __a1: ghidra.dbg.jdi.manager.JdiCause) -> None: ...

    def vmInterrupted(self) -> None: ...

    def vmSelected(self, __a0: com.sun.jdi.VirtualMachine, __a1: ghidra.dbg.jdi.manager.JdiCause) -> None: ...

    def vmStarted(self, __a0: com.sun.jdi.event.VMStartEvent, __a1: ghidra.dbg.jdi.manager.JdiCause) -> None: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    def watchpointHit(self, __a0: com.sun.jdi.event.WatchpointEvent, __a1: ghidra.dbg.jdi.manager.JdiCause) -> None: ...

    def watchpointModified(self, __a0: com.sun.jdi.event.ModificationWatchpointEvent, __a1: ghidra.dbg.jdi.manager.JdiCause) -> None: ...

