from typing import overload
import ghidra.util.database.spatial.rect
import java.lang


class EuclideanSpace2D(object):








    def compareX(self, __a0: object, __a1: object) -> int: ...

    def compareY(self, __a0: object, __a1: object) -> int: ...

    def distX(self, __a0: object, __a1: object) -> float: ...

    def distY(self, __a0: object, __a1: object) -> float: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getFull(self) -> ghidra.util.database.spatial.rect.Rectangle2D: ...

    def hashCode(self) -> int: ...

    def maxX(self, __a0: object, __a1: object) -> object: ...

    def maxY(self, __a0: object, __a1: object) -> object: ...

    def midX(self, __a0: object, __a1: object) -> object: ...

    def midY(self, __a0: object, __a1: object) -> object: ...

    def minX(self, __a0: object, __a1: object) -> object: ...

    def minY(self, __a0: object, __a1: object) -> object: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def full(self) -> ghidra.util.database.spatial.rect.Rectangle2D: ...