from typing import overload
import java.lang
import java.util.concurrent


class CheckPeriodicallyRunnable(object, java.lang.Runnable):




    def __init__(self, __a0: bool, __a1: int, __a2: java.util.concurrent.TimeUnit, __a3: java.util.concurrent.Callable): ...



    def awaitTermination(self) -> None: ...

    def dispose(self) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def run(self) -> None: ...

    def startChecking(self, __a0: int, __a1: java.util.concurrent.TimeUnit) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

