from typing import overload
import ghidra.app.plugin.core.debug.gui.thread
import ghidra.program.model.address
import ghidra.program.model.listing
import ghidra.trace.model
import ghidra.trace.model.thread
import java.lang


class ThreadRow(object):




    def __init__(self, __a0: ghidra.app.plugin.core.debug.gui.thread.DebuggerThreadsProvider, __a1: ghidra.trace.model.thread.TraceThread): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getComment(self) -> unicode: ...

    def getCreationSnap(self) -> long: ...

    def getDestructionSnap(self) -> unicode: ...

    def getFunction(self) -> ghidra.program.model.listing.Function: ...

    def getLifespan(self) -> ghidra.trace.model.Lifespan: ...

    def getModule(self) -> unicode: ...

    def getName(self) -> unicode: ...

    def getProgramCounter(self) -> ghidra.program.model.address.Address: ...

    def getStackPointer(self) -> ghidra.program.model.address.Address: ...

    def getState(self) -> ghidra.app.plugin.core.debug.gui.thread.ThreadState: ...

    def getThread(self) -> ghidra.trace.model.thread.TraceThread: ...

    def getTrace(self) -> ghidra.trace.model.Trace: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def setComment(self, __a0: unicode) -> None: ...

    def setName(self, __a0: unicode) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def comment(self) -> unicode: ...

    @comment.setter
    def comment(self, value: unicode) -> None: ...

    @property
    def creationSnap(self) -> long: ...

    @property
    def destructionSnap(self) -> unicode: ...

    @property
    def function(self) -> ghidra.program.model.listing.Function: ...

    @property
    def lifespan(self) -> ghidra.trace.model.Lifespan: ...

    @property
    def module(self) -> unicode: ...

    @property
    def name(self) -> unicode: ...

    @name.setter
    def name(self, value: unicode) -> None: ...

    @property
    def programCounter(self) -> ghidra.program.model.address.Address: ...

    @property
    def stackPointer(self) -> ghidra.program.model.address.Address: ...

    @property
    def state(self) -> ghidra.app.plugin.core.debug.gui.thread.ThreadState: ...

    @property
    def thread(self) -> ghidra.trace.model.thread.TraceThread: ...

    @property
    def trace(self) -> ghidra.trace.model.Trace: ...