# This file was auto-generated by Fern from our API Definition.

import typing

from ...types.invoice_discount_options import InvoiceDiscountOptions

Discounts = typing.Union[str, InvoiceDiscountOptions]
