from typing import overload
import ghidra.app.plugin.core.decompile.actions
import java.lang


class RetypeStructFieldTask(ghidra.app.plugin.core.decompile.actions.RetypeFieldTask):




    def __init__(self, __a0: ghidra.framework.plugintool.PluginTool, __a1: ghidra.program.model.listing.Program, __a2: ghidra.app.plugin.core.decompile.DecompilerProvider, __a3: ghidra.app.decompiler.ClangToken, __a4: ghidra.program.model.data.Composite): ...



    def commit(self) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getTransactionName(self) -> unicode: ...

    def hashCode(self) -> int: ...

    def isValidAfter(self) -> bool: ...

    def isValidBefore(self) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def runTask(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def transactionName(self) -> unicode: ...

    @property
    def validAfter(self) -> bool: ...

    @property
    def validBefore(self) -> bool: ...