from typing import List
from typing import overload
import ghidra.app.plugin.core.terminal
import java.lang
import java.nio


class ThreadedTerminal(ghidra.app.plugin.core.terminal.DefaultTerminal):




    def __init__(self, __a0: ghidra.app.plugin.core.terminal.TerminalProvider, __a1: java.io.InputStream): ...



    def addTerminalListener(self, __a0: ghidra.app.plugin.core.terminal.TerminalListener) -> None: ...

    def close(self) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getColumns(self) -> int: ...

    def getCursorColumn(self) -> int: ...

    def getCursorRow(self) -> int: ...

    def getDisplayText(self) -> unicode: ...

    def getFullText(self) -> unicode: ...

    def getLineText(self, __a0: int) -> unicode: ...

    def getRangeText(self, __a0: int, __a1: int, __a2: int, __a3: int) -> unicode: ...

    def getRows(self) -> int: ...

    def getScrollBackRows(self) -> int: ...

    def getSubTitle(self) -> unicode: ...

    def hashCode(self) -> int: ...

    @overload
    def injectDisplayOutput(self, __a0: List[int]) -> None: ...

    @overload
    def injectDisplayOutput(self, __a0: java.nio.ByteBuffer) -> None: ...

    def isTerminated(self) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def removeTerminalListener(self, __a0: ghidra.app.plugin.core.terminal.TerminalListener) -> None: ...

    def setDynamicSize(self) -> None: ...

    @overload
    def setFixedSize(self, __a0: int, __a1: int) -> None: ...

    @overload
    def setFixedSize(self, __a0: int, __a1: int) -> None: ...

    def setMaxScrollBackRows(self, __a0: int) -> None: ...

    def setSubTitle(self, __a0: unicode) -> None: ...

    def setTerminateAction(self, __a0: java.lang.Runnable) -> None: ...

    def terminated(self) -> None: ...

    def toFront(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

