from typing import overload
import ghidra.framework.plugintool
import ghidra.program.util
import ghidra.trace.model.program
import java.lang


class TraceSelectionPluginEvent(ghidra.framework.plugintool.PluginEvent):
    NAME: unicode = u'TraceSelection'



    def __init__(self, __a0: unicode, __a1: ghidra.program.util.ProgramSelection, __a2: ghidra.trace.model.program.TraceProgramView): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getEventName(self) -> unicode: ...

    def getSelection(self) -> ghidra.program.util.ProgramSelection: ...

    def getSourceName(self) -> unicode: ...

    def getToolEventName(self) -> unicode: ...

    def getTraceProgramView(self) -> ghidra.trace.model.program.TraceProgramView: ...

    def getTriggerEvent(self) -> ghidra.framework.plugintool.PluginEvent: ...

    def hashCode(self) -> int: ...

    def isToolEvent(self) -> bool: ...

    @staticmethod
    def lookupToolEventName(__a0: java.lang.Class) -> unicode: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def setSourceName(self, __a0: unicode) -> None: ...

    def setTriggerEvent(self, __a0: ghidra.framework.plugintool.PluginEvent) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def selection(self) -> ghidra.program.util.ProgramSelection: ...

    @property
    def traceProgramView(self) -> ghidra.trace.model.program.TraceProgramView: ...