from typing import List
from typing import overload
import ghidra.file.formats.android.art
import ghidra.program.model.data
import ghidra.program.model.listing
import ghidra.util.task
import java.lang


class ArtHeader_085(ghidra.file.formats.android.art.ArtHeader):




    def __init__(self, __a0: ghidra.app.util.bin.BinaryReader): ...



    def equals(self, __a0: object) -> bool: ...

    def getArtMethodCountForVersion(self) -> int: ...

    def getBlocks(self) -> List[object]: ...

    def getBootImageBegin(self) -> int: ...

    def getBootImageChecksum(self) -> int: ...

    def getBootImageComponentCount(self) -> int: ...

    def getClass(self) -> java.lang.Class: ...

    def getComponentCount(self) -> int: ...

    def getDataSize(self) -> int: ...

    def getImageBegin(self) -> int: ...

    def getImageChecksum_(self) -> int: ...

    def getImageReservationSize(self) -> int: ...

    def getImageRoots(self) -> int: ...

    def getImageSize(self) -> int: ...

    def getMagic(self) -> unicode: ...

    def getOatChecksum(self) -> int: ...

    def getOatDataBegin(self) -> int: ...

    def getOatDataEnd(self) -> int: ...

    def getOatFileBegin(self) -> int: ...

    def getOatFileEnd(self) -> int: ...

    def getPointerSize(self) -> int: ...

    def getVersion(self) -> unicode: ...

    def hashCode(self) -> int: ...

    def isAppImage(self) -> bool: ...

    def markup(self, __a0: ghidra.program.model.listing.Program, __a1: ghidra.util.task.TaskMonitor) -> None: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toDataType(self) -> ghidra.program.model.data.DataType: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def appImage(self) -> bool: ...

    @property
    def artMethodCountForVersion(self) -> int: ...

    @property
    def blocks(self) -> List[object]: ...

    @property
    def bootImageBegin(self) -> int: ...

    @property
    def bootImageChecksum(self) -> int: ...

    @property
    def bootImageComponentCount(self) -> int: ...

    @property
    def componentCount(self) -> int: ...

    @property
    def dataSize(self) -> int: ...

    @property
    def imageBegin(self) -> int: ...

    @property
    def imageChecksum_(self) -> int: ...

    @property
    def imageReservationSize(self) -> int: ...

    @property
    def imageRoots(self) -> int: ...

    @property
    def imageSize(self) -> int: ...

    @property
    def oatChecksum(self) -> int: ...

    @property
    def oatDataBegin(self) -> int: ...

    @property
    def oatDataEnd(self) -> int: ...

    @property
    def oatFileBegin(self) -> int: ...

    @property
    def oatFileEnd(self) -> int: ...

    @property
    def pointerSize(self) -> int: ...