from typing import overload
import db
import java.lang


class TableColumn(object):




    @overload
    def __init__(self, __a0: db.Field): ...

    @overload
    def __init__(self, __a0: db.Field, __a1: bool): ...



    def column(self) -> int: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getColumnField(self) -> db.Field: ...

    def hashCode(self) -> int: ...

    def isIndexed(self) -> bool: ...

    def name(self) -> unicode: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def columnField(self) -> db.Field: ...

    @property
    def indexed(self) -> bool: ...