from typing import overload
import ghidra.feature.vt.api.main
import ghidra.program.database
import ghidra.util
import java.lang


class VTMatchTagDB(ghidra.program.database.DatabaseObject, ghidra.feature.vt.api.main.VTMatchTag):








    @overload
    def compareTo(self, __a0: ghidra.feature.vt.api.main.VTMatchTag) -> int: ...

    @overload
    def compareTo(self, __a0: object) -> int: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getKey(self) -> long: ...

    def getName(self) -> unicode: ...

    def hashCode(self) -> int: ...

    def isDeleted(self, __a0: ghidra.util.Lock) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def setInvalid(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def name(self) -> unicode: ...