from typing import Iterator
from typing import List
from typing import overload
import ghidra.comm.util
import java.lang
import java.util
import java.util.function
import java.util.stream


class BitmaskSet(object, java.util.Set):




    @overload
    def __init__(self, __a0: ghidra.comm.util.BitmaskSet): ...

    @overload
    def __init__(self, __a0: java.lang.Class): ...

    @overload
    def __init__(self, __a0: java.lang.Class, __a1: long): ...

    @overload
    def __init__(self, __a0: java.lang.Class, __a1: java.util.Collection): ...

    def __iter__(self): ...

    @overload
    def add(self, __a0: java.lang.Enum) -> bool: ...

    @overload
    def add(self, __a0: object) -> bool: ...

    def addAll(self, __a0: java.util.Collection) -> bool: ...

    def clear(self) -> None: ...

    def contains(self, __a0: object) -> bool: ...

    def containsAll(self, __a0: java.util.Collection) -> bool: ...

    def containsAny(self, __a0: java.util.Collection) -> bool: ...

    @staticmethod
    def copyOf(__a0: java.util.Collection) -> java.util.Set: ...

    def equals(self, __a0: object) -> bool: ...

    def forEach(self, __a0: java.util.function.Consumer) -> None: ...

    def getBitmask(self) -> long: ...

    def getClass(self) -> java.lang.Class: ...

    def getUniverse(self) -> java.lang.Class: ...

    def hashCode(self) -> int: ...

    def isEmpty(self) -> bool: ...

    def iterator(self) -> java.util.Iterator: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    @staticmethod
    def of(__a0: List[java.lang.Enum]) -> ghidra.comm.util.BitmaskSet: ...

    def parallelStream(self) -> java.util.stream.Stream: ...

    def removeAll(self, __a0: java.util.Collection) -> bool: ...

    def removeIf(self, __a0: java.util.function.Predicate) -> bool: ...

    def retainAll(self, __a0: java.util.Collection) -> bool: ...

    def setBitmask(self, __a0: long) -> None: ...

    def size(self) -> int: ...

    def spliterator(self) -> java.util.Spliterator: ...

    def stream(self) -> java.util.stream.Stream: ...

    @overload
    def toArray(self) -> List[object]: ...

    @overload
    def toArray(self, __a0: List[object]) -> List[object]: ...

    @overload
    def toArray(self, __a0: java.util.function.IntFunction) -> List[object]: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def bitmask(self) -> long: ...

    @bitmask.setter
    def bitmask(self, value: long) -> None: ...

    @property
    def empty(self) -> bool: ...

    @property
    def universe(self) -> java.lang.Class: ...