from typing import overload
import ghidra.program.model.address
import ghidra.trace.model
import ghidra.trace.model.property
import ghidra.trace.model.stack
import ghidra.trace.model.thread
import ghidra.trace.util
import java.lang
import java.util


class TracePropertyMap(ghidra.trace.model.property.TracePropertyMapOperations, object):








    def clear(self, __a0: ghidra.trace.model.Lifespan, __a1: ghidra.program.model.address.AddressRange) -> bool: ...

    def delete(self) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def get(self, __a0: long, __a1: ghidra.program.model.address.Address) -> object: ...

    def getAddressSetView(self, __a0: ghidra.trace.model.Lifespan) -> ghidra.program.model.address.AddressSetView: ...

    def getClass(self) -> java.lang.Class: ...

    def getEntries(self, __a0: ghidra.trace.model.Lifespan, __a1: ghidra.program.model.address.AddressRange) -> java.util.Collection: ...

    def getEntry(self, __a0: long, __a1: ghidra.program.model.address.Address) -> java.util.Map.Entry: ...

    @overload
    def getPropertyMapRegisterSpace(self, __a0: ghidra.trace.model.stack.TraceStackFrame, __a1: bool) -> ghidra.trace.model.property.TracePropertyMapSpace: ...

    @overload
    def getPropertyMapRegisterSpace(self, __a0: ghidra.trace.model.thread.TraceThread, __a1: int, __a2: bool) -> ghidra.trace.model.property.TracePropertyMapSpace: ...

    @overload
    def getPropertyMapSpace(self, __a0: ghidra.program.model.address.AddressSpace, __a1: bool) -> ghidra.trace.model.property.TracePropertyMapSpace: ...

    @overload
    def getPropertyMapSpace(self, __a0: ghidra.trace.util.TraceAddressSpace, __a1: bool) -> ghidra.trace.model.property.TracePropertyMapSpace: ...

    def getValueClass(self) -> java.lang.Class: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    @overload
    def set(self, __a0: ghidra.trace.model.Lifespan, __a1: ghidra.program.model.address.Address, __a2: object) -> None: ...

    @overload
    def set(self, __a0: ghidra.trace.model.Lifespan, __a1: ghidra.program.model.address.AddressRange, __a2: object) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def valueClass(self) -> java.lang.Class: ...