from typing import List
from typing import overload
import docking
import docking.action
import ghidra.app.plugin.core.debug.gui.memview
import ghidra.framework.plugintool
import ghidra.program.model.listing
import ghidra.util
import java.awt.event
import java.lang
import java.util
import javax.swing


class MemviewProvider(ghidra.framework.plugintool.ComponentProviderAdapter):




    def __init__(self, __a0: ghidra.framework.plugintool.PluginTool, __a1: ghidra.app.plugin.core.debug.gui.memview.DebuggerMemviewPlugin): ...



    def addBox(self, __a0: ghidra.app.plugin.core.debug.gui.memview.MemoryBox) -> None: ...

    def addBoxes(self, __a0: List[object]) -> None: ...

    def addLocalAction(self, __a0: docking.action.DockingActionIf) -> None: ...

    def addToTool(self) -> None: ...

    def adjustFontSize(self, __a0: bool) -> None: ...

    def applyFilter(self) -> None: ...

    def canBeParent(self) -> bool: ...

    def changeZoomA(self, __a0: int) -> None: ...

    def changeZoomT(self, __a0: int) -> None: ...

    def closeComponent(self) -> None: ...

    def componentActivated(self) -> None: ...

    def componentDeactived(self) -> None: ...

    def componentHidden(self) -> None: ...

    def componentShown(self) -> None: ...

    def contextChanged(self) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getActionContext(self, __a0: java.awt.event.MouseEvent) -> docking.ActionContext: ...

    def getClass(self) -> java.lang.Class: ...

    def getComponent(self) -> javax.swing.JComponent: ...

    def getContextType(self) -> java.lang.Class: ...

    def getDefaultWindowPosition(self) -> docking.WindowPosition: ...

    def getHelpInfo(self) -> unicode: ...

    def getHelpLocation(self) -> ghidra.util.HelpLocation: ...

    def getHelpObject(self) -> object: ...

    def getIcon(self) -> javax.swing.Icon: ...

    def getInstanceID(self) -> long: ...

    def getIntraGroupPosition(self) -> docking.WindowPosition: ...

    def getLocalActions(self) -> java.util.Set: ...

    @staticmethod
    def getMappedName(__a0: unicode, __a1: unicode) -> unicode: ...

    @staticmethod
    def getMappedOwner(__a0: unicode, __a1: unicode) -> unicode: ...

    def getName(self) -> unicode: ...

    def getOwner(self) -> unicode: ...

    def getSubTitle(self) -> unicode: ...

    def getTabText(self) -> unicode: ...

    def getTitle(self) -> unicode: ...

    def getTool(self) -> docking.Tool: ...

    def getWindowGroup(self) -> unicode: ...

    def getWindowSubMenuName(self) -> unicode: ...

    def getZoomAmountA(self) -> float: ...

    def getZoomAmountT(self) -> float: ...

    @overload
    def goTo(self, __a0: ghidra.app.plugin.core.debug.gui.memview.MemoryBox) -> None: ...

    @overload
    def goTo(self, __a0: int, __a1: int) -> None: ...

    def hashCode(self) -> int: ...

    def initViews(self) -> None: ...

    def isActive(self) -> bool: ...

    def isApplyFilter(self) -> bool: ...

    def isFocusedProvider(self) -> bool: ...

    def isInTool(self) -> bool: ...

    def isSnapshot(self) -> bool: ...

    def isTransient(self) -> bool: ...

    def isVisible(self) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def refresh(self) -> None: ...

    @staticmethod
    def registerProviderNameOwnerChange(__a0: unicode, __a1: unicode, __a2: unicode, __a3: unicode) -> None: ...

    def removeFromTool(self) -> None: ...

    def requestFocus(self) -> None: ...

    def reset(self) -> None: ...

    def resetFontSize(self) -> None: ...

    def selectPanelPosition(self, __a0: java.util.Set) -> None: ...

    def selectTableEntry(self, __a0: java.util.Set) -> None: ...

    def setBoxes(self, __a0: List[object]) -> None: ...

    def setBoxesInPanel(self, __a0: List[object]) -> None: ...

    def setHelpLocation(self, __a0: ghidra.util.HelpLocation) -> None: ...

    def setIntraGroupPosition(self, __a0: docking.WindowPosition) -> None: ...

    def setProgram(self, __a0: ghidra.program.model.listing.Program) -> None: ...

    def setSubTitle(self, __a0: unicode) -> None: ...

    def setTabText(self, __a0: unicode) -> None: ...

    def setTitle(self, __a0: unicode) -> None: ...

    def setVisible(self, __a0: bool) -> None: ...

    def toFront(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def boxes(self) -> None: ...  # No getter available.

    @boxes.setter
    def boxes(self, value: List[object]) -> None: ...

    @property
    def boxesInPanel(self) -> None: ...  # No getter available.

    @boxesInPanel.setter
    def boxesInPanel(self, value: List[object]) -> None: ...

    @property
    def component(self) -> javax.swing.JComponent: ...

    @property
    def helpLocation(self) -> ghidra.util.HelpLocation: ...

    @helpLocation.setter
    def helpLocation(self, value: ghidra.util.HelpLocation) -> None: ...

    @property
    def program(self) -> None: ...  # No getter available.

    @program.setter
    def program(self, value: ghidra.program.model.listing.Program) -> None: ...

    @property
    def zoomAmountA(self) -> float: ...

    @property
    def zoomAmountT(self) -> float: ...