COMMANDS = [
    "clean",
    "config create",
    "config download",
    "config rename",
    "config upload",
    "download tools",
    "erase",
    "flash all",
    "flash bt121",
    "flash ex",
    "flash habs",
    "flash mn",
    "flash re",
    "flash xbee",
    "flash config",
    "logo",
    "show configs",
    "show devices",
    "show rigids",
    "show versions",
]
