from typing import overload
import docking
import docking.action
import docking.widgets.tree
import ghidra.program.model.data
import ghidra.util
import ghidra.util.task
import java.awt
import java.awt.event
import java.lang
import java.util
import javax.swing
import javax.swing.tree


class DataTypeChooserDialog(docking.DialogComponentProvider):




    def __init__(self, __a0: ghidra.app.plugin.core.datamgr.DataTypeManagerPlugin): ...



    def addAction(self, __a0: docking.action.DockingActionIf) -> None: ...

    def clearStatusText(self) -> None: ...

    def close(self) -> None: ...

    def dispose(self) -> None: ...

    def equals(self, __a0: object) -> bool: ...

    def getActionContext(self, __a0: java.awt.event.MouseEvent) -> docking.ActionContext: ...

    def getActions(self) -> java.util.Set: ...

    def getBackground(self) -> java.awt.Color: ...

    def getClass(self) -> java.lang.Class: ...

    def getComponent(self) -> javax.swing.JComponent: ...

    def getDefaultButton(self) -> javax.swing.JButton: ...

    def getDefaultSize(self) -> java.awt.Dimension: ...

    def getFocusComponent(self) -> java.awt.Component: ...

    def getHelpLocation(self) -> ghidra.util.HelpLocation: ...

    def getId(self) -> int: ...

    def getInitialLocation(self) -> java.awt.Point: ...

    def getPreferredSize(self) -> java.awt.Dimension: ...

    def getRememberLocation(self) -> bool: ...

    def getRememberSize(self) -> bool: ...

    def getSelectedDataType(self) -> ghidra.program.model.data.DataType: ...

    def getStatusText(self) -> unicode: ...

    def getTitle(self) -> unicode: ...

    def getTreeFilterProvider(self) -> docking.widgets.tree.GTreeFilterProvider: ...

    def getUseSharedLocation(self) -> bool: ...

    def hashCode(self) -> int: ...

    def hideTaskMonitorComponent(self) -> None: ...

    def isModal(self) -> bool: ...

    def isResizeable(self) -> bool: ...

    def isRunningTask(self) -> bool: ...

    def isShowing(self) -> bool: ...

    def isTransient(self) -> bool: ...

    def isVisible(self) -> bool: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def removeAction(self, __a0: docking.action.DockingActionIf) -> None: ...

    def setAccessibleDescription(self, __a0: unicode) -> None: ...

    def setBackground(self, __a0: java.awt.Color) -> None: ...

    def setCursor(self, __a0: java.awt.Cursor) -> None: ...

    def setDefaultButton(self, __a0: javax.swing.JButton) -> None: ...

    def setDefaultSize(self, __a0: int, __a1: int) -> None: ...

    def setFilterFieldEditable(self, __a0: bool) -> None: ...

    def setFilterText(self, __a0: unicode) -> None: ...

    def setFirstNodeSelected(self) -> None: ...

    def setFocusComponent(self, __a0: java.awt.Component) -> None: ...

    def setHelpLocation(self, __a0: ghidra.util.HelpLocation) -> None: ...

    def setInitialLocation(self, __a0: int, __a1: int) -> None: ...

    @overload
    def setMinimumSize(self, __a0: java.awt.Dimension) -> None: ...

    @overload
    def setMinimumSize(self, __a0: int, __a1: int) -> None: ...

    def setPreferredSize(self, __a0: int, __a1: int) -> None: ...

    def setRememberLocation(self, __a0: bool) -> None: ...

    def setRememberSize(self, __a0: bool) -> None: ...

    def setResizable(self, __a0: bool) -> None: ...

    def setSelectedPath(self, __a0: javax.swing.tree.TreePath) -> None: ...

    def setStatusJustification(self, __a0: int) -> None: ...

    @overload
    def setStatusText(self, __a0: unicode) -> None: ...

    @overload
    def setStatusText(self, __a0: unicode, __a1: ghidra.util.MessageType) -> None: ...

    @overload
    def setStatusText(self, __a0: unicode, __a1: ghidra.util.MessageType, __a2: bool) -> None: ...

    def setTitle(self, __a0: unicode) -> None: ...

    def setTransient(self, __a0: bool) -> None: ...

    def setTreeFilterProvider(self, __a0: docking.widgets.tree.GTreeFilterProvider) -> None: ...

    def setUseSharedLocation(self, __a0: bool) -> None: ...

    def showPrepopulatedDialog(self, __a0: docking.Tool, __a1: unicode) -> None: ...

    def showTaskMonitorComponent(self, __a0: unicode, __a1: bool, __a2: bool) -> ghidra.util.task.TaskMonitor: ...

    def taskCancelled(self, __a0: ghidra.util.task.Task) -> None: ...

    def taskCompleted(self, __a0: ghidra.util.task.Task) -> None: ...

    def toFront(self) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    def waitForCurrentTask(self) -> None: ...

    @property
    def filterFieldEditable(self) -> None: ...  # No getter available.

    @filterFieldEditable.setter
    def filterFieldEditable(self, value: bool) -> None: ...

    @property
    def filterText(self) -> None: ...  # No getter available.

    @filterText.setter
    def filterText(self, value: unicode) -> None: ...

    @property
    def focusComponent(self) -> java.awt.Component: ...

    @focusComponent.setter
    def focusComponent(self, value: java.awt.Component) -> None: ...

    @property
    def selectedDataType(self) -> ghidra.program.model.data.DataType: ...

    @property
    def selectedPath(self) -> None: ...  # No getter available.

    @selectedPath.setter
    def selectedPath(self, value: javax.swing.tree.TreePath) -> None: ...

    @property
    def treeFilterProvider(self) -> docking.widgets.tree.GTreeFilterProvider: ...

    @treeFilterProvider.setter
    def treeFilterProvider(self, value: docking.widgets.tree.GTreeFilterProvider) -> None: ...