from typing import overload
import ghidra.features.bsim.query.description
import ghidra.features.bsim.query.elastic
import java.lang


class IDElasticResolution(object):
    idString: unicode




    class ExternalFunction(ghidra.features.bsim.query.elastic.IDElasticResolution):
        idString: unicode



        def __init__(self, __a0: unicode, __a1: unicode): ...



        def equals(self, __a0: object) -> bool: ...

        def getClass(self) -> java.lang.Class: ...

        def hashCode(self) -> int: ...

        def notify(self) -> None: ...

        def notifyAll(self) -> None: ...

        def resolve(self, __a0: ghidra.features.bsim.query.elastic.ElasticDatabase, __a1: ghidra.features.bsim.query.description.ExecutableRecord) -> None: ...

        def toString(self) -> unicode: ...

        @overload
        def wait(self) -> None: ...

        @overload
        def wait(self, __a0: long) -> None: ...

        @overload
        def wait(self, __a0: long, __a1: int) -> None: ...



    def __init__(self): ...



    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def resolve(self, __a0: ghidra.features.bsim.query.elastic.ElasticDatabase, __a1: ghidra.features.bsim.query.description.ExecutableRecord) -> None: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

