# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: RevaComment.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x11RevaComment.proto\x12\x0cRevaProtocol\"I\n\x15RevaSetCommentRequest\x12\x0f\n\x07\x61\x64\x64ress\x18\x01 \x01(\t\x12\x0e\n\x06symbol\x18\x02 \x01(\t\x12\x0f\n\x07\x63omment\x18\x03 \x01(\t\"\x18\n\x16RevaSetCommentResponse2o\n\x12RevaCommentService\x12Y\n\nSetComment\x12#.RevaProtocol.RevaSetCommentRequest\x1a$.RevaProtocol.RevaSetCommentResponse\"\x00\x42\x0f\n\rreva.protocolb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'RevaComment_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'\n\rreva.protocol'
  _globals['_REVASETCOMMENTREQUEST']._serialized_start=35
  _globals['_REVASETCOMMENTREQUEST']._serialized_end=108
  _globals['_REVASETCOMMENTRESPONSE']._serialized_start=110
  _globals['_REVASETCOMMENTRESPONSE']._serialized_end=134
  _globals['_REVACOMMENTSERVICE']._serialized_start=136
  _globals['_REVACOMMENTSERVICE']._serialized_end=247
# @@protoc_insertion_point(module_scope)
