# automatically generated by the FlatBuffers compiler, do not modify

# namespace: fb

import flatbuffers
from flatbuffers.compat import import_numpy
np = import_numpy()

class Boundingbox2D(object):
    __slots__ = ['_tab']

    @classmethod
    def GetRootAs(cls, buf, offset=0):
        n = flatbuffers.encode.Get(flatbuffers.packer.uoffset, buf, offset)
        x = Boundingbox2D()
        x.Init(buf, n + offset)
        return x

    @classmethod
    def GetRootAsBoundingbox2D(cls, buf, offset=0):
        """This method is deprecated. Please switch to GetRootAs."""
        return cls.GetRootAs(buf, offset)
    # Boundingbox2D
    def Init(self, buf, pos):
        self._tab = flatbuffers.table.Table(buf, pos)

    # Boundingbox2D
    def CenterPoint(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(4))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from seerep.fb.Point2D import Point2D
            obj = Point2D()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Boundingbox2D
    def SpatialExtent(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(6))
        if o != 0:
            x = self._tab.Indirect(o + self._tab.Pos)
            from seerep.fb.Point2D import Point2D
            obj = Point2D()
            obj.Init(self._tab.Bytes, x)
            return obj
        return None

    # Boundingbox2D
    def Rotation(self):
        o = flatbuffers.number_types.UOffsetTFlags.py_type(self._tab.Offset(8))
        if o != 0:
            return self._tab.Get(flatbuffers.number_types.Float32Flags, o + self._tab.Pos)
        return 0.0

def Start(builder): builder.StartObject(3)
def Boundingbox2DStart(builder):
    """This method is deprecated. Please switch to Start."""
    return Start(builder)
def AddCenterPoint(builder, centerPoint): builder.PrependUOffsetTRelativeSlot(0, flatbuffers.number_types.UOffsetTFlags.py_type(centerPoint), 0)
def Boundingbox2DAddCenterPoint(builder, centerPoint):
    """This method is deprecated. Please switch to AddCenterPoint."""
    return AddCenterPoint(builder, centerPoint)
def AddSpatialExtent(builder, spatialExtent): builder.PrependUOffsetTRelativeSlot(1, flatbuffers.number_types.UOffsetTFlags.py_type(spatialExtent), 0)
def Boundingbox2DAddSpatialExtent(builder, spatialExtent):
    """This method is deprecated. Please switch to AddSpatialExtent."""
    return AddSpatialExtent(builder, spatialExtent)
def AddRotation(builder, rotation): builder.PrependFloat32Slot(2, rotation, 0.0)
def Boundingbox2DAddRotation(builder, rotation):
    """This method is deprecated. Please switch to AddRotation."""
    return AddRotation(builder, rotation)
def End(builder): return builder.EndObject()
def Boundingbox2DEnd(builder):
    """This method is deprecated. Please switch to End."""
    return End(builder)