from typing import List
from typing import overload
import ghidra.app.util.bin
import ghidra.file.formats.android.oat
import ghidra.file.formats.android.oat.bundle
import ghidra.program.model.data
import java.lang


class OatHeader_007(ghidra.file.formats.android.oat.OatHeader):




    def __init__(self, __a0: ghidra.app.util.bin.BinaryReader): ...



    def equals(self, __a0: object) -> bool: ...

    def getChecksum(self) -> int: ...

    def getClass(self) -> java.lang.Class: ...

    def getDexFileCount(self) -> int: ...

    def getExecutableOffset(self) -> int: ...

    def getImageFileLocationData_(self) -> List[int]: ...

    def getImageFileLocationOatChecksum(self) -> int: ...

    def getImageFileLocationOatDataBegin(self) -> int: ...

    def getImageFileLocationSize_(self) -> int: ...

    def getInstructionSet(self) -> ghidra.file.formats.android.oat.OatInstructionSet: ...

    def getInterpreterToCompiledCodeBridgeOffset(self) -> int: ...

    def getInterpreterToInterpreterBridgeOffset(self) -> int: ...

    def getJniDlsymLookupOffset(self) -> int: ...

    def getKeyValueStoreSize(self) -> int: ...

    def getMagic(self) -> unicode: ...

    def getOatDexFileList(self) -> List[object]: ...

    def getOatDexFilesOffset(self, __a0: ghidra.app.util.bin.BinaryReader) -> int: ...

    def getPortableResolutionTrampolineOffset(self) -> int: ...

    def getPortableToInterpreterBridgeOffset(self) -> int: ...

    def getVersion(self) -> unicode: ...

    def hashCode(self) -> int: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def parse(self, __a0: ghidra.app.util.bin.BinaryReader, __a1: ghidra.file.formats.android.oat.bundle.OatBundle) -> None: ...

    def toDataType(self) -> ghidra.program.model.data.DataType: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

    @property
    def checksum(self) -> int: ...

    @property
    def dexFileCount(self) -> int: ...

    @property
    def executableOffset(self) -> int: ...

    @property
    def imageFileLocationData_(self) -> List[int]: ...

    @property
    def imageFileLocationOatChecksum(self) -> int: ...

    @property
    def imageFileLocationOatDataBegin(self) -> int: ...

    @property
    def imageFileLocationSize_(self) -> int: ...

    @property
    def instructionSet(self) -> ghidra.file.formats.android.oat.OatInstructionSet: ...

    @property
    def interpreterToCompiledCodeBridgeOffset(self) -> int: ...

    @property
    def interpreterToInterpreterBridgeOffset(self) -> int: ...

    @property
    def jniDlsymLookupOffset(self) -> int: ...

    @property
    def keyValueStoreSize(self) -> int: ...

    @property
    def oatDexFileList(self) -> List[object]: ...

    @property
    def portableResolutionTrampolineOffset(self) -> int: ...

    @property
    def portableToInterpreterBridgeOffset(self) -> int: ...