from typing import overload
import ghidra.app.plugin.assembler.sleigh.grammars
import ghidra.app.plugin.assembler.sleigh.symbol
import ghidra.asm.wild.symbol
import java.lang
import java.util


class WildAssemblyNumericMapTerminal(ghidra.asm.wild.symbol.WildAssemblyTerminal):
    map: java.util.Map



    def __init__(self, __a0: unicode, __a1: java.util.Map): ...



    @overload
    def compareTo(self, __a0: ghidra.app.plugin.assembler.sleigh.symbol.AssemblySymbol) -> int: ...

    @overload
    def compareTo(self, __a0: object) -> int: ...

    def equals(self, __a0: object) -> bool: ...

    def getClass(self) -> java.lang.Class: ...

    def getName(self) -> unicode: ...

    def getSuggestions(self, __a0: unicode, __a1: ghidra.app.plugin.assembler.sleigh.symbol.AssemblyNumericSymbols) -> java.util.Collection: ...

    def hashCode(self) -> int: ...

    def match(self, __a0: unicode, __a1: int, __a2: ghidra.app.plugin.assembler.sleigh.grammars.AssemblyGrammar, __a3: ghidra.app.plugin.assembler.sleigh.symbol.AssemblyNumericSymbols) -> java.util.Collection: ...

    def notify(self) -> None: ...

    def notifyAll(self) -> None: ...

    def takesOperandIndex(self) -> bool: ...

    def toString(self) -> unicode: ...

    @overload
    def wait(self) -> None: ...

    @overload
    def wait(self, __a0: long) -> None: ...

    @overload
    def wait(self, __a0: long, __a1: int) -> None: ...

