__title__ = 'segment_multiwell_plate'
__description__ = 'segment_multiwell_plate: Automatically divide multi-well plate into separate images of each well'
__version__ = '0.5'
__author__ = 'Murray Cutforth'
__author_email__ = 'murray.cutforth@gmail.com'
__license__ = 'GPL 2.0'
__url__ = 'https://github.com/murraycutforth/segment-multiwell-plate'
