# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class ChargeStatusEnum(str, enum.Enum):
    SUCCEEDED = "succeeded"
    FAILED = "failed"
    PENDING = "pending"

    def visit(
        self,
        succeeded: typing.Callable[[], T_Result],
        failed: typing.Callable[[], T_Result],
        pending: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is ChargeStatusEnum.SUCCEEDED:
            return succeeded()
        if self is ChargeStatusEnum.FAILED:
            return failed()
        if self is ChargeStatusEnum.PENDING:
            return pending()
