# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class CouponDuration(str, enum.Enum):
    ONCE = "once"
    REPEATING = "repeating"
    FOREVER = "forever"

    def visit(
        self,
        once: typing.Callable[[], T_Result],
        repeating: typing.Callable[[], T_Result],
        forever: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is CouponDuration.ONCE:
            return once()
        if self is CouponDuration.REPEATING:
            return repeating()
        if self is CouponDuration.FOREVER:
            return forever()
