# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class EventType(str, enum.Enum):
    ALL = "all"
    ACCOUNT_CREATED = "account.created"
    ACCOUNT_UPDATED = "account.updated"
    ACCOUNT_DELETED = "account.deleted"
    API_TOKEN_CREATED = "api_token.created"
    API_TOKEN_UPDATED = "api_token.updated"
    API_TOKEN_DELETED = "api_token.deleted"
    CHARGE_CREATED = "charge.created"
    CHARGE_UPDATED = "charge.updated"
    CHARGE_DELETED = "charge.deleted"
    COUPON_CREATED = "coupon.created"
    COUPON_UPDATED = "coupon.updated"
    COUPON_DELETED = "coupon.deleted"
    CREDIT_NOTE_CREATED = "credit_note.created"
    CREDIT_NOTE_UPDATED = "credit_note.updated"
    CREDIT_NOTE_DELETED = "credit_note.deleted"
    CREDIT_NOTE_ITEM_CREATED = "credit_note_item.created"
    CREDIT_NOTE_ITEM_UPDATED = "credit_note_item.updated"
    CREDIT_NOTE_ITEM_DELETED = "credit_note_item.deleted"
    CUSTOMER_CREATED = "customer.created"
    CUSTOMER_UPDATED = "customer.updated"
    CUSTOMER_DELETED = "customer.deleted"
    CUSTOMER_BALANCE_TRANSACTION_CREATED = "customer_balance_transaction.created"
    CUSTOMER_BALANCE_TRANSACTION_UPDATED = "customer_balance_transaction.updated"
    CUSTOMER_BALANCE_TRANSACTION_DELETED = "customer_balance_transaction.deleted"
    DELIVERY_ATTEMPT_CREATED = "delivery_attempt.created"
    DELIVERY_ATTEMPT_UPDATED = "delivery_attempt.updated"
    DELIVERY_ATTEMPT_DELETED = "delivery_attempt.deleted"
    DISCOUNT_CREATED = "discount.created"
    DISCOUNT_UPDATED = "discount.updated"
    DISCOUNT_DELETED = "discount.deleted"
    EVENT_CREATED = "event.created"
    EVENT_UPDATED = "event.updated"
    EVENT_DELETED = "event.deleted"
    INVITE_CREATED = "invite.created"
    INVITE_UPDATED = "invite.updated"
    INVITE_DELETED = "invite.deleted"
    INVITE_ITEM_DISCOUNT_CREATED = "invite_item_discount.created"
    INVITE_ITEM_DISCOUNT_UPDATED = "invite_item_discount.updated"
    INVITE_ITEM_DISCOUNT_DELETED = "invite_item_discount.deleted"
    INVOICE_CREATED = "invoice.created"
    INVOICE_UPDATED = "invoice.updated"
    INVOICE_DELETED = "invoice.deleted"
    INVOICE_DISCOUNT_CREATED = "invoice_discount.created"
    INVOICE_DISCOUNT_UPDATED = "invoice_discount.updated"
    INVOICE_DISCOUNT_DELETED = "invoice_discount.deleted"
    INVOICE_ITEM_CREATED = "invoice_item.created"
    INVOICE_ITEM_UPDATED = "invoice_item.updated"
    INVOICE_ITEM_DELETED = "invoice_item.deleted"
    PAYMENT_INTENT_CREATED = "payment_intent.created"
    PAYMENT_INTENT_UPDATED = "payment_intent.updated"
    PAYMENT_INTENT_DELETED = "payment_intent.deleted"
    PAYMENT_METHOD_CREATED = "payment_method.created"
    PAYMENT_METHOD_UPDATED = "payment_method.updated"
    PAYMENT_METHOD_DELETED = "payment_method.deleted"
    PAYMENT_PROCESSOR_CREATED = "payment_processor.created"
    PAYMENT_PROCESSOR_UPDATED = "payment_processor.updated"
    PAYMENT_PROCESSOR_DELETED = "payment_processor.deleted"
    PRICE_CREATED = "price.created"
    PRICE_UPDATED = "price.updated"
    PRICE_DELETED = "price.deleted"
    PRICE_TIER_CREATED = "price_tier.created"
    PRICE_TIER_UPDATED = "price_tier.updated"
    PRICE_TIER_DELETED = "price_tier.deleted"
    PRODUCT_CREATED = "product.created"
    PRODUCT_UPDATED = "product.updated"
    PRODUCT_DELETED = "product.deleted"
    PROMOTION_CODE_CREATED = "promotion_code.created"
    PROMOTION_CODE_UPDATED = "promotion_code.updated"
    PROMOTION_CODE_DELETED = "promotion_code.deleted"
    REFUND_CREATED = "refund.created"
    REFUND_UPDATED = "refund.updated"
    REFUND_DELETED = "refund.deleted"
    CUSTOMER_SUBSCRIPTION_CREATED = "customer.subscription.created"
    CUSTOMER_SUBSCRIPTION_UPDATED = "customer.subscription.updated"
    CUSTOMER_SUBSCRIPTION_DELETED = "customer.subscription.deleted"
    CUSTOMER_SUBSCRIPTION_TRIAL_WILL_END = "customer.subscription.trial_will_end"
    SUBSCRIPTION_ITEM_CREATED = "subscription_item.created"
    SUBSCRIPTION_ITEM_UPDATED = "subscription_item.updated"
    SUBSCRIPTION_ITEM_DELETED = "subscription_item.deleted"
    USER_CREATED = "user.created"
    USER_UPDATED = "user.updated"
    USER_DELETED = "user.deleted"
    USER_LOGIN_CREATED = "user_login.created"
    USER_LOGIN_UPDATED = "user_login.updated"
    USER_LOGIN_DELETED = "user_login.deleted"
    USER_RECORD_CREATED = "user_record.created"
    USER_RECORD_UPDATED = "user_record.updated"
    USER_RECORD_DELETED = "user_record.deleted"
    USER_RECORD_SUMMARY_CREATED = "user_record_summary.created"
    USER_RECORD_SUMMARY_UPDATED = "user_record_summary.updated"
    USER_RECORD_SUMMARY_DELETED = "user_record_summary.deleted"
    WEBHOOK_ENDPOINT_CREATED = "webhook_endpoint.created"
    WEBHOOK_ENDPOINT_UPDATED = "webhook_endpoint.updated"
    WEBHOOK_ENDPOINT_DELETED = "webhook_endpoint.deleted"

    def visit(
        self,
        all_: typing.Callable[[], T_Result],
        account_created: typing.Callable[[], T_Result],
        account_updated: typing.Callable[[], T_Result],
        account_deleted: typing.Callable[[], T_Result],
        api_token_created: typing.Callable[[], T_Result],
        api_token_updated: typing.Callable[[], T_Result],
        api_token_deleted: typing.Callable[[], T_Result],
        charge_created: typing.Callable[[], T_Result],
        charge_updated: typing.Callable[[], T_Result],
        charge_deleted: typing.Callable[[], T_Result],
        coupon_created: typing.Callable[[], T_Result],
        coupon_updated: typing.Callable[[], T_Result],
        coupon_deleted: typing.Callable[[], T_Result],
        credit_note_created: typing.Callable[[], T_Result],
        credit_note_updated: typing.Callable[[], T_Result],
        credit_note_deleted: typing.Callable[[], T_Result],
        credit_note_item_created: typing.Callable[[], T_Result],
        credit_note_item_updated: typing.Callable[[], T_Result],
        credit_note_item_deleted: typing.Callable[[], T_Result],
        customer_created: typing.Callable[[], T_Result],
        customer_updated: typing.Callable[[], T_Result],
        customer_deleted: typing.Callable[[], T_Result],
        customer_balance_transaction_created: typing.Callable[[], T_Result],
        customer_balance_transaction_updated: typing.Callable[[], T_Result],
        customer_balance_transaction_deleted: typing.Callable[[], T_Result],
        delivery_attempt_created: typing.Callable[[], T_Result],
        delivery_attempt_updated: typing.Callable[[], T_Result],
        delivery_attempt_deleted: typing.Callable[[], T_Result],
        discount_created: typing.Callable[[], T_Result],
        discount_updated: typing.Callable[[], T_Result],
        discount_deleted: typing.Callable[[], T_Result],
        event_created: typing.Callable[[], T_Result],
        event_updated: typing.Callable[[], T_Result],
        event_deleted: typing.Callable[[], T_Result],
        invite_created: typing.Callable[[], T_Result],
        invite_updated: typing.Callable[[], T_Result],
        invite_deleted: typing.Callable[[], T_Result],
        invite_item_discount_created: typing.Callable[[], T_Result],
        invite_item_discount_updated: typing.Callable[[], T_Result],
        invite_item_discount_deleted: typing.Callable[[], T_Result],
        invoice_created: typing.Callable[[], T_Result],
        invoice_updated: typing.Callable[[], T_Result],
        invoice_deleted: typing.Callable[[], T_Result],
        invoice_discount_created: typing.Callable[[], T_Result],
        invoice_discount_updated: typing.Callable[[], T_Result],
        invoice_discount_deleted: typing.Callable[[], T_Result],
        invoice_item_created: typing.Callable[[], T_Result],
        invoice_item_updated: typing.Callable[[], T_Result],
        invoice_item_deleted: typing.Callable[[], T_Result],
        payment_intent_created: typing.Callable[[], T_Result],
        payment_intent_updated: typing.Callable[[], T_Result],
        payment_intent_deleted: typing.Callable[[], T_Result],
        payment_method_created: typing.Callable[[], T_Result],
        payment_method_updated: typing.Callable[[], T_Result],
        payment_method_deleted: typing.Callable[[], T_Result],
        payment_processor_created: typing.Callable[[], T_Result],
        payment_processor_updated: typing.Callable[[], T_Result],
        payment_processor_deleted: typing.Callable[[], T_Result],
        price_created: typing.Callable[[], T_Result],
        price_updated: typing.Callable[[], T_Result],
        price_deleted: typing.Callable[[], T_Result],
        price_tier_created: typing.Callable[[], T_Result],
        price_tier_updated: typing.Callable[[], T_Result],
        price_tier_deleted: typing.Callable[[], T_Result],
        product_created: typing.Callable[[], T_Result],
        product_updated: typing.Callable[[], T_Result],
        product_deleted: typing.Callable[[], T_Result],
        promotion_code_created: typing.Callable[[], T_Result],
        promotion_code_updated: typing.Callable[[], T_Result],
        promotion_code_deleted: typing.Callable[[], T_Result],
        refund_created: typing.Callable[[], T_Result],
        refund_updated: typing.Callable[[], T_Result],
        refund_deleted: typing.Callable[[], T_Result],
        customer_subscription_created: typing.Callable[[], T_Result],
        customer_subscription_updated: typing.Callable[[], T_Result],
        customer_subscription_deleted: typing.Callable[[], T_Result],
        customer_subscription_trial_will_end: typing.Callable[[], T_Result],
        subscription_item_created: typing.Callable[[], T_Result],
        subscription_item_updated: typing.Callable[[], T_Result],
        subscription_item_deleted: typing.Callable[[], T_Result],
        user_created: typing.Callable[[], T_Result],
        user_updated: typing.Callable[[], T_Result],
        user_deleted: typing.Callable[[], T_Result],
        user_login_created: typing.Callable[[], T_Result],
        user_login_updated: typing.Callable[[], T_Result],
        user_login_deleted: typing.Callable[[], T_Result],
        user_record_created: typing.Callable[[], T_Result],
        user_record_updated: typing.Callable[[], T_Result],
        user_record_deleted: typing.Callable[[], T_Result],
        user_record_summary_created: typing.Callable[[], T_Result],
        user_record_summary_updated: typing.Callable[[], T_Result],
        user_record_summary_deleted: typing.Callable[[], T_Result],
        webhook_endpoint_created: typing.Callable[[], T_Result],
        webhook_endpoint_updated: typing.Callable[[], T_Result],
        webhook_endpoint_deleted: typing.Callable[[], T_Result],
    ) -> T_Result:
        if self is EventType.ALL:
            return all_()
        if self is EventType.ACCOUNT_CREATED:
            return account_created()
        if self is EventType.ACCOUNT_UPDATED:
            return account_updated()
        if self is EventType.ACCOUNT_DELETED:
            return account_deleted()
        if self is EventType.API_TOKEN_CREATED:
            return api_token_created()
        if self is EventType.API_TOKEN_UPDATED:
            return api_token_updated()
        if self is EventType.API_TOKEN_DELETED:
            return api_token_deleted()
        if self is EventType.CHARGE_CREATED:
            return charge_created()
        if self is EventType.CHARGE_UPDATED:
            return charge_updated()
        if self is EventType.CHARGE_DELETED:
            return charge_deleted()
        if self is EventType.COUPON_CREATED:
            return coupon_created()
        if self is EventType.COUPON_UPDATED:
            return coupon_updated()
        if self is EventType.COUPON_DELETED:
            return coupon_deleted()
        if self is EventType.CREDIT_NOTE_CREATED:
            return credit_note_created()
        if self is EventType.CREDIT_NOTE_UPDATED:
            return credit_note_updated()
        if self is EventType.CREDIT_NOTE_DELETED:
            return credit_note_deleted()
        if self is EventType.CREDIT_NOTE_ITEM_CREATED:
            return credit_note_item_created()
        if self is EventType.CREDIT_NOTE_ITEM_UPDATED:
            return credit_note_item_updated()
        if self is EventType.CREDIT_NOTE_ITEM_DELETED:
            return credit_note_item_deleted()
        if self is EventType.CUSTOMER_CREATED:
            return customer_created()
        if self is EventType.CUSTOMER_UPDATED:
            return customer_updated()
        if self is EventType.CUSTOMER_DELETED:
            return customer_deleted()
        if self is EventType.CUSTOMER_BALANCE_TRANSACTION_CREATED:
            return customer_balance_transaction_created()
        if self is EventType.CUSTOMER_BALANCE_TRANSACTION_UPDATED:
            return customer_balance_transaction_updated()
        if self is EventType.CUSTOMER_BALANCE_TRANSACTION_DELETED:
            return customer_balance_transaction_deleted()
        if self is EventType.DELIVERY_ATTEMPT_CREATED:
            return delivery_attempt_created()
        if self is EventType.DELIVERY_ATTEMPT_UPDATED:
            return delivery_attempt_updated()
        if self is EventType.DELIVERY_ATTEMPT_DELETED:
            return delivery_attempt_deleted()
        if self is EventType.DISCOUNT_CREATED:
            return discount_created()
        if self is EventType.DISCOUNT_UPDATED:
            return discount_updated()
        if self is EventType.DISCOUNT_DELETED:
            return discount_deleted()
        if self is EventType.EVENT_CREATED:
            return event_created()
        if self is EventType.EVENT_UPDATED:
            return event_updated()
        if self is EventType.EVENT_DELETED:
            return event_deleted()
        if self is EventType.INVITE_CREATED:
            return invite_created()
        if self is EventType.INVITE_UPDATED:
            return invite_updated()
        if self is EventType.INVITE_DELETED:
            return invite_deleted()
        if self is EventType.INVITE_ITEM_DISCOUNT_CREATED:
            return invite_item_discount_created()
        if self is EventType.INVITE_ITEM_DISCOUNT_UPDATED:
            return invite_item_discount_updated()
        if self is EventType.INVITE_ITEM_DISCOUNT_DELETED:
            return invite_item_discount_deleted()
        if self is EventType.INVOICE_CREATED:
            return invoice_created()
        if self is EventType.INVOICE_UPDATED:
            return invoice_updated()
        if self is EventType.INVOICE_DELETED:
            return invoice_deleted()
        if self is EventType.INVOICE_DISCOUNT_CREATED:
            return invoice_discount_created()
        if self is EventType.INVOICE_DISCOUNT_UPDATED:
            return invoice_discount_updated()
        if self is EventType.INVOICE_DISCOUNT_DELETED:
            return invoice_discount_deleted()
        if self is EventType.INVOICE_ITEM_CREATED:
            return invoice_item_created()
        if self is EventType.INVOICE_ITEM_UPDATED:
            return invoice_item_updated()
        if self is EventType.INVOICE_ITEM_DELETED:
            return invoice_item_deleted()
        if self is EventType.PAYMENT_INTENT_CREATED:
            return payment_intent_created()
        if self is EventType.PAYMENT_INTENT_UPDATED:
            return payment_intent_updated()
        if self is EventType.PAYMENT_INTENT_DELETED:
            return payment_intent_deleted()
        if self is EventType.PAYMENT_METHOD_CREATED:
            return payment_method_created()
        if self is EventType.PAYMENT_METHOD_UPDATED:
            return payment_method_updated()
        if self is EventType.PAYMENT_METHOD_DELETED:
            return payment_method_deleted()
        if self is EventType.PAYMENT_PROCESSOR_CREATED:
            return payment_processor_created()
        if self is EventType.PAYMENT_PROCESSOR_UPDATED:
            return payment_processor_updated()
        if self is EventType.PAYMENT_PROCESSOR_DELETED:
            return payment_processor_deleted()
        if self is EventType.PRICE_CREATED:
            return price_created()
        if self is EventType.PRICE_UPDATED:
            return price_updated()
        if self is EventType.PRICE_DELETED:
            return price_deleted()
        if self is EventType.PRICE_TIER_CREATED:
            return price_tier_created()
        if self is EventType.PRICE_TIER_UPDATED:
            return price_tier_updated()
        if self is EventType.PRICE_TIER_DELETED:
            return price_tier_deleted()
        if self is EventType.PRODUCT_CREATED:
            return product_created()
        if self is EventType.PRODUCT_UPDATED:
            return product_updated()
        if self is EventType.PRODUCT_DELETED:
            return product_deleted()
        if self is EventType.PROMOTION_CODE_CREATED:
            return promotion_code_created()
        if self is EventType.PROMOTION_CODE_UPDATED:
            return promotion_code_updated()
        if self is EventType.PROMOTION_CODE_DELETED:
            return promotion_code_deleted()
        if self is EventType.REFUND_CREATED:
            return refund_created()
        if self is EventType.REFUND_UPDATED:
            return refund_updated()
        if self is EventType.REFUND_DELETED:
            return refund_deleted()
        if self is EventType.CUSTOMER_SUBSCRIPTION_CREATED:
            return customer_subscription_created()
        if self is EventType.CUSTOMER_SUBSCRIPTION_UPDATED:
            return customer_subscription_updated()
        if self is EventType.CUSTOMER_SUBSCRIPTION_DELETED:
            return customer_subscription_deleted()
        if self is EventType.CUSTOMER_SUBSCRIPTION_TRIAL_WILL_END:
            return customer_subscription_trial_will_end()
        if self is EventType.SUBSCRIPTION_ITEM_CREATED:
            return subscription_item_created()
        if self is EventType.SUBSCRIPTION_ITEM_UPDATED:
            return subscription_item_updated()
        if self is EventType.SUBSCRIPTION_ITEM_DELETED:
            return subscription_item_deleted()
        if self is EventType.USER_CREATED:
            return user_created()
        if self is EventType.USER_UPDATED:
            return user_updated()
        if self is EventType.USER_DELETED:
            return user_deleted()
        if self is EventType.USER_LOGIN_CREATED:
            return user_login_created()
        if self is EventType.USER_LOGIN_UPDATED:
            return user_login_updated()
        if self is EventType.USER_LOGIN_DELETED:
            return user_login_deleted()
        if self is EventType.USER_RECORD_CREATED:
            return user_record_created()
        if self is EventType.USER_RECORD_UPDATED:
            return user_record_updated()
        if self is EventType.USER_RECORD_DELETED:
            return user_record_deleted()
        if self is EventType.USER_RECORD_SUMMARY_CREATED:
            return user_record_summary_created()
        if self is EventType.USER_RECORD_SUMMARY_UPDATED:
            return user_record_summary_updated()
        if self is EventType.USER_RECORD_SUMMARY_DELETED:
            return user_record_summary_deleted()
        if self is EventType.WEBHOOK_ENDPOINT_CREATED:
            return webhook_endpoint_created()
        if self is EventType.WEBHOOK_ENDPOINT_UPDATED:
            return webhook_endpoint_updated()
        if self is EventType.WEBHOOK_ENDPOINT_DELETED:
            return webhook_endpoint_deleted()
