# This file was auto-generated by Fern from our API Definition.

import enum
import typing

T_Result = typing.TypeVar("T_Result")


class PricingTiersEnum(str, enum.Enum):
    GRADUATED = "graduated"
    VOLUME = "volume"

    def visit(self, graduated: typing.Callable[[], T_Result], volume: typing.Callable[[], T_Result]) -> T_Result:
        if self is PricingTiersEnum.GRADUATED:
            return graduated()
        if self is PricingTiersEnum.VOLUME:
            return volume()
