
# This file was generated by 'versioneer.py' (0.29) from
# revision-control system data, or from the parent directory name of an
# unpacked source archive. Distribution tarballs contain a pre-generated copy
# of this file.

import json

version_json = '''
{
 "date": "2024-07-15T13:39:05+0200",
 "dirty": false,
 "error": null,
 "full-revisionid": "72c6a816917b5ae1700fa469248278206a3bdf00",
 "version": "2.25.2"
}
'''  # END VERSION_JSON


def get_versions():
    return json.loads(version_json)
